### ISSUE TITLE
Crash building Raleway-Black

### ISSUE THREAD

**Issue by brawer** [googlei18n/fontmake#10]
fontmake crashes when building [Raleway-Black](https://github.com/FlossFoundry/Raleway/tree/master/src/Raleway-Black.ufo) from UFO; see [log](https://travis-ci.org/FlossFoundry/Raleway/builds/108472790). Probably, the root cause is https://github.com/behdad/fonttools/issues/520.

**Comment by jamesgk** [comment]
Indeed, that UFO has an invalid openTypeOS2WinDescent according to the UFO spec:

https://github.com/FlossFoundry/Raleway/blob/master/src/Raleway-Black.ufo/fontinfo.plist#L139
http://unifiedfontobject.org/versions/ufo3/fontinfo.html#opentypeos/2

But the thread linked to seems to conclude that a UFO->OTF compiler should not crash on this, so we can change things to handle it.

**Comment by jamesgk** [comment]
I think this was fixed by https://github.com/googlei18n/ufo2ft/commit/87b270fa4ed23fc60e8eb1cc1c0660cf5faf357d
