### ISSUE TITLE
question: TTF differences between glyphs.app and pipeline generation

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#105]
I generated TTF fonts using the glyphs.app and pipeline using 
https://github.com/googlei18n/noto-source/blob/master/src/NotoSansArabic-MM.glyphs
as input

Then ran notodiff to see if there are any differences. It found some of the differences (see the images):

![uni08f0](https://cloud.githubusercontent.com/assets/13322623/16839864/41b502cc-4986-11e6-9dcb-3397e9b086e0.png)
![uni08f1](https://cloud.githubusercontent.com/assets/13322623/16839860/41b4618c-4986-11e6-8205-a0c902527a63.png)
![uni08f2](https://cloud.githubusercontent.com/assets/13322623/16839859/41b4253c-4986-11e6-8049-e0650ec44c33.png)
![uni08f3](https://cloud.githubusercontent.com/assets/13322623/16839863/41b4c8c0-4986-11e6-83dd-c8a4cc745e5e.png)
![uni08f4](https://cloud.githubusercontent.com/assets/13322623/16839861/41b480ae-4986-11e6-9c80-48e9b3e33cb7.png)
![uni08f5](https://cloud.githubusercontent.com/assets/13322623/16839862/41b48dce-4986-11e6-992d-1d600728eb73.png)
![uni08f6](https://cloud.githubusercontent.com/assets/13322623/16839865/41c4dec2-4986-11e6-90c7-6873afa5f5a9.png)
![uni08f7](https://cloud.githubusercontent.com/assets/13322623/16839866/41c855f2-4986-11e6-8696-acb3f4a53a30.png)
![uni08f8](https://cloud.githubusercontent.com/assets/13322623/16839870/41c9478c-4986-11e6-950c-d6471e2b2a02.png)
![uni08f9](https://cloud.githubusercontent.com/assets/13322623/16839869/41c8ae12-4986-11e6-8e7b-b2cf3be9c558.png)
![uni08fa](https://cloud.githubusercontent.com/assets/13322623/16839868/41c89f1c-4986-11e6-9bad-0c91187f1f39.png)
![uni08fb](https://cloud.githubusercontent.com/assets/13322623/16839867/41c8951c-4986-11e6-979c-30d99504bc20.png)
![uni08fe](https://cloud.githubusercontent.com/assets/13322623/16839872/41da2566-4986-11e6-8aa4-c39b6abba066.png)
![uni064f](https://cloud.githubusercontent.com/assets/13322623/16839871/41d89f7a-4986-11e6-9ae9-e45f872ec4ad.png)

@behdad  , @jamesgk : are these differences intended or meaningful or a pipeline error or a glyphs.app error or notodiff error?

**Comment by marekjez86** [comment]
are they somehow related to left-to-right vs right-to-left flow?

**Comment by jamesgk** [comment]
It definitely means something, whether there's a width or metrics difference or something else between the fonts. I don't think it's LTR/RTL related. Whatever the case, it seems to me that notodiff should handle the difference more gracefully. I'll look into it.

**Comment by behdad** [comment]
Humm.  It's still worth figuring out why what we produce is different.  Any insights @jamesgk ?

**Comment by jamesgk** [comment]
Oh right, I meant to follow up about this. It's because the glyphs we output with GDEF class 3 (mark) don't have width of zero, but the ones output by Glyphs do. We're just taking the widths from the Glyphs source. To set mark widths to zero I think we'll have to look at the GDEF table after calling feaLib and change the compiled OTF/TTF glyph widths.

**Comment by behdad** [comment]
I see.  Yes, I think that makes sense.  Can you file an issue against ufo2ft so we see what others have to say about it?
