### ISSUE TITLE
Building masters and instances from design space file

### ISSUE THREAD

**Issue by khaledhosny** [googlei18n/fontmake#107]
There does not seem to be away to build both masters and instances from design space file at the same time, `fontmake -m Mada.designspace` will build the masters only, and `fontmake -i -m Mada.designspace` will build the instances only, but I’d like to build both in the same invocation.

I think the `else` block [here](https://github.com/googlei18n/fontmake/blob/master/Lib/fontmake/font_project.py#L269) should be moved out so that masters are always built even when interpolating.

**Comment by davelab6** [comment]
Being able to build one set or the other or both sounds good to me

**Comment by jamesgk** [comment]
Is this really a common thing to do? I thought it was unlikely that someone would want to generate master OTF/TTFs from a designspace (maybe for variation fonts, not sure what else), much less that they'd want masters in addition to instances.

I definitely don't think fontmake should always generate masters (that takes extra time). Allowing one or the other or both complicates the API. So basically I'm not convinced this is a good idea.

**Comment by behdad** [comment]
James: looks like most people don't define an instance on top of the masters.  Ie. they only define instances for the "interpolated" instances.  In these scenarios, it's desirable to export both masters and instances (and the difference is irrelevant to the final user).

**Comment by jamesgk** [comment]
OK, I see. In that case, I guess it's also annoying if the "masters" and "instances" end up in different `master_*` and `instance_*` directories. So if we add an option to generate both it should probably put them all in one place (I'd say `instance_*`).
