### ISSUE TITLE
incompatibility: fontmake is case sensitive glyphs.app is not

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#109]
Could fontmake "just do it for me" instead of telling me what to do?
my Mac's glyphs.app handles it without generating visible errors.

using newest delivery https://github.com/googlei18n/noto-source/blob/master/src/NotoSerif-RomanMM.glyphs as input

< Traceback (most recent call last):
<   File "/usr/local/bin/fontmake", line 9, in <module>
<     load_entry_point('fontmake==1.0', 'console_scripts', 'fontmake')()
<   File "build/bdist.linux-x86_64/egg/fontmake/__main__.py", line 43, in main
<   File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 237, in run_from_glyphs
<   File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 282, in run_from_ufos
<   File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 144, in build_otfs
<   File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/misc/loggingTools.py", line 372, in wrapper
<     return func(*args, **kwds)
<   File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 183, in save_otfs
<   File "build/bdist.linux-x86_64/egg/ufo2ft/__init__.py", line 28, in compileOTF
<   File "build/bdist.linux-x86_64/egg/ufo2ft/makeotfParts.py", line 38, in compile
<   File "build/bdist.linux-x86_64/egg/ufo2ft/makeotfParts.py", line 176, in setupFile_featureTables
<   File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/feaLib/builder.py", line 25, in addOpenTypeFeaturesFromString
<     addOpenTypeFeatures(font, featurefile)
<   File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/feaLib/builder.py", line 16, in addOpenTypeFeatures
<     builder.build()
<   File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/feaLib/builder.py", line 76, in build
<     self.parseTree = Parser(self.file).parse()
<   File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/feaLib/parser.py", line 46, in parse
<     statements.append(self.parse_feature_block_())
<   File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/feaLib/parser.py", line 1026, in parse_feature_block_
<     self.parse_block_(block, vertical, stylisticset, size_feature)
<   File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/feaLib/parser.py", line 1089, in parse_block_
<     statements.append(self.parse_language_())
<   File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/feaLib/parser.py", line 333, in parse_language_
<     language = self.expect_language_tag_()
<   File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/feaLib/parser.py", line 1197, in expect_language_tag_
<     self.cur_token_location_)
< fontTools.feaLib.error.FeatureLibError: instance_ufo/NotoSerif-Thin.ufo/features.fea:200:10: "DFLT" is not a valid language tag; use "dflt" inst
ead

**Comment by khaledhosny** [comment]
The error comes from fontTools.feaLib and this is intentional, script and language tags are case sensitive and it is a bug in the font to do otherwise. It should be fixed in the source.

**Comment by brawer** [comment]
Agree.

**Comment by marekjez86** [comment]
Thank you. Closing the bug.

**Comment by behdad** [comment]
Note that 'dflt' is not a language tag, but a special token meaning "default language system".

**Comment by behdad** [comment]
Ie. the value 'dflt' never ends up in the font.

**Comment by khaledhosny** [comment]
Good point. But I think AFDKO will error here as well. May be glyphsLib should catch uses of `DFLT` as a language tag and fix it before writing to UFO, if this is what Glyphs is generating (as apposed to something that was input by the user).

**Comment by marekjez86** [comment]
I actually doubt that this was generated by glyphs.app. Why? this is the only occurrence of this string in any of the sources that I have seen. Therefore, this string is somewhat unique.

**Comment by brawer** [comment]
Exactly. The source has a bug.
