### ISSUE TITLE
fontmake passes incomplete feature files to fonttools

### ISSUE THREAD

**Issue by brawer** [googlei18n/fontmake#11]
When building [Raleway-Medium.ufo](https://github.com/FlossFoundry/Raleway/tree/master/src/Raleway-Medium.ufo), fontmake crashes with the following error:
```
$ fontmake -u src/Raleway-Medium.ufo
>> Removing overlaps for Raleway Medium
>> Saving OTF for Raleway Medium
Traceback (most recent call last):
  File "/usr/local/bin/fontmake", line 9, in <module>
    load_entry_point('fontmake', 'console_scripts', 'fontmake')()
  File "/home/sascha/src/fontmake/Lib/fontmake/__main__.py", line 47, in main
    project.run_from_ufos(ufo_paths, **args)
  File "/home/sascha/src/fontmake/Lib/fontmake/font_project.py", line 174, in run_from_ufos
    mti_feafiles=mti_paths.get(name), kern_writer=GlyphsKernWriter)
  File "/home/sascha/src/fontmake/Lib/fontmake/font_project.py", line 118, in save_otf
    kernWriter=kern_writer, mtiFeaFiles=mti_feafiles)
  File "/usr/local/lib/python2.7/dist-packages/ufo2ft/__init__.py", line 29, in compileOTF
    featureCompilerClass, mtiFeaFiles, kernWriter, markWriter)
  File "/usr/local/lib/python2.7/dist-packages/ufo2ft/__init__.py", line 18, in _compile
    featureCompiler.compile()
  File "/usr/local/lib/python2.7/dist-packages/ufo2ft/makeotfParts.py", line 38, in compile
    self.setupFile_featureTables()
  File "/usr/local/lib/python2.7/dist-packages/ufo2ft/makeotfParts.py", line 183, in setupFile_featureTables
    addOpenTypeFeatures(fea_path, self.outline)
  File "/usr/local/lib/python2.7/dist-packages/FontTools/fontTools/feaLib/builder.py", line 13, in addOpenTypeFeatures
    builder.build()
  File "/usr/local/lib/python2.7/dist-packages/FontTools/fontTools/feaLib/builder.py", line 50, in build
    self.parseTree = Parser(self.featurefile_path).parse()
  File "/usr/local/lib/python2.7/dist-packages/FontTools/fontTools/feaLib/parser.py", line 40, in parse
    statements.append(self.parse_feature_block_())
  File "/usr/local/lib/python2.7/dist-packages/FontTools/fontTools/feaLib/parser.py", line 820, in parse_feature_block_
    self.parse_block_(block, vertical)
  File "/usr/local/lib/python2.7/dist-packages/FontTools/fontTools/feaLib/parser.py", line 872, in parse_block_
    statements.append(self.parse_substitute_())
  File "/usr/local/lib/python2.7/dist-packages/FontTools/fontTools/feaLib/parser.py", line 543, in parse_substitute_
    self.parse_glyph_pattern_(vertical=False)
  File "/usr/local/lib/python2.7/dist-packages/FontTools/fontTools/feaLib/parser.py", line 246, in parse_glyph_pattern_
    gc = self.parse_glyphclass_(accept_glyphname=True)
  File "/usr/local/lib/python2.7/dist-packages/FontTools/fontTools/feaLib/parser.py", line 181, in parse_glyphclass_
    self.cur_token_location_)
fontTools.feaLib.error.FeatureLibError: /tmp/tmpOwId86:13:9: Unknown glyph class @smcp1
```

However, [the file in /tmp/tmpOwId86](https://github.com/googlei18n/fontmake/files/126080/tmpOwId86.txt) has no definition of glyph class smcp1. fontTools.feaLib is therefore correct when it rejects this input. When passing that same file to AFDKO, it equally rejects it with the same error message.

Now, the command `fontmake -u src/Raleway-Medium.ufo --use-afdko` does _not_ fail in feature file parsing but barfs on https://github.com/googlei18n/fontmake/issues/10. This is extremely surprising, because the content of the tmpOwId86 feature file would also have been rejected by AFDKO. Does AFDKO receive a different input feature file than feaLib? Or does fontmake not check for makeotf errors? (Actually, when running fontmake under strace, I could not find any exec calls to makeotf; perhaps makeotf does not get run at all, despite passing --use-afdko?)

**Comment by brawer** [comment]
In Raleway-Medium.ufo, the glyph class “smcp1” is defined [here](https://github.com/FlossFoundry/Raleway/blob/683b01bb7fa069271544779d8a0b06eb75ded2f3/src/Raleway-Medium.ufo/groups.plist#L1053). Just speculating, is fontmake perhaps ignoring [groups.plist](http://unifiedfontobject.org/versions/ufo3/groups.html) in UFO files?

**Comment by anthrotype** [comment]
ufo2ft only appends or overwrites the kern/mark/mkmk features to the UFO `font.features.text`. It does not write the UFO groups.plist to the features file as FEA classes. I think ufo2fdk does that.

**Comment by anthrotype** [comment]
Actually not even ufo2fdk does that. Both ufo2ft and ufo2fdk don't write the groups.plist into the features, they only do it for the kerning classes which are in the groups.plist. Both seem to assume that classes used in substitutions, like 'smcp1' group in your example, are written in the features file by the user as @scmp1 = [...].

**Comment by adrientetar** [comment]
> Both seem to assume that classes used in substitutions, like 'smcp1' group in your example, are written in the features file by the user as @scmp1 = [...].

That's not surprising to me.

**Comment by brawer** [comment]
Ah, thanks @anthrotype for the explanation! So the [UFO spec](http://unifiedfontobject.org/versions/ufo3/features.html) writes:

> It is important to note that the features file may contain data that is a duplicate of or data that is in conflict with the data in kerning.plist, groups.plist and fontinfo.plist. Synchronization between the files is not a requirement of this specification. Synchronization is up to the user and authoring tool developers.

Does anyone understand how this is supposed to work in practice? If the feature file is in conflict with *.plist, is that now a bug in the authoring tool, or are consumers (such as fontmake) supposed to work around the conflict? Well, given that the UFO spec explicitly says that a valid UFO file “may contain data that is in conflict”, they probably mean the latter. But what exactly is fontmake supposed to do in this situation? Confused. :confused:

I could certainly implement a mode in feaLib to allow re-definition of certain glyph classes, but I’m not sure whether that’s a good idea. Probably it’s better for fontmake to simply reject UFO files when their feature files are broken. Do people agree?

**Comment by anthrotype** [comment]
> I could certainly implement a mode in feaLib to allow re-definition of certain glyph classes

Sorry, I don't understand what you mean by that.

>  Probably it’s better for fontmake to simply reject UFO files when their feature files are broken

By "broken", you mean if a fea class is used in features but it's not actually defined inside the features file, or it is defined both in groups.plist and features but containing different glyphs? In that case, yes. I think that's fine.

**Comment by adrientetar** [comment]
> Do people agree?

Agreed. No tools have gone ahead merging groups.plist and FEA (except for kerning) and doing so would make files more confusing overall, I think. 
I would say it's best to stick with what current tools do: having a FEA file that's valid on its own.

**Comment by adrientetar** [comment]
By the way I think Raleway was developed in another format then converted to UFO so there might be weirdness in these files. Not sure what tool was used to generate them.

**Comment by anthrotype** [comment]
I think the only font editor that splits up groups definitions and their use in features is FontLab 5, where the FEA file is not "valid on its own", but can reference glyph classes defined in the Fontlab "Groups" panel -- which are automatically converted to FEA classes upon compiling the features.

But I guess Adrien is right. Better to ensure the fea file is self-contained and in sync.

**Comment by brawer** [comment]
So the bug is in FontLab 5?

**Comment by anthrotype** [comment]
again, that's not a bug, but a feature.
The bug is rather in the UFO export tool that might have been used to go from vfb to ufo -- if that was the case.

**Comment by adrientetar** [comment]
> So the bug is in FontLab 5?

I don't really know FL5, but there was a script called UFOcentral to make UFOs and then Fontlab published vfb2ufo which is another tool to convert to UFO (you might want to try regenerating from this one since it's more recent and I think it may generate better output).

**Comment by brawer** [comment]
@twardoch, do your current tools emit UFOs whose feature files are internally consistent? To summarize this thread, we’ve encountered an UFO file that was converted from FontLab and whose features.fea refers to glyph classes that are not defined in features.fea but only in groups.plist. We don’t care much about the particular font (it’s easy to fix anyway), but it would be good to make sure that an automatic chain from FontLab to UFO to fontmake works without hiccups.

**Comment by adrientetar** [comment]
Well you could use a font that was natively developed as UFO in the meantime. I think this is one such family: https://github.com/metapolator/Breite

**Comment by brawer** [comment]
Yup, will do. Regarding UFOCentral, it does not really seem to do any feature file assembly itself; it merely passes a flag (whether or not to save features) from a user interface dialog to the FontLab API. See [line 714 of the UFOCentral source code](https://github.com/typesupply/fontlab-scripts/blob/master/UFOCentral.py#L714).

**Comment by twardoch** [comment]
I need to check. FLS5 has an option that will convert the "internal" classes into FEA classes on the fly while compiling so inside the VFB, the classes are stored only in internal format, and not in the FEA prolog. But you may import these classes explicitly into the FEA portion and disable that option. 

When vfb2ufo converts a VFB to UFO, I don't know what it does bit it's possible that it doesn't do this explicit import. 

I need to check. This is something I hadn't thought about at all so far but I should. I agree that features.fea inside UFO should be self-contained. Ideally, the kerning classes should be kept in groups.plist only if the FEA does not contain "feature kern" at all, but if it does, then they should be included. 

Karsten Luecke's [KLTF Make Kern Feature](http://kltf.de/kltf_otproduction.shtml) macro writes its kerning classes **inside** the "feature kern" block rather than into the prolog, which I actually like a lot (I never thought this was possible), so the entire "feature kern" block is self-contained, with class definitions, subtable breaks and the pos statements. This is how it should be done -- put non-kerning classes (used in sub statements) in the prolog but put kerning class definitions inside the "feature kern" block if it is being written into FEA.

**Comment by twardoch** [comment]
BTW: this is an important aspect. Any.font generation should work so that if FEA contains "feature kern", that should be used, and if it does not, ot should be built from groups.plist + kerning.plist.

**Comment by adrientetar** [comment]
> Any.font generation should work so that if FEA contains "feature kern", that should be used, and if it does not, ot should be built from groups.plist + kerning.plist.

Agreed.

**Comment by anthrotype** [comment]
if ufo2fdk, the kerning classes are written inside the "feature kern" block, in ufo2ft are written outside, immediately before the feature definition. But it doesn't matter where they are written (there's no concept of scope in FEA), as long as they *are* written before they are used.

**Comment by twardoch** [comment]
@anthrotype Technically it does not matter indeed. Might still be useful to "standardize" for the sake of the users and possible tool chain streamlining. The "kern" and "mark" feature builders in these modules are useful as they are. 

(There's also the Adobe [kern](https://github.com/adobe-type-tools/fontlab-scripts/tree/master/Kerning) and [mark/mkmk](https://github.com/adobe-type-tools/fontlab-scripts/blob/master/Anchors/MarkFeatureGenerator.py) feature generators that are written for FL but could be adopted for UFO -- or are they superseded by something already, @miguelsousa ?).

**Comment by miguelsousa** [comment]
@twardoch the kern and mark modules at https://github.com/adobe-type-tools/python-modules support several environments.

**Comment by twardoch** [comment]
Thanks!

**Comment by jamesgk** [comment]
I don't think there's any outstanding fontmake bug here. Please re-open if I'm wrong.
