### ISSUE TITLE
Cannot make Breite-Light

### ISSUE THREAD

**Issue by brawer** [googlei18n/fontmake#12]
fontmake crashes when building Breite-Light from UFO:
```
$ git clone https://github.com/metapolator/Breite.git
$ fontmake -u Breite/Breite\ Light/Light.ufo
Traceback (most recent call last):
  File "/usr/local/bin/fontmake", line 9, in <module>
    load_entry_point('fontmake', 'console_scripts', 'fontmake')()
  File "/home/sascha/src/fontmake/Lib/fontmake/__main__.py", line 47, in main
    project.run_from_ufos(ufo_paths, **args)
  File "/home/sascha/src/fontmake/Lib/fontmake/font_project.py", line 158, in run_from_ufos
    print '>> Removing overlaps for ' + ufo.info.postscriptFullName
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

First I thought it’s the whitespace in the file names, but renaming directories did not help. Is the font borked? Or an upstream component?

**Comment by adrientetar** [comment]
The font is fine I guess, it just doesn't have a postscriptFullName defined and so that is None.

**Comment by adrientetar** [comment]
In ufo2ft/ufo2fdk there is getFontAttrWithFallback which mostly requires familyName and styleName in terms of naming. Note that a UFO without these attributes is still a valid UFO, but it's reasonable to require familyName and styleName for font generation (we require attributes which ufo2ft will crash without [there](https://github.com/trufont/trufont/commit/62dbe9335ac58b6b00cfb2935fa0b92669d64e0b)).

**Comment by brawer** [comment]
Thanks for the explanation. If the input lacks a needed attribute, could fontmake print an error message instead of crashing?

**Comment by adrientetar** [comment]
I'd raise an exception anyway since it failed to proceed, so caller can react accordingly. Maybe ValueError, that's what ufo2ft raised when it was using makeotf.

Now, postscriptFullName itself shouldn't be a hard requirement. I would suggest calling getFontAttrWithFallback or falling back to familyName + styleName.

**Comment by jamesgk** [comment]
As of afe78eb5babede6f935289a3f9e07d392c5ab65a it's now just building a postscript-like name, since this was only used for printing. Breite-Light is still crashing for me, but I believe that's an issue with the UFO (missing or mis-referencing a component).

**Comment by brawer** [comment]
Thanks for fixing postscriptFullName. Created a [new bug](https://github.com/googlei18n/fontmake/issues/16) for the discussion how to handle missing components.
