### ISSUE TITLE
-mi short option (masters_as_instances) uses two letters, should only use one

### ISSUE THREAD

**Issue by anthrotype** [googlei18n/fontmake#126]
Short option (preceded by a single `-`) must be a single letter, otherwise things get confusing for the argument parser and the user.

See https://docs.python.org/3/library/argparse.html#option-value-syntax

**Comment by jamesgk** [comment]
Oh right, I guess there is ambiguity if there are also -m and -i options. So, what to use for masters_as_instances?

**Comment by khaledhosny** [comment]
Short options are always cryptic, so `-M` should do as well.
