### ISSUE TITLE
out of memory error with "make -B src/NotoSerif-RomanMM.glyphs"

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#139]
My system has the following memory (output from dmesg | grep Memory ):
[    0.000000] Memory: 12298112K/12582388K available (7402K kernel code, 1146K rwdata, 3416K rodata, 1336K init, 1448K bss, 284276K reserved)

When I make https://github.com/googlei18n/noto-source/blob/master/src/NotoSerif-RomanMM.glyphs

using the command below
make -B -d -k src/NotoSerif-RomanMM.glyphs 

at this point I run out of memory. This is a NEW situation.
 
>> Building OTFs
>> Decomposing glyphs for NotoSerif-Thin
>> Decomposing glyphs for NotoSerif-ExtraLight
>> Decomposing glyphs for NotoSerif-Light
>> Decomposing glyphs for NotoSerif-Regular
>> Decomposing glyphs for NotoSerif-Medium
>> Decomposing glyphs for NotoSerif-SemiBold
>> Decomposing glyphs for NotoSerif-Bold
>> Decomposing glyphs for NotoSerif-ExtraBold
>> Decomposing glyphs for NotoSerif-Black
>> Decomposing glyphs for NotoSerif-SemiCondensedThin
>> Decomposing glyphs for NotoSerif-SemiCondensedExtraLight
>> Decomposing glyphs for NotoSerif-SemiCondensedLight
>> Decomposing glyphs for NotoSerif-SemiCondensed
>> Decomposing glyphs for NotoSerif-SemiCondensedMedium
>> Decomposing glyphs for NotoSerif-SemiCondensedSemiBold
>> Decomposing glyphs for NotoSerif-SemiCondensedBold
>> Decomposing glyphs for NotoSerif-SemiCondensedExtraBold
>> Decomposing glyphs for NotoSerif-SemiCondensedBlack
>> Decomposing glyphs for NotoSerif-CondensedThin
>> Decomposing glyphs for NotoSerif-CondensedExtraLight
>> Decomposing glyphs for NotoSerif-CondensedLight
>> Decomposing glyphs for NotoSerif-Condensed
>> Decomposing glyphs for NotoSerif-CondensedMedium
>> Decomposing glyphs for NotoSerif-CondensedSemiBold
>> Decomposing glyphs for NotoSerif-CondensedBold
>> Decomposing glyphs for NotoSerif-CondensedExtraBold
>> Decomposing glyphs for NotoSerif-CondensedBlack
>> Decomposing glyphs for NotoSerif-ExtraCondensedThin
>> Decomposing glyphs for NotoSerif-ExtraCondensedExtraLight
>> Decomposing glyphs for NotoSerif-ExtraCondensedLight
>> Decomposing glyphs for NotoSerif-ExtraCondensed
>> Decomposing glyphs for NotoSerif-ExtraCondensedMedium
>> Decomposing glyphs for NotoSerif-ExtraCondensedSemiBold
>> Decomposing glyphs for NotoSerif-ExtraCondensedBold
>> Decomposing glyphs for NotoSerif-ExtraCondensedExtraBold
>> Decomposing glyphs for NotoSerif-ExtraCondensedBlack
>> Removing overlaps for NotoSerif-Thin
>> Removing overlaps for NotoSerif-ExtraLight
>> Removing overlaps for NotoSerif-Light
>> Removing overlaps for NotoSerif-Regular
>> Removing overlaps for NotoSerif-Medium
>> Removing overlaps for NotoSerif-SemiBold
>> Removing overlaps for NotoSerif-Bold
>> Removing overlaps for NotoSerif-ExtraBold
>> Removing overlaps for NotoSerif-Black
>> Removing overlaps for NotoSerif-SemiCondensedThin
>> Removing overlaps for NotoSerif-SemiCondensedExtraLight
>> Removing overlaps for NotoSerif-SemiCondensedLight
>> Removing overlaps for NotoSerif-SemiCondensed
>> Removing overlaps for NotoSerif-SemiCondensedMedium
>> Removing overlaps for NotoSerif-SemiCondensedSemiBold
>> Removing overlaps for NotoSerif-SemiCondensedBold
>> Removing overlaps for NotoSerif-SemiCondensedExtraBold
>> Removing overlaps for NotoSerif-SemiCondensedBlack
>> Removing overlaps for NotoSerif-CondensedThin
>> Removing overlaps for NotoSerif-CondensedExtraLight
>> Removing overlaps for NotoSerif-CondensedLight
>> Removing overlaps for NotoSerif-Condensed
>> Removing overlaps for NotoSerif-CondensedMedium
>> Removing overlaps for NotoSerif-CondensedSemiBold
>> Removing overlaps for NotoSerif-CondensedBold
>> Removing overlaps for NotoSerif-CondensedExtraBold
>> Removing overlaps for NotoSerif-CondensedBlack
>> Removing overlaps for NotoSerif-ExtraCondensedThin
>> Removing overlaps for NotoSerif-ExtraCondensedExtraLight
>> Removing overlaps for NotoSerif-ExtraCondensedLight
>> Removing overlaps for NotoSerif-ExtraCondensed
>> Removing overlaps for NotoSerif-ExtraCondensedMedium
>> Removing overlaps for NotoSerif-ExtraCondensedSemiBold
>> Removing overlaps for NotoSerif-ExtraCondensedBold
>> Removing overlaps for NotoSerif-ExtraCondensedExtraBold
>> Removing overlaps for NotoSerif-ExtraCondensedBlack
>> Saving OTF for NotoSerif-Thin
WARNING: underline thickness not set in UFO, defaulting to UPM * 0.05
WARNING: underline position not set in UFO, defaulting to UPM * -0.075
WARNING: underline thickness not set in UFO, defaulting to UPM * 0.05
WARNING: underline position not set in UFO, defaulting to UPM * -0.075
WARNING: underline thickness not set in UFO, defaulting to UPM * 0.05
Traceback (most recent call last):
  File "/usr/local/bin/fontmake", line 9, in <module>
    load_entry_point('fontmake', 'console_scripts', 'fontmake')()
  File "build/bdist.linux-x86_64/egg/fontmake/__main__.py", line 43, in main
  File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 237, in run_from_glyphs
  File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 282, in run_from_ufos
  File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 144, in build_otfs
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 183, in save_otfs
  File "build/bdist.linux-x86_64/egg/ufo2ft/__init__.py", line 31, in compileOTF
  File "build/bdist.linux-x86_64/egg/ufo2ft/otfPostProcessor.py", line 25, in process
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/compreffor/__init__.py", line 115, in compress
    self.run_executable()
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/compreffor/__init__.py", line 135, in run_executable
    cxxCompressor.compreff(self.font, use_lib=False, **self.options)
  File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/compreffor/cxxCompressor.py", line 239, in compreff
    stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1223, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
Reaping losing child 0x021feb70 PID 30659 
make: *** [src/NotoSerif-RomanMM.glyphs] Error 1
Removing child 0x021feb70 PID 30659 from chain.
Failed to remake target file `src/NotoSerif-RomanMM.glyphs'.

**Comment by marekjez86** [comment]
The same/similar to https://github.com/googlei18n/fontmake/issues/140 ?
This one was using Linux the other one was running on my Mac.

**Comment by anthrotype** [comment]
Try updating to the latest compreffor. From the traceback it looks like you are using an old version (i.e. that spawned a new subprocess).

**Comment by marekjez86** [comment]
unable to reproduce. right now I can build src/NotoSerif-RomanMM.glyphs
appears to be fixed
