### ISSUE TITLE
Contours are reversing unexpectedly in interpolatable ttfs

### ISSUE THREAD

**Issue by aaronbell** [googlei18n/fontmake#141]
I am generating interpolatable TTFs from a Glyphs file, but am having trouble with the cap 'A'. 

The 'master_ufo' files generated are all correct, but when the 'master_ttf_interpolatable' file is generated, for whatever reason, the outline direction of the crossbar reverses, causing overlap errors with the rest of the letter.

[Here](https://github.com/googlei18n/fontmake/files/461176/TEST.zip) is a zip file containing the letter A and all the master files created. 

Any idea what might be causing this?

**Comment by aaronbell** [comment]
It appears that this is actually due to a bug in OSX El Capitan. Cheers!

**Comment by behdad** [comment]
Oh, that bug!  Yes.

@aaronbell but you also told me there's another bug, where coincident points are being merged?

**Comment by anthrotype** [comment]
fonttools ttGlyphPen removes the last point if the first and last point are the same.

**Comment by behdad** [comment]
Right.  We need a mode in ttGlyphPen that doesn't do anything "smart".  That should be called for ttf-interpolatable output.

**Comment by behdad** [comment]
Humm.  Actually, the removal messes up point numbers and breaks hinting as well, so it definitely shouldn't be on by default.  Meh.  We have to clean this up.

**Comment by aaronbell** [comment]
Yeah, fixing that would be good too. I'm running into issues where in the condensed styles I need two points to create a straight line, but in the extended styles the design is rounded. So there needs to be a double point in the interpolatable version.

**Comment by anthrotype** [comment]
maybe you can temporarily work around that by moving the starting point. The pruning of duplicate nodes only occur for the first and last point.

**Comment by aaronbell** [comment]
I ended up shifting the duplicated points by 1 or 2 funits to establish a difference. BTW, it appeared not to be just deleting duplicates at the starting point, but anywhere on the curve. Something to take a look at?

**Comment by behdad** [comment]
Can you open a new issue?  Also, will be much easier with a test font.
