### ISSUE TITLE
-o ttf-interpolatable removes necessary double points at start of curve

### ISSUE THREAD

**Issue by aaronbell** [googlei18n/fontmake#142]
In [this font](https://github.com/googlei18n/fontmake/files/462704/Archive.zip), double points in the extended style are necessary to enable the font to interpolate correctly from narrow to wide. There's two issues that I'm seeing in the attached font. 

1) The starting point of the curve is being moved from the current placement—at the bottom of the curve. 
2) the double point present at the new starting point is being removed. It does appear that non-starting double points are preserved though.

**Comment by behdad** [comment]
@jamesgk can you take a look at this?  Thanks.

**Comment by jamesgk** [comment]
Could this be related to https://github.com/googlei18n/cu2qu/pull/30? cc @anthrotype

**Comment by anthrotype** [comment]
I think issue number 2 is related to the fonttools TTGlyphPen removing duplicate points when they occur at the end of the contour (if last point is the same as the first.

Whereas issue number 1 (changing starting point) I'm not sure if it's related to cu2qu.
Was the original starting point of the contour on an on-curve point, or on an off-curve point? Glyphs seem to produce the latter sometimes...

**Comment by jamesgk** [comment]
Yea, original starting point is off-curve and the points are reversed when going UFO -> TTF. My understanding was that cu2qu pens (including reverse contour pen? or not?) always rearrange points to make sure the first is on-curve. I can investigate more.

**Comment by anthrotype** [comment]
cu2qu keeps the starting point if it occurs on an on-curve point. But of course it can't keep it if the starting point is on an off-curve, because it's job is to actually re-write all the PS off-curves to TT off-curves...

**Comment by anthrotype** [comment]
I believe it's glyphsLib that's moving the starting point when creating the UFO from the glyphs file.

I just drew a simple circle, and you can see from the glyph view the starting point (little triangle) appears to be at the bottom, on what it seems an on-curve point, namely (366, 163).

<img width="378" alt="screenshot 2016-09-12 13 33 45" src="https://cloud.githubusercontent.com/assets/6939968/18436075/64a0cd06-78ee-11e6-96ab-75b104c07827.png">

This is how Glyphs stores it internally:

```
{
glyphname = A;
lastChange = "2016-09-12 12:24:22 +0000";
layers = (
{
layerId = "E3185ACB-E009-4EDC-A343-0FEB610C57FE";
paths = (
{
closed = 1;
nodes = (
"472 163 OFFCURVE",
"559 259 OFFCURVE",
"559 378 CURVE SMOOTH",
"559 496 OFFCURVE",
"472 592 OFFCURVE",
"366 592 CURVE SMOOTH",
"259 592 OFFCURVE",
"172 496 OFFCURVE",
"172 378 CURVE SMOOTH",
"172 259 OFFCURVE",
"259 163 OFFCURVE",
"366 163 CURVE SMOOTH"
);
}
);
width = 600;
}
);
unicode = 0041;
}
```

You can see the first point in the contour is actually `OFFCURVE`, but the "real" oncurve point (as it shows in the GUI) is actually the last `CURVE` point.

This is how glyphsLib converts it to a UFO glif:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<glyph name="A" format="2">
  <advance width="600"/>
  <unicode hex="0041"/>
  <outline>
    <contour>
      <point x="472" y="163"/>
      <point x="559" y="259"/>
      <point x="559" y="378" type="curve" smooth="yes"/>
      <point x="559" y="496"/>
      <point x="472" y="592"/>
      <point x="366" y="592" type="curve" smooth="yes"/>
      <point x="259" y="592"/>
      <point x="172" y="496"/>
      <point x="172" y="378" type="curve" smooth="yes"/>
      <point x="172" y="259"/>
      <point x="259" y="163"/>
      <point x="366" y="163" type="curve" smooth="yes"/>
    </contour>
  </outline>
  <lib>
    <dict>
      <key>com.schriftgestaltung.Glyphs.lastChange</key>
      <string>2016/09/12 12:24:22</string>
    </dict>
  </lib>
</glyph>
```

It should be like that instead:

```diff
 <?xml version="1.0" encoding="UTF-8"?>
 <glyph name="A" format="2">
   <advance width="600"/>
   <unicode hex="0041"/>
   <outline>
     <contour>
+      <point x="366" y="163" type="curve" smooth="yes"/>
       <point x="472" y="163"/>
       <point x="559" y="259"/>
       <point x="559" y="378" type="curve" smooth="yes"/>
       <point x="559" y="496"/>
       <point x="472" y="592"/>
       <point x="366" y="592" type="curve" smooth="yes"/>
       <point x="259" y="592"/>
       <point x="172" y="496"/>
       <point x="172" y="378" type="curve" smooth="yes"/>
       <point x="172" y="259"/>
       <point x="259" y="163"/>
-      <point x="366" y="163" type="curve" smooth="yes"/>
     </contour>
   </outline>
   <lib>
     <dict>
       <key>com.schriftgestaltung.Glyphs.lastChange</key>
       <string>2016/09/12 12:24:22</string>
     </dict>
   </lib>
 </glyph> 
```

This way the starting point would not change in the UFO, nor in the generated TTF.

/cc @schriftgestalt

**Comment by jamesgk** [comment]
Here's what I see when running the given font through fontmake:

Glyphs:
```
nodes = (
"716 -3 OFFCURVE",
"848 113 OFFCURVE",
"848 348 CURVE SMOOTH",
"848 348 LINE SMOOTH",
"848 586 OFFCURVE",
...
```

UFO:
```
   <contour>
      <point x="716" y="-3"/>
      <point x="848" y="113"/>
      <point x="848" y="348" type="curve" smooth="yes"/>
      <point x="848" y="348" type="line" smooth="yes"/>
      <point x="848" y="586"/>
```

TTX:
```
   <TTGlyph name="uni004F" xMin="50" yMin="-3" xMax="848" yMax="704">
      <contour>
        <pt x="848" y="348" on="1"/>
        <pt x="848" y="172" on="0"/>
        <pt x="649" y="-3" on="0"/>
        <pt x="449" y="-3" on="1"/>
        <pt x="249" y="-3" on="0"/>
```

And indeed the duplicate 848,348 point has been removed.

**Comment by anthrotype** [comment]
yes this confirms my theory.
When you ask a defcon Glyph to `draw` itself onto the `cu2qu.ufo.GetSegmentsPen`, it will have to convert the list of points into list of segments, using the `PointToSegmentPen`.
The latter inherits from the `BasePointToSegmentPen`, which in its endPath method locates the first on-curve point, and rotates the point list:
https://github.com/unified-font-object/ufoLib/blob/master/Lib/ufoLib/pointPen.py#L107-L115

We need to change glyphsLib to write the UFO so that, when a Glyphs.app contour ends with a CURVE, that becomes the first on-curve point in the GLIF contour.

**Comment by anthrotype** [comment]
about the duplicate point, we need to make that optimization optional in the TTGlyphPen.

**Comment by schriftgestalt** [comment]
Is there a hard reason why a contour has to start with an oncurve point? I find it easier to read if all "segments" are together, with the small inconvenience that the first "move" node has to be collected from the end of the node list. Otherwise you have to draw past the end of the nodes to get to the final point of the last segment. Both have pro/cons.

**Comment by anthrotype** [comment]
The UFO spec does not say it must start with an on-curve; however even if it does not start with an on-curve, all the UFO apps and libraries that use the Pen protocol like robofab, defcon, etc. *will* nevertheless interpret the first segment of the contour as the first on-curve point in the point list. 
So, for example, if one exports a UFO directly from Glyphs.app and tries to open it in Robofont, then the starting point icon will show up on the following on-curve. The two make different assumptions so in glyphsLib we need to translate between one and the other.
