### ISSUE TITLE
Glyphs custom axes added even when unused

### ISSUE THREAD

**Issue by aaronbell** [googlei18n/fontmake#144]
When generating master UFOs with a MetricsMachine .designspace document from a Glyphs file, I note that the "custom" axes is added as a dimension:

`<dimension name="custom" xvalue="100.000000" />`

While this doesn't necessarily cause problems, it would be cleaner to ignore axes if no interpolation is happening on that axis.

[Sample designspace](https://github.com/googlei18n/fontmake/files/463226/TESTdesignspace.zip)

**Comment by behdad** [comment]
Yes, I have had wanted to get rid of those. Will do today.

**Comment by robmck-ms** [comment]
Same is true for the Width axis, even if you're not using it. (e.g. when I build a one axis font, the .designspace file lists 3 axes).

**Comment by brawer** [comment]
Also, when using fontmake to build variation fonts, it currently emits this bogus `xxxx` axis into the `fvar` table. Obviously, a non-existing bogus axis should not be part of the generated output.

```xml
<fvar>
  <!-- Custom -->
  <Axis>
    <AxisTag>xxxx</AxisTag>
    <MinValue>100.0</MinValue>
    <DefaultValue>100.0</DefaultValue>
    <MaxValue>100.0</MaxValue>
  </Axis>

  <!-- Regular -->
  <NamedInstance subfamilyNameID="262">
      <coord axis="wdth" value="100.0"/>
      <coord axis="wght" value="90.0"/>
      <coord axis="xxxx" value="100.0"/>
  </NamedInstance>
</fvar>
```

**Comment by behdad** [comment]
Right.  I'll clean these up soon.

**Comment by behdad** [comment]
Fixed now.
