### ISSUE TITLE
back in my 29/Sep build: Assertion `enc.size() < 128' failed. when processing NotoSansSymbols2-Regular font

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#150]
< cffCompressor: cffCompressor.cc:297: void charstring_pool_t::writeEncoding(const encoding_list&, const std::map<const substring_t*, unsigned int>&, std::os
tream&): Assertion `enc.size() < 128' failed.
4956,4978c4955,4967
< Traceback (most recent call last):
<   File "/usr/local/bin/fontmake", line 9, in <module>
<     load_entry_point('fontmake', 'console_scripts', 'fontmake')()
<   File "build/bdist.linux-x86_64/egg/fontmake/**main**.py", line 43, in main
<   File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 237, in run_from_glyphs
<   File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 282, in run_from_ufos
<   File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 144, in build_otfs
<   File "/usr/local/lib/python2.7/dist-packages/fonttools-3.1.3.dev1+ng7eed002-py2.7.egg/fontTools/misc/loggingTools.py", line 372, in wrapper
<     return func(_args, *_kwds)
<   File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 183, in save_otfs
<   File "build/bdist.linux-x86_64/egg/ufo2ft/**init**.py", line 31, in compileOTF
<   File "build/bdist.linux-x86_64/egg/ufo2ft/otfPostProcessor.py", line 25, in process
<   File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/compreffor/**init**.py", line 115, in compress
<     self.run_executable()
<   File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/compreffor/**init**.py", line 135, in run_executable
<     cxxCompressor.compreff(self.font, use_lib=False, **self.options)
<   File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/compreffor/cxxCompressor.py", line 248, in compreff
<     subrs, glyph_encodings = read_data(td, results)
<   File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/compreffor/cxxCompressor.py", line 148, in read_data
<     enc, num_read = get_encoding(results[pos:], subrs)
<   File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/compreffor/cxxCompressor.py", line 110, in get_encoding
<     num_calls = data_buffer[pos]
## < IndexError: array index out of range

> > > Building TTFs
> > > Removing overlaps for NotoSansSymbols2-Regular
> > > Converting curves for NotoSansSymbols2-Regular

**Comment by anthrotype** [comment]
Hi Marek, you seem to be using an old version of compreffor. I can see from the traceback it is trying to `run_executable`, but the latest compreffor uses a Cython wrapper for the C++ library.
Could you please try to `pip uninstall compreffor` and then do

`pip install --find-links https://github.com/googlei18n/compreffor/releases --user compreffor==0.3.0` 

and then try again to build the font and see if that fixes it.

I will also send a PR to update the fontmake requirement to use the latest compreffor.

**Comment by marekjez86** [comment]
no longer relevant
