### ISSUE TITLE
TypeError: coercing to Unicode: need string or buffer, list found

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#152]
looks that now all *.plist builds terminate with "TypeError: coercing to Unicode: need string or buffer, list found" error

==== building src/NotoSerifMyanmar/NotoSerifMyanmar-MM.plist ====

> > Checking Glyphs source for illegal glyph names
> > Found 1 glyph names containing hyphens: signCwi-kayahli
> > Replacing all hyphens with periods.
> > Building UFOs from Glyphs source
> > 
> > > Parsing .glyphs file
> > > Casting parsed values
> > > Loading to UFOs
> > > Writing master_ufo/NotoSerifMyanmar-Light.ufo
> > > Writing master_ufo/NotoSerifMyanmar-Regular.ufo
> > > Writing master_ufo/NotoSerifMyanmar-Bold.ufo
> > > Writing master_ufo/NotoSerifMyanmar-CondensedLight.ufo
> > > Writing master_ufo/NotoSerifMyanmar-Condensed.ufo
> > > Writing master_ufo/NotoSerifMyanmar-CondensedBold.ufo
> > > Traceback (most recent call last):
> > >   File "/usr/local/bin/fontmake", line 9, in <module>
> > >     load_entry_point('fontmake', 'console_scripts', 'fontmake')()
> > >   File "build/bdist.linux-x86_64/egg/fontmake/**main**.py", line 43, in main
> > >   File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 237, in run_from_glyphs
> > >   File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 269, in run_from_ufos
> > >   File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/defcon/objects/font.py", line 142, in **init**
> > >     reader = UFOReader(self._path)
> > >   File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/ufoLib/__init__.py", line 122, in **init**
> > >     if not os.path.exists(path):
> > >   File "/usr/lib/python2.7/genericpath.py", line 18, in exists
> > >     os.stat(path)
> > > TypeError: coercing to Unicode: need string or buffer, list found

**Comment by behdad** [comment]
Still relevant?

**Comment by marekjez86** [comment]
not relevant.
