### ISSUE TITLE
use requires.io for keeing requirements.txt up-to-date

### ISSUE THREAD

**Issue by anthrotype** [googlei18n/fontmake#164]
https://requires.io/ is a great tool to keep dependencies up to date, while ensuring they have explictly pinned-down versions.
Once it's authorized (by someone with push access to the repo), it works like a bot that watches PyPI for new releases, and sends new pull requests to projects having some requirements.txt files, to update them files with the new requirement. The CI will then run the tests against the new version of that dependency, and the maintainers can merge the PR or fix any issues that may arise.

**Comment by jamesgk** [comment]
Honestly, I think I'd prefer to just update dependencies as-needed rather than add this additional complexity.

**Comment by brawer** [comment]
We now have pyup.io (thanks to @anthrotype).
