### ISSUE TITLE
connection of stroke ends in Noto Sans Arabic variable font has little dents

### ISSUE THREAD

**Issue by xiangyexiao** [googlei18n/fontmake#166]
<img width="1173" alt="arabic gx" src="https://cloud.githubusercontent.com/assets/12721521/19541355/745fc730-961a-11e6-9dce-7e24473009e2.png">

Check the image. Connection between strokes in ليا and كا has little dent in heavier weights. 

This issue doesn't exist in the interpolated normal otf fonts.

xiangye

**Comment by xiangyexiao** [comment]
@behdad any issue in fonttools?

**Comment by behdad** [comment]
See my email to you. Should not happen with latest fonttools, which has HVAR generation disabled.

**Comment by jamesgk** [comment]
Yep, seems to be fixed. See attached: 
[NotoSansArabic-GX.ttf.zip](https://github.com/googlei18n/fontmake/files/540503/NotoSansArabic-GX.ttf.zip)

**Comment by xiangyexiao** [comment]
problem solved.
