### ISSUE TITLE
Is there a way to suppress INFO messages in fontmake from all sources?

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#169]
Is there a way to suppress INFO messages in fontmake?
Stats:
- my log after processing one small font and while working on NotoSansArabic has about 994 lines 
- out of these 994 lines 535 are INFO lines from the following three sources:
  INFO:fontmake
  INFO:fontTools.subset
  INFO:mutatorMath
  Some of these INFO lines are very ver long 994 lines occupy ~740kB so average line is about 741 bytes.

Is there a way to suppress INFO messages in fontmake?

marekj@yol-worjdp:~/rel/noto-source$ grep "==== building" makeout-201610241600.txt
==== building src/KKB-Roman-201608021750.glyphs ====
==== building src/NotoSansArabic-MM.glyphs ====
marekj@yol-worjdp:~/rel/noto-source$ grep INFO makeout-201610241600.txt | wc -l
535
marekj@yol-worjdp:~/rel/noto-source$ ls -ltr makeout-201610241600.txt 
-rw-r----- 1 marekj eng 745472 Oct 24 17:00 makeout-201610241600.txt
marekj@yol-worjdp:~/rel/noto-source$ wc makeout-201610241600.txt
   994  81430 745472 makeout-201610241600.txt
marekj@yol-worjdp:~/rel/noto-source$

**Comment by anthrotype** [comment]
Try with:
```
$ fontmake --verbose WARNING ...
```

**Comment by jamesgk** [comment]
I'd like to suppress messages from fontTools.subset in any case, but I couldn't figure out how to do that with the logging module.

**Comment by anthrotype** [comment]
you can either set the `disabled` attribute to `True` to completely mute a specific logger instance, or you can use logging filters for more fine-grained control.

**Comment by anthrotype** [comment]
for an example, you can have a look at fonttools `ChannelsFilter` class in `fontTools.misc.loggingTools`:
https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/misc/loggingTools.py#L389

**Comment by anthrotype** [comment]
another way, instead of muting the subsetter logger, could be to set a custom logging level for it, e.g. one which is greater than logging.INFO, so that any record with a lower level from the subsetter will be muted.

```python
subset_log = logging.getLogger('fontTools.subset')
subset_log.setLevel(logging.WARNING)
```

**Comment by brawer** [comment]
Seems done, closing bug.
