### ISSUE TITLE
Dot of ¿ in Selawik-Regular is shifted

### ISSUE THREAD

**Issue by brawer** [googlei18n/fontmake#17]
When building Microsoft’s Selawik font from the glyphs source, fontmake moves the dot of the ¿ character.  To reproduce:
```
$ wget https://raw.githubusercontent.com/Microsoft/Selawik/master/Source%20files/Glyphs/selawik.glyphs
$ fontmake -g selawik.glyphs
$ hb-view master_otf/Selawik-Regular.otf "¿Huh?"
```

![selawik_bug](https://cloud.githubusercontent.com/assets/1527880/13082683/fee7beea-d4d1-11e5-8720-62e1ac22200e.png)

Or open the font in Glyphs.app:
<img width="284" alt="questiondown" src="https://cloud.githubusercontent.com/assets/1527880/13082758/4e19a6fe-d4d2-11e5-9a39-ca36c5b05823.png">

The original glyphs source places the dot at the expected location. So this looks like a problem in the fontmake pipeline, probably related to composite glyphs.

**Comment by davelab6** [comment]
Yes; it might be because the period glyph is used as the component, and is
placed to the right of origin, and it looks to me like fontmake is applying
that offset.

**Comment by behdad** [comment]
Note that the original bug was because you were not scaling the new offset when accumulating.  It could be fixed without resorting to keeping separate transforms.  See if you can use fonttools.misc.transform for this.
