### ISSUE TITLE
puzzled by error while building NotoSansDisplay-SemiCondensedThinItalic 

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#172]
Is this because of a wrong path direction? How serious is a wrong path direction?

ERROR:fontmake:Failed to remove overlaps for NotoSansDisplay-SemiCondensedThinItalic: 'uni200C'

![uni200c](https://cloud.githubusercontent.com/assets/13322623/19709240/e64d7bda-9ad9-11e6-98af-040a5534d49b.jpg)

**Comment by anthrotype** [comment]
some masters have different starting points for uni200C in NotoSansDisplayItalic-MM.glyphs, which produces this result in the interpolated UFO:

<img width="394" alt="screenshot 2016-10-26 12 34 35" src="https://cloud.githubusercontent.com/assets/6939968/19724542/c36a92b6-9b78-11e6-91a9-a5ef9010fb4b.png">

**Comment by marekjez86** [comment]
@anthrotype : thank you.
Assigning to @behdad to investigate fixing it

**Comment by marekjez86** [comment]
I think I fixed it in the source. I do not think it's relevant any longer (unless you want to deal with it in the code).

**Comment by marekjez86** [comment]
I created source bug. Closing this one.
