### ISSUE TITLE
production name setting in the Glyphs file should take precedent over the fontmake option

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#174]
production name setting in the Glyphs file should take precedent over the fontmake option and we should use --no-production-names or --production-names when this info is not in the Glyphs file. IMHO, we should give warning if what in the Glyphs file is different from the fontmake option

**Comment by anthrotype** [comment]
well, usually command line options override settings from configuration files.
The current behaviour when no `--production-names` option is passed, is to use production names if the UFO lib.plist contains a `com.schriftgestaltung.Don't use Production Names` key.
What's wrong with that?

**Comment by marekjez86** [comment]
@anthrotype : maybe I need more education on this. A font designer complained  "my source files contain friendly names, and the pipeline replaces these by Unicode number names, despite the Glyphs file has a setting to not replace the names." [I used --production-names when building the fonts]. In his mind, he as designer wanted for his fonts to always have "friendly names". Why does it matter - production vs non-production? when would one want to use production vs non-production? Is there a place I could be educated?

**Comment by anthrotype** [comment]
The term "production names" comes from Glyphs.app terminology. If a designer wants to keep so-called "friendly" or "nice" names in Glyphs.app, they have to set a custom parameter "Don't Use Production Names" in the Font Info.
This way, both Glyphs.app and fontmake will not rename the glyphs, i.e keep the friendly names.

Unless one tells fontmake to explicitly use `--production-names`, in which case one must conclude that for that particular run of fontmake the user wishes to rename the glyph names, whether or not the custom parameter is set in the .glyphs file.

**Comment by moyogo** [comment]
@marekjez86 it is recommended to use "production names" which meet the requirements defined in https://github.com/adobe-type-tools/agl-specification and https://github.com/adobe-type-tools/agl-aglfn. The "production names" in the final font must only use characters allowed by the Postscript specifications. These are also called PostScript names.

The term "Production names" can be confusing but it’s Glyphs.app terminology. See https://www.glyphsapp.com/content/1-get-started/2-manuals/1-handbook-glyphs-2-0/Glyphs-Handbook-2.3.pdf section 6.6.1 Glyph Info Database
> Glyphs contains a glyph info database. For each glyph, the
> database defines:
> • the human-readable (or ‘nice’) glyph name,
> • the production names, i.e., the name as required for the
> exported installable font file
> [...]

Once one know that, fontmake’s help already makes it clear that `--production-names` renames the glyphs and sort of implies `--no-production-names` doesn’t.
```
  --production-names    Rename glyphs with production names if available
                        otherwise use uninames.
  --no-production-names
```

It might be good to be explicit about what `--no-production` does and clarify that there is a third option and what it does. Would that be enough?
If that also helps one could find better names for these options.

**Comment by behdad** [comment]
Is the default following the option in Glyphs app?  That is all we care about, right?

I actually don't think "production names" are more useful in the font.  The whole myth around PDF and stuff is, well, a myth.  Text extraction doesn't work reliably for complex scripts if just relying on glyph names anyway.

**Comment by anthrotype** [comment]
> Is the default following the option in Glyphs app?

Yes. When no `--production-names` option is explicitly specified, fontmake checks that  `com.schriftgestaltung.Don't use Production Names` is present (and true) in the UFO lib.plist.

**Comment by jamesgk** [comment]
Just want to note that I think the original context for this issue is https://github.com/googlei18n/noto-source/commit/0345032c37ce8ff1d76d0b2955fecb86b980b88a
