### ISSUE TITLE
Panose numbers and ascender/descender values defined for the instances are ignored

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#18]
I copied from an email by Jelle.B who looked at regular Ethiopic font (see the otf file in the attached zip) generated by the pipeline from the glyphs file (see the attached zip) on about 1/Feb/2016. The comments pertain to that version of the pipeline. See the bottom of this message for the reason why I cannot generate a new version of the fonts.

[...] ignored are Panose numbers and ascender/descender values defined for
the instances.

[NotoSansEthiopicCondensed-Regular-km-error.zip](https://github.com/googlei18n/fontmake/files/133281/NotoSansEthiopicCondensed-Regular-km-error.zip)

Note that NotoSansEthiopic-MM.glyphs generates as of 12/Feb/2016 "defcon.errors.DefconError: The kerning data is not valid" so I cannot check what the newest version of pipeline generates (see https://github.com/googlei18n/fontmake/issues/13 )

**Comment by adrientetar** [comment]
googlei18n/glyphs2ufo#14 will fix this.

**Comment by jamesgk** [comment]
Yep, these should be fixed.
