### ISSUE TITLE
Order of instances in generated designspace doc

### ISSUE THREAD

**Issue by aaronbell** [googlei18n/fontmake#188]
I am finding that some applications, when loading a variation font, are loading the first named instance in the font, which may or may not be the best instance to represent the font. 

This is based on the designspace document that is generated from the original Glyphs Source. However, as far as I can tell, there's no relationship between the instance order in Glyphs and the instance order in the designspace document. 

Would it be possible to set the order of the instances in the designspace document based on the Glyphs instance order?

**Comment by brawer** [comment]
@aaronbell, can you attach a *.glyphs file where the instance order is not preserved in the generated *.designspace file? I’ve tried running a few fonts through glyphsLib but couldn’t reproduce the problem. Also the test case in https://github.com/googlei18n/glyphsLib/pull/128 passes without any code changes.

**Comment by brawer** [comment]
There’s now a test case in https://github.com/googlei18n/glyphsLib/commit/f3612de48aadb2691f51b3271776aaa704063182 but I still can’t reproduce the bug (and the test passes). Please re-open this bug if I’m missing something.
