### ISSUE TITLE
GSUB and GPOS are different from generated by other tool. GPOS decompile fails.

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#19]
I copied the text below from an email by Jelle.B who looked at regular Ethiopic font (see the otf file in the attached zip) generated by the pipeline from the glyphs file (see the attached zip) on about 1/Feb/2016. The comments pertain to that version of the pipeline. See the bottom of this message for the reason why I cannot generate a new version of the fonts.

'Looking at the regular Ethiopic, I can confirm that the Glyphs version [...] matches the font I found that has been used for Monotype’s QA. The only difference seems to be that we tested without hints.

The “pipeline” font is different. [...]

[...] There are size differences of GSUB and GPOS too. The GSUB seems to be OK. The GPOS of the pipeline is significant larger and the tools that I have to decompile GPOS tables both fail to do so.'

[NotoSansEthiopicCondensed-Regular-km-error.zip](https://github.com/googlei18n/fontmake/files/133281/NotoSansEthiopicCondensed-Regular-km-error.zip)

Note that NotoSansEthiopic-MM.glyphs generates as of 12/Feb/2016 "defcon.errors.DefconError: The kerning data is not valid" so I cannot check what the newest version of pipeline generates (see https://github.com/googlei18n/fontmake/issues/13 )

**Comment by jamesgk** [comment]
I'm not seeing this at all, in fact I'm seeing that fontmake GPOS output is significantly smaller than Glyphs output. Maybe this refers to pre-feaLib fontmake output? Closing for now, can re-open if this comes up again.
