### ISSUE TITLE
Support building UFOs

### ISSUE THREAD

**Issue by davelab6** [googlei18n/fontmake#2]
README says, 

> This library provides a wrapper for several other Python libraries which together compile fonts from various sources (.glyphs, .ufo) into binaries (.otf, .ttf).

but it seems to only accept .glyphs files atm,

https://github.com/googlei18n/fontmake/blob/master/Lib/fontmake/__main__.py#L22

In reading https://github.com/googlei18n/fontmake/blob/master/Lib/fontmake/font_project.py then I suppose there needs to be a default assumption that an input UFO is a master or an instance, and an arg to declare this I propose that assuming UFOs are masters makes more sense.

**Comment by justvanrossum** [comment]
I also just fell for that description... fontmake directly taking UFO input would be great.
