### ISSUE TITLE
CFF table is too large because pipeline ignores much of the data in the Glyphs file

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#20]
I copied the text below from an email by Jelle.B who looked at regular Ethiopic font (see the otf file in the attached zip) generated by the pipeline from the glyphs file (see the attached zip) on about 1/Feb/2016. The comments pertain to that version of the pipeline. See the bottom of this message for the reason why I cannot generate a new version of the fonts.

'Looking at the regular Ethiopic, I can confirm that the Glyphs version [...] matches the font I found that has been used for Monotype’s QA. The only difference seems to be that we tested without hints.

The “pipeline” font is different. [...]

The most profound difference is the CFF table, which for the pipeline font
is more than twice as large. It contains more glyphs, 714 versus 561, but
that cannot explain the size difference alone. The explanation for the
different glyph count is that the Pipeline ignores much of the data in the
Glyphs file. It contains Ascii characters and component glyphs that have
been set not to export. The Pipeline exports them anyway: in alphabetical
order of glyph name with NULL between N and O. Glyphs exports the intended
glyph set, using production names in uniXXXX format, in what appears to be
based on Unicode order.'

[NotoSansEthiopicCondensed-Regular-km-error.zip](https://github.com/googlei18n/fontmake/files/133281/NotoSansEthiopicCondensed-Regular-km-error.zip)

Note that NotoSansEthiopic-MM.glyphs generates as of 12/Feb/2016 "defcon.errors.DefconError: The kerning data is not valid" so I cannot check what the newest version of pipeline generates (see https://github.com/googlei18n/fontmake/issues/13 )

**Comment by behdad** [comment]
We also are not subroutinizing, and not specializing operators.  Plus, seems like we are exporting glyphs that are marked as non-export.

**Comment by behdad** [comment]
James, can you please fix the non-export part in glyphs2ufo or ufo2ft, whichever needs the fix?

**Comment by adrientetar** [comment]
UFO has no built-in way of specifying non-exporting glyphs, so I would:

1. in glyphs2ufo, put a boolean value in the glyph lib under com.glyphsapp.export if the export attribute is present in the .glyphs file glyph
2. in ufo2ft, add an optional argument with a list of glyph names that should be compiled.
3. in fontmake, when dealing with a .glyphs as input exclude non-exporting glyphs (those having com.glyphsapp.export) from that list of glyphs

**Comment by moyogo** [comment]
Isn’t that what GOADB is for? Any glyph not listed can be excluded.

**Comment by davelab6** [comment]
On 19 February 2016 at 06:12, Denis Moyogo Jacquerye <
notifications@github.com> wrote:

> Isn’t that what GOADB is for? Any glyph not listed can be excluded.
>
It is in FDK, but my expectation is that fontmake is a 'batteries included'
('self contained')  .glyphs file compiler.

I don't think it would be good to require fontmake users to develop and
maintain a GOADB file to have 'fontmake font.glyphs' work "out of the box".

**Comment by moyogo** [comment]
> I don't think it would be good to require fontmake users to develop and
maintain a GOADB file to have 'fontmake font.glyphs' work "out of the box".

They shouldn’t. Glyphs2ufo should generate the GOADB file from the data in the .glyphs file. It could even [put it in lib.plist](http://doc.robofont.com/forums/topic/export-glyphnames-glyph-libcom-username-exportname/#post-6137). Some people already use GOADB as part of their UFO workflow with makeotf, it would be good for fontmake or ufo2ft/ufo2fdk to be able to use it. GOADB can be used for renaming glyphs (design to production name), for setting unicode value, for glyph order or for glyph exclusion.

**Comment by anthrotype** [comment]
:+1:

**Comment by adrientetar** [comment]
There's already public.glyphOrder for glyphOrder.

**Comment by anthrotype** [comment]
Yeah, so let's use public.glyphOrder for both subsetting (ie. pruning those glyphs in the UFO which are not in its public.glyphOrder) and for reordering (applying whatever order is specified in public.glyphOrder, if present).

There's still one nice thing about the GOADB which is the mapping between design-friendly and AGLFN-uniNames. Of course the latter can be generated automatically (e.g. if a glyph name is in AGLFN use that, else use the uniXXXX given the unicode codepoint, else if "_" is in the name, etc...), but it would also be nice if a user could provide a custom mapping for this purpose.

**Comment by adrientetar** [comment]
We can't do this because the spec makes no guarantees about public.glyphOrder, it's just an ordering you should use when set. In TruFont we use public.glyphOrder as a superset of all glyphs present in the font. So we put all glyphs in the font in there, and those which don't have outlines defined are treated as template glyphs (i.e. ones that you will fill up at some point since they're part of your glyphOrder), that's how we store these. And if public.glyphOrder is a subset of all the glyphs when opening the font, it gets filled up to make sure it represents all glyphs (it's used for various things e.g. looping of glyphs). So while what you suggest can be done, the subsetting will be overwritten or treated differently if you open up in an editor and save.

**Comment by jamesgk** [comment]
In general I like to match Glyphs itself when converting .glyphs -> .ufo. Glyphs puts an export flag in the glyph lib under com.schriftgestaltung.Glyphs.Export, which I'd like to do in glyphs2ufo.

As for what's done in fontmake/ufo2ft, I don't have strong feelings. But it makes sense to me that ufo2ft could take in a list of glyphs to include and fontmake could generate this based on glyphs' libs. What is GOADB?

**Comment by adrientetar** [comment]
> What is GOADB?

GlyphOrderAndAliasDB, a file that maps development names to final names and unicode for use with Adobe FDK.

**Comment by jamesgk** [comment]
I see. Well I propose that fontmake generates this file based on useProductionNames/export flags, when exporting instance OTFs. Then ufo2ft can take the file as an optional parameter.

**Comment by behdad** [comment]
> I see. Well I propose that fontmake generates this file based on useProductionNames/export flags, when exporting instance OTFs. Then ufo2ft can take the file as an optional parameter.

Sounds good.  Re production names, to work around having to rename glyphs in the .fea sources, we can compile the font without production names, then do a rename operation on it.  If we really wanted to, we can also use subsetter or a dumber version of it to subset to the requested glyph set as well.  That approach might minimize changes needed to ufo2ft.

**Comment by jamesgk** [comment]
It sounds like we don't need to change ufo2ft at all? If fontmake is creating the GOADB, it can just use fontTools to rename and subset, right?

**Comment by jamesgk** [comment]
It looks like fontTools.subset can drop development names pretty easily, but only for TTFs until https://github.com/behdad/fonttools/issues/147 is resolved.

**Comment by adrientetar** [comment]
> It looks like fontTools.subset can drop development names pretty easily, but only for TTFs until behdad/fonttools#147 is resolved.

That isn't development names but glyph names &ndash; they can be dropped from compiled fonts since you generally just care about cmap mapping there but there are some legacy concerns, for Adobe apps mostly (something with copy/pasting text from PDFs, I think? they maintained a glyph list with PUA mappings in the days when OTL wasn't implemented properly).

In the context of GOADB, we're talking of development glyph names e.g. using horizontalbar instead of AGLFN-compliant uni2015 (that's just to carry more meaning for the designer, like Glyphs' glyph names). The replacement is then done at compile-time, with GOADB file in the case of the Adobe FDK.

**Comment by jamesgk** [comment]
That makes sense. My questions then are whether it's important to rename the glyphs to have the "uniXXXX" names rather than just dropping the names, and whether it's desirable for ufo2ft to have a GOADB file argument (if so, the file contents? or the file name?).

The easiest thing to do is just call subset without creating such a file or worrying about production glyph names, but it doesn't seem too difficult either way.

**Comment by adrientetar** [comment]
> whether it's important to rename the glyphs to have the "uniXXXX" names rather than just dropping the names

I'm not sure about that tbh, surely @twardoch knows?

> we can also use subsetter or a dumber version of it to subset to the requested glyph set

Wouldn't just making the specified glyphs be faster? When ran over many fonts with large source UFO that might make a difference. Also one of the things I had in mind is a toolchain that compiles just one glyph to display a bitmap of it. FWIW.

**Comment by jamesgk** [comment]
> Wouldn't just making the specified glyphs be faster? When ran over many fonts with large source UFO that might make a difference.

I didn't notice a significant difference in compile time adding a subset step. Right now the slowest parts of the toolchain are interpolation and to a lesser extent glyph decomposition. I suppose glyph decomp could operate on only the subset but I'm not sure that would be a big win (in most cases the subset is almost as big as the full set and in a 1-font, 1-glyph case I'd think it would be fast enough either way).

> Also one of the things I had in mind is a toolchain that compiles just one glyph to display a bitmap of it. FWIW.

Can you do this with ufo2ft's existing glyphOrder parameter? Anyways, if added I was thinking a GOADB parameter would replace glyphOrder.

**Comment by twardoch** [comment]
Perhaps "we" (you, Georg, FontLab) could standardize a section of the UFO lib that indicates which tools were used to generate the UFO? It would be eg. useful to record whether the UFO was generated from a .glyphs file using glyphs2ufo, or Glyphs, or FontLab VI, as the results may differ. Some kind of "lastTool" key. We could propose it to go to public.*. 

Something akin to the browser id string that gets sent in a http request. 

As for .glyphs -> .ufo or .otf glyphname handling and order, I think Georg is the best person to ask. I know that his code "does things" depending on settings, but I don't know much details.

**Comment by adrientetar** [comment]
> could standardize a section of the UFO lib that indicates which tools were used to generate the UFO?

That's creator key in metainfo.plist.

Do you have any idea whether we need to respect AGL and keep glyph names in compiled fonts? Is there any consequence if we drop glyph names?

**Comment by twardoch** [comment]
Glyph names are needed in OTF, in TTF they're optional. They're needed by feaLib or mtiLib before the features are compiled. They're also useful if you postprocess the fonts with some other tools, of if you keep some pre-made .ttx table definitions where glyphs are keyed by names, or if you use tools like VOLT or VTT. Setting the post table format to 3 is useful at the last step, as an option, but I'd recommend that you try to build the lib so that it can generate PDF-compatible glyphnames. 

For Noto fonts, I'd recommend shipping them with glyphnames, since they are useful to everyone except end-users.

**Comment by davelab6** [comment]
I think its good for web fonts APIs to serve files with post table format
version 3, but TTFs that may typically be installed by users ought to have
version 2 with the names.

**Comment by twardoch** [comment]
Yes. It's Microsoft who doesn't care about glyph names in TTFs on Windows. But other workflows do. For example some TeX workflows. Since Noto are useful for a broad audience, I think it's best to leave glyph names in for "desktop fonts" and only remove them in web fonts.

**Comment by jamesgk** [comment]
We're now outputting production names and optimizing CFF outlines.

**Comment by behdad** [comment]
Does anyone have numbers for Glyph-produced as well as pipeline produced CFF file sizes?  Maybe with / without compreffor?

**Comment by jamesgk** [comment]
We seem to be doing pretty well according to this quick test:

```
glyphs:
137K  NotoSansArabic-Black.otf
137K  NotoSansArabic-Bold.otf
136K  NotoSansArabic-Condensed.otf
137K  NotoSansArabic-CondensedBlack.otf
142K  NotoSansArabic-CondensedBold.otf
135K  NotoSansArabic-CondensedThin.otf
133K  NotoSansArabic-Regular.otf
140K  NotoSansArabic-Thin.otf

pipeline_comp:
126K  NotoSansArabic-Black.otf
124K  NotoSansArabic-Bold.otf
124K  NotoSansArabic-Condensed.otf
124K  NotoSansArabic-CondensedBlack.otf
128K  NotoSansArabic-CondensedBold.otf
121K  NotoSansArabic-CondensedThin.otf
123K  NotoSansArabic-Regular.otf
122K  NotoSansArabic-Thin.otf

pipeline_nocomp:
386K  NotoSansArabic-Black.otf
387K  NotoSansArabic-Bold.otf
381K  NotoSansArabic-Condensed.otf
382K  NotoSansArabic-CondensedBlack.otf
391K  NotoSansArabic-CondensedBold.otf
381K  NotoSansArabic-CondensedThin.otf
382K  NotoSansArabic-Regular.otf
389K  NotoSansArabic-Thin.otf
```

**Comment by behdad** [comment]
Humm.  386k -> 126k looks awfully suspicious.  With CJk fonts people typically see more like 15% compression, up to maybe 50% for Hangul.  But this is Arabic which is hugely redundant, so I imagine it's correct.  And we produce 10% better than AFDKO!  Good to know!

**Comment by behdad** [comment]
We should also implement CFF operator specialization and see whether that improves, or worsens, the compreffed size.

**Comment by anthrotype** [comment]
Do these stats refer to overall file size or to the CFF table size only? There might be other things which influence the total size (just checking the obvious here)

**Comment by behdad** [comment]
I *think* it's CFF table only.  Sure, but it's possible, but hard to imagine using compreffor affecting the rest of the font.
