### ISSUE TITLE
solve intersecting outline paths in font instances

### ISSUE THREAD

**Issue by xiangyexiao** [googlei18n/fontmake#210]
notolints report a lot of intersecting outline paths in ttf files generated from sources in https://github.com/googlei18n/noto-source/tree/master/src. 

For example, 

Automatic testing for 'NotoSansArabic-Black.ttf', Version 1.902:
E <paths/intersection> The glyph 'dotlessbeh.ar' has intersecting outlines: intersection ((478.0, -21.0), (504.0, 147.0)) and ((478.0, -21.0), (310.0, -21.0), (219.0, 13.5))

![unnamed](https://cloud.githubusercontent.com/assets/12721521/20997690/dcab241a-bcbc-11e6-9911-094f5b03c517.jpg)

It'll be great if fontmake can solve the intersecting outline paths.

@jamesgk @dougfelt @marekjez86

**Comment by jamesgk** [comment]
Should be fixed by https://github.com/googlei18n/fontmake/pull/208.
