### ISSUE TITLE
Don’t emit bogus “custom” axis

### ISSUE THREAD

**Issue by brawer** [googlei18n/fontmake#211]
For Noto, fontmake produces variable fonts that contain three axes (width, weight, custom). However, this “custom” axis is bogus and contains no useful data, so it should not be emitted in the output.

**Comment by brawer** [comment]
Also, in NotoSansSymbols the “width” axis is not variable either, so it should be suppressed too.

**Comment by anthrotype** [comment]
fixed upstream https://github.com/fonttools/fonttools/pull/736

need to update requirements.txt

**Comment by brawer** [comment]
What about the comment in https://github.com/fonttools/fonttools/pull/736? “It probably needs to be fixed upstream in fontmake”

**Comment by anthrotype** [comment]
I guess @robmck-ms meant that glyphsLib should not add those bogus axes to the generated designspace file?
https://github.com/googlei18n/glyphsLib/blob/master/Lib/glyphsLib/interpolation.py#L105

**Comment by robmck-ms** [comment]
Yes, that's exactly it. glyphsLib shouldn't add unused axes (min==max) in the designspace file.

**Comment by anthrotype** [comment]
glyphsLib has been updated so it doesn't write unused axes to the generated designspace file https://github.com/googlei18n/glyphsLib/issues/84

fontmake requirements should be updated accordingly.

**Comment by behdad** [comment]
So, should the fonttools change be reverted to add whatever axes where passed to it?

**Comment by brawer** [comment]
Looking at https://github.com/fonttools/fonttools/commit/86207144aeba48248653c947fece0e892dae810e the fonttools change seems reasonable, so I’d vote for keeping it. If anyone disagrees, please re-open this bug.
