### ISSUE TITLE
development group/mailing list to receive github/ci notifications

### ISSUE THREAD

**Issue by anthrotype** [googlei18n/fontmake#214]
I would like to set up a google-groups mailing list like the one we have for [fonttools-dev](https://groups.google.com/forum/#!forum/fonttools-dev), in which developers receive notifications for the continuous integration services as well as Github notifications for pushes to fontmake's repository and its dependencies: ufo2ft, cu2qu, glyphsLib, compreffor, as well as ufoLib, defcon, mutatorMath, fontMath, booleanOperations.

This is not meant to be for user/developer discussions, but only as a centralised channel for all the Github/Travis/Appveyor spam.
 
https://help.github.com/articles/managing-notifications-for-pushes-to-a-repository/
 
We could re-use the fonttools-dev list, or create a new ad-hoc one, maybe fontmake-dev.

WDYGT?

**Comment by anthrotype** [comment]
I went on and created a public google-groups mailing list called "fontmake-dev":

https://groups.google.com/forum/#!forum/fontmake-dev

Like the fonttools-dev, this is a public so that Github and the CI can post to it freely.

I'd like to configure fontmake, glyphsLib, ufo2ft, cu2qu, compreffor, etc. repos to send notifications on pushes, and the respective CI to send build status report.

If you believe it's better to re-use the same fonttools-dev list for this purpose, I can scrap this.

**Comment by moyogo** [comment]
Thanks Cosimo!

**Comment by anthrotype** [comment]
Someone with admin access to the fontmake repo should set up the email hook.
I could only configure compreffor so far.

**Comment by anthrotype** [comment]
I just pushed a commit to master and was expecting an email notification from Github but didn't get any. I think fontmake is still not configured properly to send email notifications on pushes to the `fontmake-dev@googlegroups.com` list.

@brawer can you please have a look? I'm not admin of this repo.

**Comment by brawer** [comment]
@anthrotype, you’re an admin now.

**Comment by anthrotype** [comment]
thanks!
Email notifications to fontmake-dev should now be configured.
