### ISSUE TITLE
usWeightClass in 'OS/2' table for *Thin* and *ExtraLight* fonts are incorrect

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#224]
For NotoSansArabic, NotoSansArabicUI, .... and any fonts that pipeline makes

noto_lint.py for \*Thin\* font reports the following error
_E <head/os2/weight_class> Value of usWeightClass in 'OS/2' table is 250, but should be 100._

noto_lint.py for \*ExtraLight\* font reports the following error
_E <head/os2/weight_class> Value of usWeightClass in 'OS/2' table is 300, but should be 200._

Looks that pipeline ignores what is in the source...

Example of the source setting for an \*ExtraLight\* font:
![notoserifsinhala-mm-glyphs-extralight](https://cloud.githubusercontent.com/assets/13322623/21456153/c05b0b20-c8da-11e6-8b64-a8af0c7b2e89.jpeg)

Example of what pipeline made:
![notosanssinhala-semicondensedextralight-usweightclass](https://cloud.githubusercontent.com/assets/13322623/21456158/c903242e-c8da-11e6-9b9d-58eeece76088.jpeg)

**Comment by moyogo** [comment]
This is from glyphsLib’s [builder.py](https://github.com/googlei18n/glyphsLib/blob/3cd3c5d1e52266eae3263f864c3f084132d7c2c8/Lib/glyphsLib/builder.py#L51) where weight names are translated to weightclass (starting at `'Thin' = 250`).

This is to avoid issues on some applications.
See https://www.adobe.com/devnet/opentype/afdko/topic_font_wt_win.html
>Having a weightclass of 100 or 200 can result in a "smear bold" or (unintentionally) returning the style-linked bold. Because of this, you may wish to manually override the weightclass setting for all "extra light," "ultra light" or "thin" fonts.

**Comment by marekjez86** [comment]
@moyogo: thank you

@jamesgk : we either need to "manually" handle "extra light," "ultra light" or "thin" fonts 
OR
@dougfelt : we need to change the noto_lint.py to learn to live with these exceptions
Between two of you please decide.

@moyogo or @twardoch : what would be your advice?

**Comment by davelab6** [comment]
For Google Fonts, the usWeightClass of Thin should be 250 and ExtraLight
should be 275.

**Comment by JelleBosmaMT** [comment]
When we created a specification for the Noto fonts, Google decided to use 200 for the ExtraLight and 100 for the Thin weights. The consideration was that the few legacy Windows apps that might smear was not a problem.

**Comment by JelleBosmaMT** [comment]
I should add:
If you do not have a custom parameter Glyphs will cap the usWeightClass at 250 when generating a font.
If there is a custom parameter then Glyphs will use the value set by it. 

So any software that generates fonts from Glyphs files, should do the same. The decision is taken by the designer of the font, not the software.

**Comment by davelab6** [comment]
> When we created a specification for the Noto fonts

Has that been published? :)

**Comment by JelleBosmaMT** [comment]
It is a shared Google Doc.

**Comment by davelab6** [comment]
URL? :)

**Comment by JelleBosmaMT** [comment]
I don’t know if it is up to me to share this on GitHub. If you have any
business with it, you can ask the Google team for it.

**Comment by davelab6** [comment]
Sorry I misunderstood, I thought you were saying it was a **published** Google Doc =)

**Comment by dougfelt** [comment]
@jungshik, care to comment?  We had talked about this in December.

**Comment by jungshik** [comment]
'250' for the lower bound comes from a compatibility consideration with Windows GDI. All other targets (including newer Windows API) can handle 100 ~ 900.
In my opinion, we should use the full range (100 ~ 900) by default (Android, Mac, Linux do not have any issue). If we do need to care about Windows GDI, a Windows-GDI-specific 'hack' can be added (e.g. fix up usWeightClass to be 250 or larger when serving to Windows-GDI clients).

**Comment by brawer** [comment]
Duplicate of https://github.com/googlei18n/fontmake/issues/167?

**Comment by JelleBosmaMT** [comment]
In #167 it looks if the weight axis is using Glyphs weight interpolation
values rather than the weightClass values of the instances that have these
interpolation values. So no, it is not a duplicate. Although if for #167
you start looking at the weightClass values, you have to make sure you get
the right values: use the custom parameter if it is there.

**Comment by anthrotype** [comment]
as @moyogo explained in https://github.com/googlei18n/fontmake/issues/224#issuecomment-269011274, it looks like this is glyphsLib issue (not using `weightClass` custom parameter when setting the generated `ufo.info. openTypeOS2WeightClass`, so it should be re-opened under https://github.com/googlei18n/glyphsLib/issues/new

**Comment by davelab6** [comment]
Google Fonts certainly needs to care about Windows GDI users :)

**Comment by jungshik** [comment]
@davelab6 If you care, you can certainly serve modified versions with usWeightClass lowerlimit set to 250 to Windows GDI clients. I don't want Noto to be bogged down by WIndows GDI clients.

**Comment by marekjez86** [comment]
created https://github.com/googlei18n/glyphsLib/issues/135
closing this bug

**Comment by davelab6** [comment]
Jungshik, Google Fonts also offers fonts for download, and users expect that single non-modifiable-per-host copy to work everywhere. If you don't want Noto to be useful for your users, that's a pity
