### ISSUE TITLE
AutomatedTestReport: GPOSThe Class1Count does not match the values in ClassDef1

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#23]
I copied the text below from an email by Jelle.B who looked at regular Ethiopic font (see the otf file in the attached zip) generated by the pipeline from the glyphs file (see the attached zip) on about 1/Feb/2016. The comments pertain to that version of the pipeline. See the bottom of this message for the reason why I cannot generate a new version of the fonts.

'Of the errors listed by our test tool I mention:
GPOSThe Class1Count does not match the values in ClassDef1. (lookuplist
lookup 1 lookup subtable 29 pair pairclasses)
The following glyphs explicitly mapped to class zero in the second
ClassDef….
(lookuplist lookup 1 lookup subtable 5 pair pairclasses) Vxxxx'

[NotoSansEthiopicCondensed-Regular-km-error.zip](https://github.com/googlei18n/fontmake/files/133281/NotoSansEthiopicCondensed-Regular-km-error.zip)

Note that NotoSansEthiopic-MM.glyphs generates as of 12/Feb/2016 "defcon.errors.DefconError: The kerning data is not valid" so I cannot check what the newest version of pipeline generates (see https://github.com/googlei18n/fontmake/issues/13 )

**Comment by behdad** [comment]
Closing this unless Jelle has something more to offer.  Our GPOS seems to be just fine.  And we have switched to feaLib anyway.
