### ISSUE TITLE
Fails building NotoSansArabic-MM.glyphs

### ISSUE THREAD

**Issue by behdad** [googlei18n/fontmake#232]
Used to work.  Now I get:

```
    raise FeatureLibError("Expected a number", self.cur_token_location_)
fontTools.feaLib.error.FeatureLibError: /home/behdad/SSD/CURRENT/notophaseiii/noto-source/src/master_ufo/NotoSansArabic-Condensed.ufo/features.fea:1407:36: Expected a number
```

Sascha, can we 1. make feaLib+fontmake save the failing feature file somewhere? 2. make it print out a pretty listing of the failure location?

Or any other way to debug and fix this first? :)

Thanks.

**Comment by behdad** [comment]
cc @marekjez86

**Comment by behdad** [comment]
This is how I'm invoking fontmake BTW:
```
$ fontmake -o variable -g NotoSansArabic-MM.glyphs
```

**Comment by marekjez86** [comment]
cd noto-source
fontmake  -g src/NotoSansArabic-MM.glyphs -o variable
works for me

**Comment by marekjez86** [comment]
Other fonts displaying the same error (but Arabic seems to be the smallest test case)


fontTools.feaLib.error.FeatureLibError: /Users/marekj/newrel/noto-source/master_ufo/NotoSans-CondensedBold.ufo/features.fea:845:26: Expected a number
fontTools.feaLib.error.FeatureLibError: /Users/marekj/newrel/noto-source/master_ufo/NotoSansArabic-Condensed.ufo/features.fea:1407:36: Expected a number
fontTools.feaLib.error.FeatureLibError: /Users/marekj/newrel/noto-source/master_ufo/NotoSansArabicUI-CondensedBold.ufo/features.fea:1296:36: Expected a number
fontTools.feaLib.error.FeatureLibError: /Users/marekj/newrel/noto-source/master_ufo/NotoSansDisplay-CondensedSemiBoldItalic.ufo/features.fea:854:26: Expected a number
fontTools.feaLib.error.FeatureLibError: /Users/marekj/newrel/noto-source/master_ufo/NotoSansDisplay-Light.ufo/features.fea:854:24: Expected a number
fontTools.feaLib.error.FeatureLibError: /Users/marekj/newrel/noto-source/master_ufo/NotoSerif-BoldItalic.ufo/features.fea:881:38: Expected a number
fontTools.feaLib.error.FeatureLibError: /Users/marekj/newrel/noto-source/master_ufo/NotoSerif-CondensedLight.ufo/features.fea:880:26: Expected a number
fontTools.feaLib.error.FeatureLibError: /Users/marekj/newrel/noto-source/master_ufo/NotoSerifDisplay-Italic.ufo/features.fea:890:24: Expected a number
fontTools.feaLib.error.FeatureLibError: /Users/marekj/newrel/noto-source/master_ufo/NotoSerifDisplay-CondensedLight.ufo/features.fea:880:26: Expected a number

**Comment by behdad** [comment]
Ok, looks to me like feaLib is not happy that non-integers ended up in the .fea file:
```
LigatureCaretByPos allah.ar -322 0 803.25; 
```
Sascha, others, any idea how this crept in?  Or was the source really changed to include non-integer kerning?  If these are not valid in fea format, we should round when producing fea.

**Comment by behdad** [comment]
Ok I see the 803.25 in the source file. `position = "{803.25, 0}";`
We shall round those.  I'll take a look.

**Comment by behdad** [comment]
Reopening to roll glyphsLib req forward.
