### ISSUE TITLE
AutomatedTestReport: hmtxThe left sidebearing 34 does not match the glyph's xMin 35 (glyph 418)

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#24]
I copied the text below from an email by Jelle.B who looked at regular Ethiopic font (see the otf file in the attached zip) generated by the pipeline from the glyphs file (see the attached zip) on about 1/Feb/2016. The comments pertain to that version of the pipeline. See the bottom of this message for the reason why I cannot generate a new version of the fonts.

'Of the errors listed by our test tool I mention:
hmtxThe left sidebearing 34 does not match the glyph's xMin 35 (glyph 418)
13 more like this'

[NotoSansEthiopicCondensed-Regular-km-error.zip](https://github.com/googlei18n/fontmake/files/133281/NotoSansEthiopicCondensed-Regular-km-error.zip)

Note that NotoSansEthiopic-MM.glyphs generates as of 12/Feb/2016 "defcon.errors.DefconError: The kerning data is not valid" so I cannot check what the newest version of pipeline generates (see https://github.com/googlei18n/fontmake/issues/13 )

**Comment by behdad** [comment]
We should track down where the discrepancy is coming from.

**Comment by anthrotype** [comment]
I believe this has to do with this ufo2ft issue https://github.com/googlei18n/ufo2ft/issues/106 which should be fixed now. Please reopen if this is not the case.

**Comment by marekjez86** [comment]
Verified as fixed

**Comment by marekjez86** [comment]
@anthrotype : there's nothing to do; I just assigned it to you to give you credit for the investigation (in the future if you do any work please add yourself to assignees :-))
