### ISSUE TITLE
Support glyphOrder custom parameter

### ISSUE THREAD

**Issue by robmck-ms** [googlei18n/fontmake#246]
It would be helpful if fontmake/glyphsLib honored the glyphOrder custom parameter in Glyphs. This is useful when working with other tools that have a dependency on glyph order.

E.g. Selawik is hinted in VTT, with hint sources saved out to an XML file so I can re-apply hints anytime I rebuild the font. Trouble is, low-level code (e.g. OFFSET[]) has explicit glyph id references, thus once hinted, I need to preserve glyph order. Any new glyphs need to go at the end of the list so as to preserve the glyph IDs of previously hinted glyphs. So, I need some way to control glyph order.

(And, yes, I'd like to update VTT and it's various high/low level languages to support named references, but that's a really big work item).

**Comment by anthrotype** [comment]
I agree. We shall have glyphsLib honour the `glyphOrder` custom parameter if present, and set the generated UFO's `public.glyphOrder` accordingly, so that ufo2ft can use it when compiling the fonts.
I'll do that.

**Comment by anthrotype** [comment]
@robmck-ms if you `pip install --upgrade glyphsLib`, you should get support for the `glyphOrder` custom parameter.

https://github.com/googlei18n/glyphsLib/releases/tag/v1.5.0
https://pypi.python.org/pypi/glyphsLib/1.5.0

**Comment by robmck-ms** [comment]
You guys are fantastic! Thanks!
