### ISSUE TITLE
Fontmake should not “preprocess” glyphs sources

### ISSUE THREAD

**Issue by brawer** [googlei18n/fontmake#249]
fontmake currently has a “preprocess” function to handle glyph names with hyphens. (In Glyphs files, glyphs can contain hyphens in their names, but hyphens are not valid in Adobe feature files).

However, the current implementation is **extremely** fragile: It tries to extract glyph names from the glyphs source, under the (wrong) assumption that anything with a `name` property in the Glyphs source is probably a glyph. Then, it just runs a string replace on the entire input, in the (wrong) hope that those rewrites won’t affect anything else but the glyph name.

An example where this doesn’t work is https://github.com/googlei18n/fontmake/issues/247. Here, the font contained the following (abbreviated) dictionary with TrueType hinting zones. fontmake wrongly recognizes the string “B: -219” as a glyph name, rewrites it to “B: .219”, and then it shoves it into glyphsLib.

```p
{
name = TTFZones;
value = (
{
name = "B: 0";
position = 0;
size = -15;
},
{
name = "B: -219";
position = -219;
size = -18;
}
);
```

Instead of doing such hackery, I think fontmake should pass the original, unmodified glyphs file to glyphsLib. It’s the task of glyphsLib to deal with valid input Glyphs files, and convert this to valid UFO with valid OpenType feature files. Therefore, it’s clearly within the scope of glyphsLib to know what constitutes a valid glyph name in what file format. Of course it’s necessary to handle this unfortunate mismatch, but for doing this correctly, one needs to parse the file. So the place for doing such rewrites should be glyphsLib and not fontmake.

**Comment by anthrotype** [comment]
Totally agree. Anybody would like to takes this up?

**Comment by brawer** [comment]
I’m a bit confused by the behavior of Glyphs.app. When I export a font to UFO, Glyphs happily produces UFOs with `features.fea` files whose glyph names contain dashes, which means they are in violation of [§2.f.i of the AFDKO syntax](http://www.adobe.com/devnet/opentype/afdko/topic_feature_file_syntax.html#2.f.i). The [UFO3 specification](http://unifiedfontobject.org/versions/ufo3/features.fea/) says that the file should be in AFDKO syntax. So Glyphs.app seems to produce invalid UFOs. What should glyphsLib do?

**Comment by anthrotype** [comment]
I believe the features.fea should use the same names as those from the `name` attribute of the `glyphs/*.glif` files.
We already store the production names in the UFO `lib.postscriptNames`, which ufo2ft then uses to do the glyph renaming directly on the compiled font.

Does feaLib reject those glyph names?

**Comment by moyogo** [comment]
The specs should be updated. There’s an issue for that https://github.com/adobe-type-tools/afdko/issues/152 and for feaLib there’s the issue fonttools/fonttools#559.

Fontmake should definitely not do this.
