### ISSUE TITLE
fontmake error when compiling Roboto Italic variable fonts

### ISSUE THREAD

**Issue by erinmclaughlin** [googlei18n/fontmake#250]
After updating fontmake on Feb 6th at 10pm cst (latest commit was [this](https://github.com/googlei18n/fontmake/commit/8be47470b7b638b7c8a2d2136076f90e8fe13f52)), I attempted to generate new Roboto variable fonts using the interpolated source ufos found here: https://github.com/erinmclaughlin/roboto/tree/everything-in-source-interp/src/v2

I used this command 
` fontmake -m RobotoUpright.designspace -o variable --no-production-names` 
to generate RobotoUpright-GX.ttf successfully.

Unfortunately, ` fontmake -m RobotoItalic.designspace -o variable --no-production-names`  did not work. Here are the last few lines of output before the error, in case it is helpful:

>   File "/Users/erinmclaughlin/env/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 410, in merge
    subtables = [_Lookup_PairPos_subtables_canonicalize(l.SubTable, merger.font) for l in lst]
  File "/Users/erinmclaughlin/env/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 397, in _Lookup_PairPos_subtables_canonicalize
    tail.insert(0, _Lookup_PairPosFormat1_subtables_merge_overlay(head, font))
  File "/Users/erinmclaughlin/env/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 376, in _Lookup_PairPosFormat1_subtables_merge_overlay
    [v.PairSet for v in lst])
  File "/Users/erinmclaughlin/env/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 144, in _merge_GlyphOrders
    assert all(sorted(vs, key=sortKey) == vs for vs in lst)
AssertionError: ('Lookup', '[1]', 'list', '.Lookup', 'LookupList', '.LookupList', 'GPOS', '.table', 'table_G_P_O_S_')

The Italic variable font did successfully compile several weeks ago using the `--no-gpos` command before I updated fontmake.

Let me know if there's anything else I can provide that can be of help. Thanks!

**Comment by davelab6** [comment]
> The Italic variable font did successfully compile several weeks ago using the --no-gpos command before I updated fontmake.

Does it still work with that argument?

**Comment by erinmclaughlin** [comment]
I got this error when I tried  `fontmake: error: unrecognized arguments: --no-gpos`

**Comment by davelab6** [comment]
lol ok

**Comment by davelab6** [comment]
I took a quick look at this ([direct download link](https://github.com/erinmclaughlin/roboto/blob/everything-in-source-interp/src/v2/RobotoUpright-GX.ttf?raw=true)) and it seems bogus in several ways:

- [ ] The named instances are not right, it seems condensed styles need to be named as such, and there are **three** regulars...

<img width="1286" alt="screen shot 2017-02-06 at 21 35 08" src="https://cloud.githubusercontent.com/assets/261579/22679118/8d19d4b4-ecb4-11e6-8a5b-d20bf7132e88.png">

- [ ] The spacing is really not right

<img width="1283" alt="screen shot 2017-02-06 at 21 35 47" src="https://cloud.githubusercontent.com/assets/261579/22679117/8d19697a-ecb4-11e6-80a9-e08c0469a0b7.png">

<img width="1283" alt="screen shot 2017-02-06 at 21 36 24" src="https://cloud.githubusercontent.com/assets/261579/22679116/8d17d2fe-ecb4-11e6-993d-1683b9e2bc6d.png">

**Comment by erinmclaughlin** [comment]
I've edited the designspace file, regenerated, and the spacing in the output file looked fine. So those spacing errors must not have been fontmake's fault.

**Comment by erinmclaughlin** [comment]
Ok, so I've learned that I needed to give the full name in the "stylename" field, not just the weight, in order to prevent duplicates. However, for some reason, the Regular is still populating twice, one from the "instances" specification, and also the master Regular.

In the original designspace file that I was given, the Thin, Regular, and Bold instances were all given slightly different weight values than were used in the original master. (The instance for Regular uses xvalue="90.0" yvalue="92.0")

I did a test, naming the regular-width instances with "i" at the end of them in this example. You can see that the Master Regular is also being included in the variable font. 

I am not sure how to prevent this from happening.

<img width="1028" alt="screen shot 2017-02-07 at 11 32 34 am" src="https://cloud.githubusercontent.com/assets/7864323/22703500/02d43134-ed2a-11e6-86d0-8e8a333f52db.png">
<img width="989" alt="screen shot 2017-02-07 at 11 32 42 am" src="https://cloud.githubusercontent.com/assets/7864323/22703501/02d663b4-ed2a-11e6-89f0-a0e08aa86dfb.png">

**Comment by anthrotype** [comment]
hello @erinmclaughlin, thanks for your report!

The `--no-gpos` option is in a separate branch, which has never been merged into master and is now out of sync:
https://github.com/googlei18n/fontmake/commit/a08c2b53baa7d6aa452b795c01e59f3a8015c33b

@brawer @behdad whad do we do? Do we want to add the option?

About fontmake failing with RobotoItalic.designpace, the AssertionError is coming from fontTools.varLib.merger:

https://github.com/fonttools/fonttools/blob/ef0eb9dc8f9d634988ab7c4d2859216d5bd1b291/Lib/fontTools/varLib/merger.py#L143-L144

It could be that the fonts you're merging don't share the same glyph order?

**Comment by erinmclaughlin** [comment]
@anthrotype Thanks! I'll take another look at glyph order, though the Italic generated fine before when I was using the no gpos branch.

**Comment by anthrotype** [comment]
yes, but they were generating without GPOS, i.e, no kerning, marks, etc.

**Comment by erinmclaughlin** [comment]
@anthrotype Fudge, you're right, the order is wrong.
Do you have any ideas about why Regular is showing up twice (as a master and as an instance) in my Upright output? 

Does fontmake automatically put the master which you've copied groups,features,info, and lib from in the final output?

**Comment by davelab6** [comment]
> the Regular Italic is showing up twice (at the master weight (100,100), and as the "regular" instance weight). Does fontmake automatically put the master which you've copied groups,features,info, and lib from in the final output?

Hmm, I know that the `--masters-as-instances` option outputs masters as instances, but in your above comment you don't use that. You could try turning it off, but it is off by default, I think

**Comment by davelab6** [comment]
> the Regular Italic is showing up twice (at the master weight (100,100), and as the "regular" instance weight).

Do they look 1:1 the same? :)

**Comment by erinmclaughlin** [comment]
@davelab6  Nope, both the Upright and Italic are having the same issue, 2 regulars. One is heavier than the other. The lighter weight is the correct one. (I hope these animated gifs work)

![robotoitalic](https://cloud.githubusercontent.com/assets/7864323/22762696/4deb628a-ee26-11e6-8338-893ebfe1ccef.gif)
![robotoupright](https://cloud.githubusercontent.com/assets/7864323/22762695/4dea89aa-ee26-11e6-9d82-1dbbf8f29c59.gif)

dumb question... how do I turn that off?  --no-masters-as-instances  ?

**Comment by davelab6** [comment]
I checked and indeed, its only possible to turn it on. So I expect its something in your designspace file.

**Comment by davelab6** [comment]
Love the GIFs. But why are they not 1:1?

Are all the other named instances 1:1 with the pre-GX fonts?

**Comment by twardoch** [comment]
The `--no-gpos` option can be simulated by performing: 

```
pip install git+https://github.com/twardoch/feaLab.git
fontmake -g SOURCEFONT.glyphs --keep-overlaps --no-production-names -o variable --kern-writer-module feaLab.writers.kernFeatureNoWriter --mark-writer-module feaLab.writers.markFeatureNoWriter
```

**Comment by behdad** [comment]
Can someone clarify what problem we are talking about? This looks like transcript of a support call than a bug report now. :)

**Comment by erinmclaughlin** [comment]
@davelab6  Here's the Upright [designspace](https://github.com/erinmclaughlin/roboto/blob/everything-in-source-interp/src/v2/RobotoUpright.designspace) file. These were the interpolation values given to me when I entered the project. As you can see, the weight values of the Instances of Reg and Bold are not 1:1 with the Master Reg and Bold. But, Bold is not being erroneously duplicated, only Regular is. (I've added the "i" to the interpolated Regular style name to differentiate it in the output, after I first saw the duplication). I have no idea why the Master is also being output - I am totally new to this fontmake process. Can you check it for errors?

@twardoch Thanks for the info!!

@behdad Yup, sorry this got confusing and long-winded. 
I'm not sure if this is a fontmake issue or not anymore: for some reason, the Regular weight Master is automatically being included as a selectable style in my Variable fonts, instead of _just_ the instances.
Here's the link to the upright [designspace]([https://github.com/erinmclaughlin/roboto/blob/everything-in-source-interp/src/v2/RobotoUpright.designspace]) file.  The command I used to generate was `fontmake -m RobotoUpright.designspace -o variable --no-production-names`
If anyone catches an error I've made, please let me know and I'll promptly close this "issue" :)

Thanks for the help, everyone.

**Comment by behdad** [comment]
> the Regular weight Master is automatically being included as a selectable style in my Variable fonts

Currently we always require a master to be the "base font". And base font is always visible to the consuming system.

**Comment by behdad** [comment]
> the Regular weight Master is automatically being included as a selectable style in my Variable fonts
> 
> Currently we always require a master to be the "base font". And base font is always visible to the consuming system.

Depending on how badly you need otherwise, I can prioritize working on it.

**Comment by davelab6** [comment]
@erinmclaughlin is `Regular` or `Regular i` a 1:1 match for the pre-vf regular?

**Comment by erinmclaughlin** [comment]
@davelab6 Just compared with the previously-released fonts. The `Regular i` is the 1:1 match of the pre-vf Regular font.  `Regular` is too heavy.

So... do we bother Behdad and have someone figure out how to export variable fonts without including the Regular master as one of the options? Or... do I figure out how to make the `Regular i` weight into a Master, change the designspace file, and then we make the vf from that? Or... maybe a different solution?

**Comment by behdad** [comment]
So, if Regular master is not really Regular, just rename its style to something else.  Would that not work?

**Comment by davelab6** [comment]
Perhaps not: Since non-VF-aware systems will use the 'base' font, should that map 1:1 to the previous regular?

**Comment by behdad** [comment]
We don't care about non-VF-aware systems using the VF font right now.

**Comment by xiangyexiao** [comment]
@erinmclaughlin have you got a chance to take Behdad's suggestion to rebuild RobotoUpright-GX.ttf and RobotoItalic-GX.ttf, i.e., rename masters to something else, and rename Regular/Bold/Thin i to Regular/Bold/Thin?

**Comment by erinmclaughlin** [comment]
@behdad @xiangyexiao  Hi, all! I attempted changing the style name, of the Regular Master, but it didn't fix the problem. I also changed the weight class value (from 400 to 390), but still no luck.

Could this automatic-insertion be related to the designspace value (100,100) rather than the actual style name or weight attribute?

**Comment by xiangyexiao** [comment]
@brawer @zjusbo @behdad could any of you try to fix this issue?

**Comment by khaledhosny** [comment]
I had the original issue with a different font:
```
fontTools/varLib/merger.py", line 144, in _merge_GlyphOrders
    assert all(sorted(vs, key=sortKey) == vs for vs in lst)
AssertionError: ('Lookup', '[1]', 'list', '.Lookup', 'LookupList', '.LookupList', 'GPOS', '.table', 'table_G_P_O_S_')
```

After few hours of debugging turns out my masters had different glyph orders, so the glyph coverage were sorted differently across masters but varLib is assuming there one glyph order for all masters. I think fontmake should make sure the glyph order is identical when building interpolatable masters, or may be varLib should warn error on that the masters are not compatible rather than failing later in mysterious (to me at least) way.

**Comment by behdad** [comment]
One day we would allow different glyphsets.  For now, the assert is there to make sure we don't silently drop glyphs or fail later on even more cryptically.  Not an issue right now.
