### ISSUE TITLE
AutomatedTestReport: The usMaxContext should be 3, but is 0

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#26]
I copied the text below from an email by Jelle.B who looked at regular Ethiopic font (see the otf file in the attached zip) generated by the pipeline from the glyphs file (see the attached zip) on about 1/Feb/2016. The comments pertain to that version of the pipeline. See the bottom of this message for the reason why I cannot generate a new version of the fonts.

'Of the errors listed by our test tool I mention:
The usMaxContext should be 3, but is 0'

[NotoSansEthiopicCondensed-Regular-km-error.zip](https://github.com/googlei18n/fontmake/files/133281/NotoSansEthiopicCondensed-Regular-km-error.zip)

Note that NotoSansEthiopic-MM.glyphs generates as of 12/Feb/2016 "defcon.errors.DefconError: The kerning data is not valid" so I cannot check what the newest version of pipeline generates (see https://github.com/googlei18n/fontmake/issues/13 )

**Comment by behdad** [comment]
@jamesgk is working on this.

James: I suppose Glyphs is using AFDKO number for this.  Looking for usMaxContext in AFDKO source leads to OS_2SetMaxContext, which is called once from each of GSUB and GPOS.  If you search for maxContext in FDK/Tools/Programs/makeotf/makeotf_lib/source/hotconv/GSUB.c and FDK/Tools/Programs/makeotf/makeotf_lib/source/hotconv/GPOS.c you see exactly how they are computing it.  Please follow the same.

In particular, the main difference I see with what you have is, they use inputCount+lookAheadCount.  Ie, backtrackCount is NOT added.  I can see how they arrive at that...

**Comment by jamesgk** [comment]
Well, I've tried to match the AFDKO (at https://github.com/googlei18n/ufo2ft/blob/usmaxcontext/Lib/ufo2ft/makeotfParts.py#L210), but still the calculated differences are sometimes different from those already present in noto-font binaries. For example it calculates usMaxContext of 2 for Ethiopic, and 15(!) for Nastaliq.

**Comment by behdad** [comment]
> Well, I've tried to match the AFDKO (at https://github.com/googlei18n/ufo2ft/blob/usmaxcontext/Lib/ufo2ft/makeotfParts.py#L210), but still the calculated values are sometimes different from those already present in noto-font binaries. For example it calculates usMaxContext of 2 for Ethiopic, and 15(!) for Nastaliq.

Nastaliq, and possibly Ethiopic, were done using Monotype's own proprietary build tools I believe, and hence use a different heuristic.

**Comment by marekjez86** [comment]
Definitely anything that has its own *{GPOS,GDEF,GSUB}*.txt  data goes
through MTI's proprietary build tools. I doubt they use something different
when there are no separate *{GPOS,GDEF,GSUB}*.txt files. Hence this is very
likely scenario and an explanation for the differences.

On Fri, Mar 4, 2016 at 5:58 PM, Behdad Esfahbod <notifications@github.com>
wrote:

> Well, I've tried to match the AFDKO (at
> https://github.com/googlei18n/ufo2ft/blob/usmaxcontext/Lib/ufo2ft/makeotfParts.py#L210),
> but still the calculated values are sometimes different from those already
> present in noto-font binaries. For example it calculates usMaxContext of 2
> for Ethiopic, and 15(!) for Nastaliq.
>
> Nastaliq, and possibly Ethiopic, were done using Monotype's own
> proprietary build tools I believe, and hence use a different heuristic.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/googlei18n/fontmake/issues/26#issuecomment-192550039>.
>



-- 

Marek Z Jeziorek [ 老马 ] | marekj@google.com | 312 725-6958

**Comment by jamesgk** [comment]
Well, do we want to try to match this heuristic? Or just go with the new values?

**Comment by behdad** [comment]
Go with new values.  Roughly matching AFDKO is more than enough for this
useless field!

On Tue, Mar 8, 2016 at 8:19 AM, James Godfrey-Kittle <
notifications@github.com> wrote:

> Well, do we want to try to match this heuristic? Or just go with the new
> values?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/googlei18n/fontmake/issues/26#issuecomment-193500392>.
>



-- 
behdad
http://behdad.org/

**Comment by jamesgk** [comment]
:laughing: SGTM
