### ISSUE TITLE
Pipeline creates Myanmar fonts without GPOS entries for KSW and MON 

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#265]
copied from a report I received:
"This was found while checking the validity of the GSUB and GPOS in fonts created by pipeline. The designer states: ‘Myanmar is used in two other languages, Mon and Sgaw Karen, which are accounted for in our GPOS and GSUB. Pipeline seems to drop the two scripts from the GPOS.
GPOS in Pipeline Instances DO NOT carry over to Script Locales.

The code below was dumped from the Pipeline’s Noto Sans Myanmar Regular’s GPOS. The Regular instance is supposed to be equivalent in weight and width to the Noto Sans Myanmar Regular Master made by Monotype.
 
script table begin
mym2    default         0, 1, 2
script table end
 
However, the script table above is missing two locales present in our Regular Master:
 
script table begin
mym2    default         0, 1, 2
mym2   KSW           0, 1, 2
mym2   MON           0, 1, 2
script table end
 
As a result, when in a different locale, there is NO GPOS positioning taking place in the pipeline generated fonts."

For reference:

- the source in question is in https://github.com/googlei18n/noto-source/tree/master/src/NotoSansMyanmar
- a sample font generated by the pipeline on 2017.March.1 is in https://github.com/googlei18n/noto-fonts/blob/master/alpha/from-pipeline/unhinted/otf/sans/NotoSans-Regular.otf

**Comment by marekjez86** [comment]
@jungshik : does this sound like an issue that could cause Roboto's problem?

**Comment by marekjez86** [comment]
@brawer @anthrotype : Cosimo, what would it take to have this corrected (and whom should I ask to fix it)? this is a prerequisite to support Mon (and Sgaw Karen).

**Comment by jungshik** [comment]
> @jungshik : does this sound like an issue that could cause Roboto's problem?

What problem do you have in mind?  I don't think this can cause any of Roboto's problem that I know of. 

This issue is about not including non-default language in GPOS/GSUB (KSW, MON).  

BTW, Myanmar scripts can be used to write more than KSW, MON and Burmese. Do they also need lang-specific shaping rules?

**Comment by punchcutter** [comment]
This appears to be happening in `fonttools/subset/__init__.py` in `remove_redundant_langsys()`. For the Myanmar the GPOS feature list is identical for default, KSW, and MON. So KSW and MON are removed as being redundant. The GSUB feature lists have differences which is why they don't get wiped out.

**Comment by behdad** [comment]
Correct.
