### ISSUE TITLE
Omit TTFA table?

### ISSUE THREAD

**Issue by brawer** [googlei18n/fontmake#268]
Should fontmake omit the TTFA table from its output? In https://github.com/googlei18n/noto-fonts/pull/862, @jungshik and @dougfelt noticed that fontmake output contains TTFA tables. These are generated by ttfautohint when running with the [-t or --ttfa-table option](https://www.freetype.org/ttfautohint/doc/ttfautohint.html#add-ttfa-info-table). But at least currently, this is purely informational; all TrueType rendering engines ignore the table.

**Comment by davelab6** [comment]
I like to have them in GF fonts because the API will strip them, but it's
useful metadata to debug hinting issues

If fontbakery by default strips them, please make an optional argument to
include them :)

**Comment by anthrotype** [comment]
I don't see where is the problem. fontmake `-a [AUTOHINT]` option does what it's being told; if you do tell fontmake to call `ttfautohint` command with `-t` option, then you will get the TTFA table; otherwise you won't.
Am I missing something?

**Comment by brawer** [comment]
Oh! Thanks... blush. Ahem.
