### ISSUE TITLE
Hebrew non-VF fonts have missing entries in GDEF - GlyphClassDef. 

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#273]
The source: https://github.com/googlei18n/noto-source/blob/master/src/NotoSansHebrew-MM.glyphs

Pipeline generated font: https://github.com/googlei18n/noto-fonts/blob/master/alpha/from-pipeline/unhinted/ttf/sans/NotoSansHebrew-Regular.ttf
Glyphs.app generated font: https://github.com/googlei18n/noto-fonts/blob/master/alpha/from-glyphsapp/unhinted/ttf/sans/NotoSansHebrew-Regular.ttf

test cases:

```html
	<p style="font-weight:700">וַיִּפֶן אַחֲרָיו וַיִּרְאֵם,</p>
	<p style="font-weight:700">וַיְקַלְלֵם בְּשֵׁם יְהוָה;</p>
```

the differences using fontdiff

[pipeline is lower/green, note additional spacing]
![he-001](https://cloud.githubusercontent.com/assets/13322623/23913766/2b1d5b38-08a1-11e7-9c39-a182a31e6370.jpeg)

[pipeline is lower/green, note additional spacing, but also notice shift of diacritics to the left of "w-like" letter]
![he-002](https://cloud.githubusercontent.com/assets/13322623/23913828/58d8c5f8-08a1-11e7-87e2-7ef95725cb83.jpeg)

The font generated from the same sources by the Glyphs.app appears to behave correctly.

**Comment by anthrotype** [comment]
I wonder if this is glyphsLib issue might be related:
https://github.com/googlei18n/glyphsLib/issues/115

@marekjez86 do those combining mark glyphs have a non-zero advance? GlyphsLib currently does _not_ zero them out, Glyphs.app does.

**Comment by marekjez86** [comment]
I forgot to add: while the metrics are somewhat off (pipeline VF hebrew appears to be slightly "fatter"), the VF font produced by the pipeline doesn't appear to have the same problem as static TTfs.

![he-g-p-002](https://cloud.githubusercontent.com/assets/13322623/23914949/c1fdb8b0-08a4-11e7-98ae-419bc31a5fcb.jpeg)

**Comment by punchcutter** [comment]
The marks have a non-zero advance so it's definitely the issue @anthrotype mentioned. I almost have a pull request ready for glyphsLib where I could fit this in as it's related.

**Comment by behdad** [comment]
Someone needs to debug why varfont works but static doesn't. Might be user error.

**Comment by xiangyexiao** [comment]
Marek,

could you look into this bug?

I am wondering whether Glyphs app generated static font has the same issue.

**Comment by marekjez86** [comment]
@xiangyexiao : Glyphs app generated static font doesn't have this problem (see the first two images upper/pink lines).

**Comment by marekjez86** [comment]
@punchcutter : what's the status of the change mentioned in the comment above: "The marks have a non-zero advance so it's definitely the issue @anthrotype mentioned. I almost have a pull request ready for glyphsLib where I could fit this in as it's related."? any update? If done, where could I get it?

**Comment by anthrotype** [comment]
See https://github.com/googlei18n/glyphsLib/pull/154

**Comment by behdad** [comment]
@marekjez86 Can you confirm that there's no user error involved?  I just built variable, otf, and ttf fonts from the same source and all three work as expected.  The code I'm running definitely does NOT have the googlei18n/glyphsLib#154 fix, and I know that fix is NOT required for this sequence to work.  Something else is going on.

**Comment by marekjez86** [comment]
@behdad : it's possible that this is an older build of the fonts or a fontdiff problem. I'll check it out later today. Could you send me the fonts that you built so I can have them as a reference?

**Comment by xiangyexiao** [comment]
@marekjez86 

Is this issue still there?

**Comment by xiangyexiao** [comment]
I tested the two test cases with FontView using the two fonts in the first provided in the original report, but cannot reproduce this issue.
<img width="1281" alt="screen shot 2017-03-31 at 4 34 51 pm" src="https://cloud.githubusercontent.com/assets/12721521/24572729/3582913c-1630-11e7-8355-6991f5b27bce.png">
<img width="1359" alt="screen shot 2017-03-31 at 4 32 25 pm" src="https://cloud.githubusercontent.com/assets/12721521/24572730/3583ee6a-1630-11e7-9720-5660e5686c9c.png">

top: pipeline generated
bottom: glyphsapp generated.

**Comment by xiangyexiao** [comment]
also tested the two fonts in the original report with hb-view. Don't see this bug.
<img width="1399" alt="hb" src="https://cloud.githubusercontent.com/assets/12721521/24572942/35699478-1632-11e7-8b92-6fa515f5617d.png">

bottom: pipeline generated font
top: glyphsapp generated font

so close it

**Comment by xiangyexiao** [comment]
@marekjez86 please check if fontdiff has an issue.

**Comment by xiangyexiao** [comment]
for peace of mind, also checked VF. no issue either.

<img width="1400" alt="3-way" src="https://cloud.githubusercontent.com/assets/12721521/24573176/ca59b714-1634-11e7-9a14-5930b16e26c6.png">

**Comment by xiangyexiao** [comment]
@jungshik 

Noto Serif Hebrew doesn't have this issue either (internal bug report mentions serif fonts too)

<img width="1402" alt="serif" src="https://cloud.githubusercontent.com/assets/12721521/24573245/c82cc994-1635-11e7-9a56-739b88c96830.png">

1st line: glyphsapp static
2nd line: pipeline generated static
3rd line: pipeline generated VF

**Comment by jungshik** [comment]
The 1st line is Phase 2 and the 2nd line is phase 3 -static (Noto Sans Hebrew-Regular)
![image](https://cloud.githubusercontent.com/assets/8578343/24573455/1e4bb662-1638-11e7-9c5f-a2c3268a1044.png)

It's from hb-veiw ToT with direction=rtl. 

The input string is made up of the following code points (I got the code points from Marek's bug report in comment 0; I might have made a mistake somewhere)> 

05d5,05b7,05d9,05bc,05b4,05e4,05b6,05df,0020,05d0,05b7,05d7,05b2,05e8,05b8,05d9,05d5

**Comment by xiangyexiao** [comment]
just a heads-up. I updated FontView from 0.2.0 to 0.2.3 and this issue appears again. will try to report more details later

**Comment by xiangyexiao** [comment]
@behdad @jungshik @roozbehp 

Okay here is the complete report. 

Summary: 

With HarfBuzz 1.4.5:
Spacing and Nikkud shifting issues can be seen with the pipeline generated NotoSansHebrew static and NotoSerifHebrew static fonts. VF fonts and glyphsapp generated static fonts don't have this issue.

With BarfBuzz 1.3.3:
glyphsapp generated static fonts and pipeline generated static and VF fonts don't have this issue (as reported above).

wondering if there is any regression issue in HarfBuzz.

My command line: hb-view --font-file=x.ttf --text-file=test.txt --output-file=out --output-format=png

<img width="1401" alt="sans" src="https://cloud.githubusercontent.com/assets/12721521/24574900/ad7a8dde-164e-11e7-8420-1461994bd86d.png">
Sans-serif fonts
1st line: glyphsapp generated static font
2nd line: pipeline generated static font
3rd line: pipeline generated VF

<img width="1396" alt="serif" src="https://cloud.githubusercontent.com/assets/12721521/24574917/d744f154-164e-11e7-8732-8254e4f7e395.png">
Serif fonts
1st line: glyphsapp generated static font
2nd line: pipeline generated static font
3rd line: pipeline generated VF

**Comment by jungshik** [comment]
HarfBuzz 1.4.2 is also fine. ToT Harfbuzz somehow does not like the pipeline generated static Hebrew fonts.

**Comment by jungshik** [comment]
> HarfBuzz 1.4.2 is also fine.

Sorry for the confusion.  HarfBuzz 1.4.2 does have the same issue with a pipeline-built Noto Hebrew static fonts as shown in https://github.com/googlei18n/fontmake/issues/273#issuecomment-290879035

**Comment by jungshik** [comment]
There are two issues here. One is handling of sequences like <U+05D9, U+05BC>. 

With the pipeline generated NotoSansHebrew-Regular (static), I got this from hb-text (--direction=rtl):

```
[dagesh.hb=0@92,108+167|yod.hb=0+235]
```

With glyphsapp generated NotoSansHebrew-Regular (static), I got this from hb-text (--direction=rtl):
```
[uni05BC=0@-75,108+0|uni05D9=0+235]
```
Aside from the glyph name difference (that does NOT matter), the position of 'dagesh' (uni05BC) is difference between two. 

The above is all from HarfBuzz (740fdbc ).

**Comment by jungshik** [comment]
Harfbuzz 1.3.3 with the pipeline generated NotoSansHebrew-Regular.ttf (static) gives me the following:

```
[hiriq.hb=0@36,0+0|dagesh.hb=0@-75,108+0|yod.hb=0+235]
```
That's the same as Harfbuzz ToT (740fdbc) + the glyphapp generated font (the glyph name difference does not matter.). 

So, as Xiangye found out, somehow Harfbuzz ToT does not like NotoSansHebrew static generated by the pipeline while HB 1.3.3 was fine with it.

**Comment by jungshik** [comment]
With bisecting, I found out a commit in HarfBuzz that triggered this issue. It's a fix  for behdad/harfbuzz#347. 

```
Revert "Synthesize GDEF glyph class for any glyph that does not have one in GDEF"
This reverts commit 69f9fbc4200442a35484d3c790ae8f4979be5d60.
```

I don't think we can revert the above commit (because that does the 'right' thing). Still need to figure out why Noto*Hebrew static from the pipeline has an this issue. Either its GDEF is somehow 'broken' or GSUB/GPOS do not have Hebrew ScriptSystem or something. 

I compared GDEF tables from pipeline-static, pipeline-vf and glyphsapp-static. 

pipeline-vf and glyphsapp-static are similar (aside from VF-related entries in the former). However, a lot of entries are missing in pipeline-static's GDEF-GlyphClassDef (pipeline-vf has ~50 more entries in GlyphClassDef than pipeline-static). 

Without Harfbuzz synthesizing GDEF classes any more, those missing entries would lead to this issue. 

So, next question is why pipeline generates seeming deficient GDEF table for static fonts.

**Comment by jungshik** [comment]
JFYI: 
As a spot check, I compared GDEF in NotoSansKhmer-Regular.ttf to GDEF in NotoSansKhmer-VF.ttf (both generated by fontmake). They're identical as far non-VF-related sections of GDEF are concerned. 
It may be necessary to do this check more systematically.

**Comment by punchcutter** [comment]
Comparing to the Noto Khmer isn't so good because the Khmer GDEF is coming from --mti-source in fontmake. The Hebrew GDEF is generated with glyphsLib which until 1.5.2 has not been correct. This has been addressed in https://github.com/googlei18n/glyphsLib/pull/154 so it should hopefully be correct when glyphsLib is updated. 

I see a couple issues here. 
1. GDEF and mark classes have not been generated correctly
2. Zeroing of mark width (like Glyphs does by default on export). This is also addressed in the above pull request.
3. Kerning. Glyphs export makes a features.fea file with a kern feature. In the UFOs generated by pipeline the features.fea file does not contain the kerning at all. It is only in the UFO's kerning.plist, but does not seem to be applied correctly. I tried copying features.fea from the Glyphs export into the UFO and then running fontmake -u on the UFO and the spacing and kerning was then correct. Also, the Glyphs generated font has the kern feature under both hebr/default and hebr/IWR, but pipeline only has it under hebr/default and not DFLT/default. This shouldn't really make a big difference in this case, but the Glyphs generated and pipeline generated do not match here.

**Comment by punchcutter** [comment]
I see why the kerning isn't working correctly. IgnoreMarks=False in the pipeline generated, but not in the Glyphs generated. If I just flip that flag in the pipeline generated then the kerning works.

**Comment by jungshik** [comment]
Thank you, @punchcutter !

@marekjez86 , can you rebuild Hebrew static fonts? 

@dougfelt

**Comment by marekjez86** [comment]
@punchcutter : do I need to do anything special to correct "IgnoreMarks=False in the pipeline generated, but not in the Glyphs generated."? Where is it done? When was it done?

**Comment by punchcutter** [comment]
@marekjez86 I only edited the binary TTF as a test to make sure it was only this flag that was causing kerning to fail. I don't see anywhere in the UFO format to store these flags, but in the pipeline it can be done in ufo2ft in kernFeatureWriter.py.  I just tried by adding the IgnoreMarks line here and it seems to work:
```
        if rtlKern:
            lines.append("lookup kern_rtl {")
            lines.append("lookupflag IgnoreMarks;")
```
One question, though, is whether or not this should always be set to True. 
@schriftgestalt When Glyphs creates the auto-generated kern feature and adds this flag to the features.fea is it always set to True or do you have some rules? I think in most cases IgnoreMarks is desired, but there could be situations where it's not wanted.

**Comment by schriftgestalt** [comment]
In Glyphs, most scripts (including Hebrew) get the `IgnoreMarks` set by default.

**Comment by punchcutter** [comment]
@schriftgestalt Nice. That's helpful. Are there any scripts that don't get it set by default? Or do you have a list of scripts it does get set for? If we want the pipeline to produce the same thing as Glyphs then we should definitely add this to ufo2ft.

**Comment by behdad** [comment]
I think ignoring is a better default, yes.

**Comment by marekjez86** [comment]
@jungshik : I rebuilt the fonts at https://github.com/googlei18n/noto-fonts/blob/master/alpha/from-pipeline/unhinted/ttf/sans/NotoSansHebrew-Regular.ttf and others but from the discussion above it looks that it might not help. I'll try to check later, but it looks to me that we need to modify the code.

**Comment by schriftgestalt** [comment]
There are some rules but they end up to set it for most scripts in the end. And for the ones that don't get it right now, it should better be set I suppose.

This is a hardcoded list that get it:
`latin, cyrillic, arab, hebrew, nko, syriac, thai, lao, myanmar, khmer, devanagari, georgian`
And all other indic scripts get it, except `kannada`.

**Comment by punchcutter** [comment]
@marekjez86 Yes, glyphsLib needs to be updated to at least 1.5.3 and ufo2ft should be updated to set `IgnoreMarks`. Then if you rebuild it should look correct. My local tests look good so far.

**Comment by jungshik** [comment]
@marekjez86  Sorry that I was not clear (and thank you for rebuilding them anyway). I meant rebuilding after updating glyphsLib and ufo2ft (what @punchcutter wrote).

**Comment by anthrotype** [comment]
ufo2ft 0.4.2 now sets `IgnoreMarks` lookup flag, thanks to @punchcutter 
https://pypi.python.org/pypi/ufo2ft/0.4.2

**Comment by marekjez86** [comment]
I pulled recent fontmake.
Updated requirements for ufo2ft to 0.4.2
**_more requirements.txt_** 
_fonttools==3.9.1
cu2qu==1.1.1
glyphsLib==1.6.0
ufo2ft==0.4.2
MutatorMath==2.0.3
defcon==0.3.1
booleanOperations==0.7.0_

built fontmake and used 
https://github.com/googlei18n/noto-source/blob/master/src/NotoSansHebrew-MM.glyphs
and
https://github.com/googlei18n/noto-source/blob/master/src/NotoSerifHebrew-MM.glyphs

using the following command to build fonts
_for filename in NotoSansHebrew-MM NotoSerifHebrew-MM ; do fontmake  -g src/$filename.glyphs -o otf ttf -i ; done_

I obtained the following fonts (only Regular included here)
[NotoHebrew.zip](https://github.com/googlei18n/fontmake/files/896348/NotoHebrew.zip)

I ran fontdiff just like in the beginning of this bug

Serif font looks good (and this is a change, before it had problems like I described above)

![serif-heb-273](https://cloud.githubusercontent.com/assets/13322623/24707617/a82f5372-1a14-11e7-802c-d9f8c785d4b3.jpeg)

However, Sans font appears to have the same issue (i.e., no change). I'm stopped and cannot seem to make it work. Is it a source problem? A user error? 

Any suggestions? I deleted all of the previous copies of fontmake, ufo2ft and glyphsLib (at least that's what I attempted so I think I have only the right version of the components).

There might be something with the source because Serif now works (and it didn't before although bug doesn't mention this).

**Comment by marekjez86** [comment]
I realized I need to check my hard buzz version.

**Comment by marekjez86** [comment]
Harfbuzz : phone spelling correction intervened

**Comment by punchcutter** [comment]
@marekjez86 As a test I created a new virtual machine (OS X 10.12.4) with absolutely nothing on it. I installed git, cloned noto-source and fontmake, built fontmake and generated the Hebrew Sans and the fonts are identical to what I'm getting already which looks correct. Maybe there's a difference in fontdiff. I'm using dev version on OS X and not seeing the spacing shown above.

**Comment by xiangyexiao** [comment]
all look very promising. thanks for the quick fix. 

@marekjez86 if you could rebuild the sans and serif fonts, we can then update problematic fonts in google.com/get/noto quickly.

**Comment by marekjez86** [comment]
I re-started my environment. Rebuilt the stuff and I cannot reproduce the issue.

**Comment by marekjez86** [comment]
![he-273](https://cloud.githubusercontent.com/assets/13322623/24829809/217ac912-1c79-11e7-8725-7e45b92e2f47.png)
