### ISSUE TITLE
"ValueError: need more than 3 values to unpack" while processing Glyphs_Sapperlot.glyphs

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#28]
I built the pipeline in the evening (PDT) on 2016-02-16.
I used Glyphs_Sapperlot.glyphs from https://github.com/DrTypo/sapperlot and decided to try using it as an input to the pipeline (my mac glyphs.app can export unhinted OTF files from Glyphs_Sapperlot.glyphs).

Note that while https://github.com/googlei18n/fontmake/issues/14 appears to be fixed we get the following error while running the pipeline:

==== building src/Glyphs_Sapperlot.glyphs ====
....
   File "/usr/local/lib/python2.7/dist-packages/fontmake/font_project.py", line 144, in run_from_glyphs
<     self.run_from_ufos(ufos, is_instance=interpolate, **kwargs)
<   File "/usr/local/lib/python2.7/dist-packages/fontmake/font_project.py", line 159, in run_from_ufos
<     self.remove_overlaps(ufo)
<   File "/usr/local/lib/python2.7/dist-packages/fontmake/font_project.py", line 85, in remove_overlaps
<     manager.union(contours, glyph.getPointPen())
<   File "/usr/local/lib/python2.7/dist-packages/booleanOperations/booleanOperationManager.py", line 56, in union
<     return self._performOperation("union", contours, [], outPen)
<   File "/usr/local/lib/python2.7/dist-packages/booleanOperations/booleanOperationManager.py", line 20, in _performOperation
<     subjectInputContours = [InputContour(contour) for contour in subjectContours if contour and len(contour) > 1]
<   File "/usr/local/lib/python2.7/dist-packages/booleanOperations/flatten.py", line 71, in __init__
<     self.segments = _convertPointsToSegments(points)
<   File "/usr/local/lib/python2.7/dist-packages/booleanOperations/flatten.py", line 436, in _convertPointsToSegments
<     willBeReversed=willBeReversed
<   File "/usr/local/lib/python2.7/dist-packages/booleanOperations/flatten.py", line 194, in __init__
<     self.flat = _flattenSegment(pointsToFlatten)
<   File "/usr/local/lib/python2.7/dist-packages/booleanOperations/flatten.py", line 1157, in _flattenSegment
<     onCurve1, offCurve1, offCurve2, onCurve2 = segment
< ValueError: need more than 3 values to unpack

**Comment by behdad** [comment]
@typemytype does booleanOperations support quadratic segments?

**Comment by typemytype** [comment]
BooleanOperations as a nice NotImplementedError https://github.com/typemytype/booleanOperations/blob/master/Lib/booleanOperations/flatten.py#L237
 when trying to perform an operation on a qcurves 

It should not be so difficult to support qcurves...

A wild guess: the input data has somehow a wrong curve type somewhere

**Comment by typemytype** [comment]
FYI: RoboFont does support this: it converts each quadratic segment to cubic, perform an operation and, converts its back

**Comment by marekjez86** [comment]
this bug is gone; I'm not able to reproduce it.
