### ISSUE TITLE
Do not include cmap table with pid=0/eid=3 and name ids with platformID=1, platEncID=0

### ISSUE THREAD

**Issue by jungshik** [googlei18n/fontmake#280]
At least, NotoSansKhmer-VF.ttf has cmap table with pid=0 and eid=3. It also has variation-font related name ids with platformID=1, platEncID=0. 

The former (cmap table) does not increase the file size much (~ 100 bytes) because the actual table is shared with pid=3/eid=1.  However, the latter increases the file size by ~ 4kB. 

fontmake should not include those entries. 

@marekjez86 @behdad @roozbehp

**Comment by jungshik** [comment]
Static instances corresponding to NotoSansKhmer-VF.ttf also have cmap table with PID=0/EID=3.

**Comment by anthrotype** [comment]
About fvar-related name ids with platform 1 platEncID 0:
https://github.com/fonttools/fonttools/issues/683
https://github.com/fonttools/fonttools/issues/756

**Comment by anthrotype** [comment]
the cmap subtables are written by ufo2ft here:

https://github.com/googlei18n/ufo2ft/blob/b2db479a87cdc484c0b50f550478bb7b4983a6a5/Lib/ufo2ft/outlineCompiler.py#L381

I don't think it's worth dropping platform 0 (Unicode) cmap for just a few bytes.

**Comment by jungshik** [comment]
> I don't think it's worth dropping platform 0 (Unicode) cmap for just a few bytes.
I'm aware that the difference is very small because the actual data is shared, but Android wants to drop them anyway. @roozbehp

**Comment by jungshik** [comment]
Thank you for the pointer the fvar-related name ids with PID/EID=1/0 on Mac. It appears that at least for now, PID/EID=1/0 name ids have to be removed when variation fonts are installed on other platforms if they do care about the size reduction. 

@dougfelt

**Comment by jungshik** [comment]
Close for now.
