### ISSUE TITLE
glyphs file input VF 'wght' axis scale not as expected

### ISSUE THREAD

**Issue by davelab6** [googlei18n/fontmake#281]
The font available at fonts.googleapis.com/earlyaccess/nunitovfbeta.css was made by @m4rc1e using fontmake (via https://gist.github.com/m4rc1e/8b9a6e5678c6628eae7e682d4de63220#file-gf_vf-py-L120-L142) the scale of the 'wght' axis is not 100 to 900 as expected, but 50 to 160. 

> <img width="1914" alt="screen shot 2017-04-06 at 11 41 40" src="https://cloud.githubusercontent.com/assets/261579/24748100/e7f350bc-1abe-11e7-8044-bb35b5a9ce4e.png">
>
> https://jsbin.com/lewikin/1/edit?html,output

I guess that is because those are the arbitrary interpolation values used in GlyphsApp which correspond to stem widths in UPM values to make the type designer's mind-arithmetic easier, and GlyphsApp uses for its own interpolation, and exports directly to the font.

**Comment by moyogo** [comment]
This is a duplicate of #167.

**Comment by davelab6** [comment]
Thanks @moyogo :)
