### ISSUE TITLE
maxZones in static TTF files from pipeline has incorrect value 

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#286]
All TTF files we produce have incorrect value for maxZones. This information is reported by ftxvalidator running on Mac

There's just a single error for all files:
maxp: The maxZones field is equal to 1; it should be equal to 2

_ftxvalidator -t all -T \<font-file-name\>_

NotoSerifSinhala-SemiBold.ttf.txt:			maxp: The maxZones field is equal to 1; it should be equal to 2
NotoSerifSinhala-Thin.ttf.txt:			maxp: The maxZones field is equal to 1; it should be equal to 2
NotoSerifThai-Black.ttf.txt:			maxp: The maxZones field is equal to 1; it should be equal to 2
NotoSerifThai-Bold.ttf.txt:			maxp: The maxZones field is equal to 1; it should be equal to 2
NotoSerifThai-Condensed.ttf.txt:			maxp: The maxZones field is equal to 1; it should be equal to 2
NotoSerifThai-CondensedBlack.ttf.txt:			maxp: The maxZones field is equal to 1; it should be equal to 2
NotoSerifThai-CondensedBold.ttf.txt:			maxp: The maxZones field is equal to 1; it should be equal to 2
NotoSerifThai-CondensedExtraBold.ttf.txt:			maxp: The maxZones field is equal to 1; it should be equal to 2
NotoSerifThai-CondensedExtraLight.ttf.txt:			maxp: The maxZones field is equal to 1; it should be equal to 2
NotoSerifThai-CondensedLight.ttf.txt:			maxp: The maxZones field is equal to 1; it should be equal to 2

@brawer : does it have anything to do with hinting?

**Comment by marekjez86** [comment]
There are more related maxp table messages produced by ftxvalidator for each font file:

        com.apple.TrueType.maxp.structure
                ‘maxp’ table structure
                This test ensures the structure of the maximum profile table, ‘maxp’, accords with the specification.
                Minor 
                        maxp: The maxZones field is equal to 1; it should be equal to 2
                                kATSFontTestSeverityMinorError
                        maxp: The table's maximum component depth is 8; it should be 2
                                kATSFontTestSeverityMinorError
                        maxp: The table's maximum component depth is 8; fonts with maximum component depth greater than 1 may not work properly on Mac OS X
                                kATSFontTestSeverityMinorError

**Comment by anthrotype** [comment]
the maxp.maxZones should be equal to 2 if the font is hinted (ttfautohint takes care of setting those), when the font is unhinted, the value can be 1 (in any case, it's ignored).

About the maximum component depth > 1 which may not work properly on OS X, I think that warning is obsolete.

**Comment by brawer** [comment]
The [OpenType spec](https://www.microsoft.com/typography/otspec/maxp.htm) disagrees with [Apple’s spec](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6maxp.html) about the correct value for `maxZones`. The code that sets it to 1 is in [ufo2ft.outlineCompiler](https://github.com/googlei18n/ufo2ft/blob/master/Lib/ufo2ft/outlineCompiler.py#L986).  We follow the OpenType spec, so from that perspective we probably do the right thing today. On the other hand, would there be any harm in always setting it to 2 to make Apple happy?

@lemzwerg, does FreeType care about `maxp.maxZones`?

**Comment by anthrotype** [comment]
It doesn't make any difference if the font has no hinting. The fonttools subsetter sets it to 1 when `--no-hinting` option is passed (which drops the hinting); ttfautohint sets all the maxp values to 0, including maxZones, with the `--dehint` option (see `ttfautohint/src/lib/tamaxp.c`).
It's a non issue.

**Comment by lemzwerg** [comment]
FreeType completely ignores the `maxZones` value.

**Comment by brawer** [comment]
I’ve filed a bug with Apple, asking them if their TrueType spec could perhaps follow OpenType in this (admittedly rather minor) regard. And, in case they do change the spec, if they could perhaps also change ftxvalidator accordingly. Apple radar bug ID 31606020; copied it to [OpenRadar](https://openradar.appspot.com/radar?id=4972933873139712).
