### ISSUE TITLE
Question: how to validate tables in the pipeline generated OTF fonts

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#291]
I have two sample OTF fonts produced from exactly the same sources. One generated by the pipeline and the other provided to us as a reference font. 

Each of these fonts is provided below as an OTF file, ttx  (created from the OTF) file and glyphs file (also created from the OTF for that weight).

[pipeline-NotoSansTamil-Regular.zip](https://github.com/googlei18n/fontmake/files/919484/pipeline-NotoSansTamil-Regular.zip)
[ref-NotoSansTamil-Regular.zip](https://github.com/googlei18n/fontmake/files/919485/ref-NotoSansTamil-Regular.zip)

question for one (or all of) @behdad , @roozbehp , @twardoch , @brawer , @dougfelt , @jungshik, @jamesgk , @anthrotype : how could I validate that 
1. we produce all of the tables that we need to make 
2. all of the tables are correct
What tools could I use for this?

I added the reference file if it would help with the comparisons.

**Comment by anthrotype** [comment]
By correct, do you mean that they are identical or equivalent to the reference font? Or correct in general, e.g. according to the OT spec?

**Comment by brawer** [comment]
@marekjez86, try [fontdiff](https://github.com/googlei18n/fontdiff).

**Comment by marekjez86** [comment]
In this case, I have the reference font. I would like to know if what we produce is  equivalent to the reference font. I do not expect exactly the same as the reference font.

So far, I tried: 
- fontdiff and looked at the results (but it depends on having samples exercising all of the features)
- notodiff -t area 
- notodiff -t rendered
- ftxvalidator -t all -T [single font]
- noto_lint.py  [single font]

Is it sufficient to convince myself that our tables are correct?

**Comment by brawer** [comment]
Sounds reasonable.

**Comment by miguelsousa** [comment]
@marekjez86 you could also try diff'ing `ttxn` dumps of the fonts.

**Comment by behdad** [comment]
I diff'ed the raw ttx dumps.  They are different for obvious reason but much closer than I have had expected.  I like writing a little fontTools module that can diff and account for functionally-equivalent representations...

**Comment by marekjez86** [comment]
@miguelsousa, @behdad  : I generated ttx dumps (not certain what ttxn is). I actually created 3 different dumps per font file: everything, GSUB only dump and GPOS only dump. I did "diff -b" of corresponding files, but I lack of knowledge required for the tables hence I need to learn more to be able to assess the diffs.

**Comment by miguelsousa** [comment]
ttx**n** is a spinoff of ttx that @readroberts developed. It's available in the FDK package. **notodiff** uses it for the GSUB/GPOS diffs. So if you're using notodiff you may have ttxn already installed.
