### ISSUE TITLE
fontmake should set correctly ulCodePageRange (currently not set)

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#304]
for more details please see https://github.com/googlei18n/noto-fonts/issues/902

values in sample fonts created by the fontmake

_NotoSans-Regular.ttx:    \<ulCodePageRange1 value="00000000 00000000 00000000 00000000"/>
NotoSans-Regular.ttx:    \<ulCodePageRange2 value="00000000 00000000 00000000 00000000"/>
NotoSerifThai-Thin.ttx:    \<ulCodePageRange1 value="00000000 00000000 00000000 00000000"/>
NotoSerifThai-Thin.ttx:    \<ulCodePageRange2 value="00000000 00000000 00000000 00000000"/>_

**Comment by anthrotype** [comment]
ufo2ft simply compiles whatever is in the source file; it does not auto-compute the ulUnicodeRange and ulCodePageRange values, because there is no agreement as to how these should be calculated. The OT spec is rather vague:

> The determination of “functional” is left up to the font designer

https://www.microsoft.com/typography/otspec/os2.htm

At DaMa, we set the unicode ranges bit on whenever there is *at least one character* that intersects a range; and we set the codepage bit on when the coverage is >= 98 % of the characters defined in a code page.
These are somewhat arbitrary decisions, and others may make different choices.

We could add a similar functionality to ufo2ft outlineCompiler, if there's enough demand.

**Comment by anthrotype** [comment]
I guess the next question is, how does Glyphs.app decides when to set these flags?
The unicode-to-codepages mappings we can get find in the Python built-in `encodings` module. What I'm asking is which threshold value does Glyphs.app uses to decide when to automatically enable them (if a user did not explicitly define them with a custom parameter)?

 /cc @schriftgestalt

**Comment by marekjez86** [comment]
@anthrotype : "set the unicode ranges bit on whenever there is at least one character that intersects a range; and we set the codepage bit on when the coverage is >= 98 % of the characters defined in a code page." sounds reasonable to me. Where is it done? Is it done manually by the designer in the sources using glyphs.app? Could this be computed, for example, in ufo2ft according to the values mentioned earlier? Looks to me that some MS apps require this.

**Comment by anthrotype** [comment]
fonttools can already recalculate the unicode ranges bit using the "at-least-one" rule, but this is not currently used by ufo2ft:
https://github.com/fonttools/fonttools/blob/dc1a3bd/Lib/fontTools/ttLib/tables/O_S_2f_2.py#L284-L301

As for the codepages, as I said, we do have a script internally that takes the intersection between python's `encodings` tables and a font's Unicode cmap, and calculates "how much" the codepage is covered, and use this to set the respective bits on whenever it is at least 98 %.

We could have ufo2ft automatically do this as a fallback whenever a UFO does not already have user defined values for these bits.
Though I can't make promises as to when I'll be available to work on that, as we are quite busy here at the moment.

**Comment by marekjez86** [comment]
I'd like this automatic whenever a UFO does not already have user defined values for these bits using DaMa heuristic. Whenever, you could do it would be great (no rush).

**Comment by marekjez86** [comment]
@codeman38 : would you have time and skills to make the above described changes under @anthrotype 's guidance?  If you do, then this would guarantee that your request in https://github.com/googlei18n/noto-fonts/issues/902 is fulfilled :-)

**Comment by schriftgestalt** [comment]
> I guess the next question is, how does Glyphs.app decide when to set these flags?

currently that is handled by makeOTF (if not set manually).

**Comment by adrientetar** [comment]
> and use this to set the respective bits on whenever it is at least 98 %.

Back in 2014 there was consensus on at least one in: https://github.com/fonttools/fonttools/pull/181  
I guess it would be interesting to know where makeotf puts the threshold; cc @miguelsousa

**Comment by miguelsousa** [comment]
@readroberts will explain

**Comment by readroberts** [comment]
In makeotfexe, the Unicode page bits are set in the function setOS_2Fields() in FDK/Tools/Programs/makeotf/makeotf_lib/source/hot_conv/map.c. The comment correctly describes the logic:
/* This is a hack. The numEssential field is set for each block in uniblock.h. It is currently
 the number of entries in the range from min UV to max UV of the block.
 This is already not right, as in most blocks, not all UV's in the range are valid.
However, most of these ranges include a lot of archaic and  unusual glyphs not really needed for
useful support of the script. I am going to just say that if at least third of the entry range is included in the font, the designer was making a reasonable effort to support this block */

**Comment by codeman38** [comment]
Out of curiosity, is there any easy way to calculate the coverage for the double-byte CJK code pages using only the built-in libraries? These aren't directly visible in the `encodings` module, and the mappings only seem to be stored as headers inside a C library (https://github.com/python/cpython/tree/2.7/Modules/cjkcodecs) which does not directly expose them to the Python runtime as far as I can tell.

**Comment by anthrotype** [comment]
@codeman38 Right. For those we'd have to parse the CJK codepages to Unicode mappings text files on http://unicode.org/Public/MAPPINGS/ and build the tables. Maybe a MetaTools script inside fontTools that generates python module containing pre-parsed data to speed up the loading.

So, while this could be done (and I'd be happy to review a PR in this direction), I still think that designers should take the responsibility of setting those values themselves, given that the OT spec does not set any specific threshold but leaves it to the the font designer to assess whether they deem a codepage or a unicode range block "functional" or not.

**Comment by anthrotype** [comment]
this feature was added to ufo2ft 2.0, thanks to @khaledhosny
