### ISSUE TITLE
A .designspace document is not accepted by AFDKO’s makeInstancesUFO

### ISSUE THREAD

**Issue by MrBrezina** [googlei18n/fontmake#306]
A .designspace document generated from .glyphs source is refused by makeInstancesUFO as it does not include `postscriptfontname` attribute for each instance. Maybe new AFDKO does not have a problem with that, I have not tried that yet.

**Comment by anthrotype** [comment]
This should be optional, at least according to https://github.com/LettError/designSpaceDocument

> postscriptfontname: string. Optional for MutatorMath.

**Comment by anthrotype** [comment]
glyphsLib >= 1.7.0 does support exporting an instance's `postscriptFontName` custom parameter to the .designspace:
https://github.com/googlei18n/glyphsLib/commit/4fade33cfccd5838f9e756f76ee71df040b95570

**Comment by MrBrezina** [comment]
Are you saying this is fixed also for fontmake or that I can generate a good designspace using glyphsLib >= 1.7.0? (FYI, I am using the latest versions and fontmake is not adding `postscriptFontName` attribute.)

**Comment by MrBrezina** [comment]
I guess, what I am trying to say is that I would expect fontmake to play nice with AFDKO in this respect. :) Or AFDKO to be more flexible.

**Comment by anthrotype** [comment]
Yes, but only when you have a postscriptFontName custom parameter in your instances in the source glyphs file.

**Comment by anthrotype** [comment]
The attribute is optional, and that AFDKO script should not rely on its presence, in my option.

**Comment by brawer** [comment]
Agree — according to the designSpaceDocument spec, `postscriptfontname` is optional. If AFDKO does not work without it, this sounds like a clear bug in AFDKO. Mind reporting it to Adobe? Thanks.

**Comment by MrBrezina** [comment]
Ah. I see and agree. Will do.

**Comment by miguelsousa** [comment]
> Agree — according to the designSpaceDocument spec, postscriptfontname is optional. If AFDKO does not work without it, this sounds like a clear bug in AFDKO.

**makeotf** requires UFOs to have `postscriptFontName` set in order to build OTFs. But I agree that **makeInstancesUFO** should not enforce the presence of `postscriptfontname` in the designspace file in order to generate UFOs.
