### ISSUE TITLE
add command-line option to only interpolate some instances from designspace

### ISSUE THREAD

**Issue by MrBrezina** [googlei18n/fontmake#308]
Is it possible to call fontmake to interpolate and output just one instance from a .designspace? E.g. like with MuMa, with instance’s order in the .designspace.

Also, does it make sense to remove overlaps, decompose composites etc. after interpolating an ufo instance, not only when generating otf/ttf? Sometimes, I would like to play with feature code and keep testing it (i.e. frequently compile ufo instance into otf) and doing the time-expensive remove overlaps and decompose operations make it too slow for that purpose. And even if I use `--keep-overlaps, --keep-direction` there are other operations that slow it down. Maybe there is a better way to test-compile the features?

**Comment by anthrotype** [comment]
> Is it possible to call fontmake to interpolate and output just one instance from a .designspace?

currently no. If you set that instance as "inactive" in the .glyphs source file, then the generated designspace will not contain the instance, and fontmake will not generate it.
If you use a designspace as input, then all the instances are generated.

> E.g. like with MuMa, with instance’s order in the .designspace.

not sure what you mean here.

> does it make sense to remove overlaps, decompose composites etc. after interpolating an ufo 

Maybe.

> Maybe there is a better way to test-compile the features?

you could maybe call `fonttools feaLib` with a TTF and features.fea as inputs.

**Comment by MrBrezina** [comment]
Thanks.

Here:

>> E.g. like with MuMa, with instance’s order in the .designspace.

Sorry, I meant `makeInstancesUFO`’s CLI:

> -i <list of instance indices>
>   Specify the instances to generate. 'i' is a 0-based index of the instance records
>   in the design space file.
>      Example: '-i 1,4,22' -> generates only the 2nd, 5th, and 23rd instances

**Comment by anthrotype** [comment]
I see. Maybe we could overload the current `-i/--interpolate` option in fontmake to optionally take a comma-separated list of indexes (like in `makeInstanceUFO`), or even instance names.

**Comment by anthrotype** [comment]
Fixed by https://github.com/googlei18n/fontmake/pull/410
