### ISSUE TITLE
When compiling TTF from UFO with --use-afdko, mtiFeaFiles attribute is required

### ISSUE THREAD

**Issue by MrBrezina** [googlei18n/fontmake#312]
Why would I need that in the UFO to do this?

Here is the log:

```
Traceback (most recent call last):
  File "/usr/local/bin/fontmake", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/fontmake/__main__.py", line 194, in main
    ufo_paths, is_instance=args.pop('masters_as_instances'), **args)
  File "/usr/local/lib/python2.7/site-packages/fontmake/font_project.py", line 466, in run_from_ufos
    mti_paths=mti_paths, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/fontmake/font_project.py", line 167, in build_ttfs
    self.save_otfs(ufos, ttf=True, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/usr/local/lib/python2.7/site-packages/fontmake/font_project.py", line 271, in save_otfs
    font = compileTTF(ufo, convertCubics=False, **compiler_options)
  File "/usr/local/lib/python2.7/site-packages/ufo2ft/__init__.py", line 67, in compileTTF
    featureCompiler.compile()
  File "/usr/local/lib/python2.7/site-packages/ufo2ft/featureCompiler.py", line 40, in compile
    self.setupFile_featureTables()
  File "/usr/local/lib/python2.7/site-packages/fontmake/font_project.py", line 564, in setupFile_featureTables
    if self.mtiFeaFiles is not None:
AttributeError: 'FDKFeatureCompiler' object has no attribute 'mtiFeaFiles'
```

**Comment by anthrotype** [comment]
It should not be required.
The attribute was added later to the base class in ufo2ft and the subclass in fontmake has not been updated to handle that.
We'll fix it, thanks.

**Comment by anthrotype** [comment]
@MrBrezina can you please try to `git pull` from the latest upstream master, re-installing fontmake from there and see if that fixes it?

**Comment by MrBrezina** [comment]
This is probably on me, but how do I specify the FontMenuDB for fontmake? I know how to do it for AFDKO.

```
makeotfexe [WARNING] Font Menu Name database is not specified or not found .[Avory-Regular]
syntax error at "}" [tmpvXdZ4W 5192]
makeotfexe [FATAL] <Avory-Regular> aborting because of errors
INFO:fontmake.font_project:
makeotf [Note] Converting source font '/var/folders/5p/x2mfgzlj4c92bmdwq_mw58h80000gn/T/tmpv6mewR' to temporary Unix Type1 font file '/var/folders/5p/x2mfgzlj4c92bmdwq_mw58h80000gn/T/tmpv6mewR.tmp'.
makeotf [Warning] Could not find FontMenuNameDB file. Font will be built with menu names derived from PostScript name.
makeotf [Note] Writing options file /var/folders/5p/x2mfgzlj4c92bmdwq_mw58h80000gn/T/current.fpr
makeotf [Note] Running makeotfexe with commands:
   cd "/var/folders/5p/x2mfgzlj4c92bmdwq_mw58h80000gn/T"
   makeotfexe "-f" "tmpv6mewR.tmp" "-o" "tmpY0_Swn.temp_cff" -ff "tmpvXdZ4W" -ga -gf "tmpv6mewR.temp.GOADB" -shw
makeotf [Error] Failed to build output font file 'tmpY0_Swn.temp_cff'.

Traceback (most recent call last):
  File "/usr/local/bin/fontmake", line 11, in <module>
    load_entry_point('fontmake==1.2.4.dev0', 'console_scripts', 'fontmake')()
  File "/usr/local/lib/python2.7/site-packages/fontmake/__main__.py", line 195, in main
    ufo_paths, is_instance=args.pop('masters_as_instances'), **args)
  File "/usr/local/lib/python2.7/site-packages/fontmake/font_project.py", line 481, in run_from_ufos
    **kwargs)
  File "/usr/local/lib/python2.7/site-packages/fontmake/font_project.py", line 193, in build_ttfs
    self.save_otfs(ufos, ttf=True, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/usr/local/lib/python2.7/site-packages/fontmake/font_project.py", line 293, in save_otfs
    font = compileTTF(ufo, convertCubics=False, **compiler_options)
  File "/usr/local/lib/python2.7/site-packages/ufo2ft/__init__.py", line 67, in compileTTF
    featureCompiler.compile()
  File "/usr/local/lib/python2.7/site-packages/ufo2ft/featureCompiler.py", line 40, in compile
    self.setupFile_featureTables()
  File "/usr/local/lib/python2.7/site-packages/fontmake/font_project.py", line 615, in setupFile_featureTables
    os.remove(feasrc_path)
OSError: [Errno 2] No such file or directory: '/var/folders/5p/x2mfgzlj4c92bmdwq_mw58h80000gn/T/tmpY0_Swn'
```

**Comment by anthrotype** [comment]
There is no such a thing for fontmake... If you want to have control on how the name table is built, you have to define your names in the UFO fontinfo.plist
http://unifiedfontobject.org/versions/ufo3/fontinfo.plist/

The `--use-afdko` option was added only to make it easier to compare feaLib vs makeotf as far as the compilation of features.fea into binary GPOS/GSUB/GDEF. It was useful at the beginning, when feaLib was not feature-complete yet.

Basically, what that does is, instead of using fonttools to compile the features (with feaLib), it tells ufo2ft to use makeotf instead, and then injects the makeotf-generated opentype layout tables generated into the OTF or TTF files that are built by ufo2ft. Makeotf is not used for anything else.

You shouldn't really need to use that option, unless you find that that there is a bug or feature which is lacking from feaLib. In which case, please let use know!

**Comment by anthrotype** [comment]
so you can ignore that warning about missing FontMenuDB because it's not needed anyway.
The reason the compilation is failing is

```
syntax error at "}" [tmpvXdZ4W 5192]
makeotfexe [FATAL] <Avory-Regular> aborting because of errors
``

**Comment by MrBrezina** [comment]
ok, thanks, the warning confused me.

Re getting binary GPOS/GSUB/GDEF: yes, that’s what I thought. Based on what @miguelsousa says in #305 it makes sense to use makeotf/AFDKO as it will compile a smaller GPOS table.

**Comment by MrBrezina** [comment]
Also, the syntax error is odd as makeotf from command line can compile the UFO just fine. How can I investigate what’s wrong (e.g. open `tmpvXdZ4W`)

**Comment by anthrotype** [comment]
try to comment out the line `os.remove(fea_path)` which removes the temporary file and see what it is there at line 5192.
I suspect it might be one of the features automatically generated by ufo2ft (kern, mark or mkmk).

**Comment by anthrotype** [comment]
this line
https://github.com/googlei18n/fontmake/blob/c7bbdff/Lib/fontmake/font_project.py#L604

**Comment by MrBrezina** [comment]
I think it is this empty `mkmk` feature:
```
feature mkmk {
} mkmk;
```

**Comment by anthrotype** [comment]
Oh ok.. yes, I once also hit that but then forgot to fix it. It's a ufo2ft issue in the markFeatuerWriter. FeaLib does not complain with empty features blocks, just skips them, whereas makeotf is more picky about them. I can fix that.

**Comment by anthrotype** [comment]
@MrBrezina ok, I fixed the empty mkmk block with https://github.com/googlei18n/ufo2ft/pull/130
Try to `pip install --upgrade ufo2ft` to get the latest version (v0.5.1) and let me know if that fixes it for you, thanks.

**Comment by MrBrezina** [comment]
@anthrotype works, thanks!
