### ISSUE TITLE
fontmake.font_project appears to drop regular (which is OK), italic (which is bad) from the VF file names

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#314]
This is just a gut feeling based on my observations of the results (I'll investigate more). It looks to me that fontmake appears to drop regular, italic (possibly others) from the VF file names. This is correct for regular, but it will cause problems for our Italic font versions.

Why?
Here are our source names:
![sans-glyphs](https://cloud.githubusercontent.com/assets/13322623/25757967/8911e7c8-3181-11e7-80a6-7ad31d6cd6da.jpeg)
![display-glyphs](https://cloud.githubusercontent.com/assets/13322623/25757968/89136d5a-3181-11e7-92eb-027615c89bf7.jpeg)

I expect that for the Italic sources we will get the following results:
NotoSansDisplay-Italic-VF.ttf
NotoSans-Italic-VF.ttf
just like we did in the past
![fontmake-italic](https://cloud.githubusercontent.com/assets/13322623/25758033/cb55d662-3181-11e7-92b1-d73d0fb74712.jpeg)

However, now we only produce NotoSansDisplay-VF.ttf and NotoSans-VF.ttf
From the name I have no idea what this is :-) Most likely the last one out of the two that was compiled :-)

I'll check and update this.

**Comment by marekjez86** [comment]
I checked NotoSansDisplay-VF.ttf and NotoSans-VF.ttf. They are what they need to be. I need to check why NotoSansDisplay-Italic-VF.ttf and NotoSans-Italic-VF.ttf weren't built.

**Comment by marekjez86** [comment]
Mystery solved. It looks like a new behaviour of fontmake.font_project. It looks that NotoSansDisplay-Italic-VF.ttf and NotoSans-Italic-VF.ttf were built first in my pipeline. Here's the log for NotoSansDisplay-Italic-VF.ttf.

![fontmake-italic-issue](https://cloud.githubusercontent.com/assets/13322623/25759352/f8ac724c-3186-11e7-8a2e-68c033a7eb0c.jpeg)

Note "**_Building variable font variable_ttf/NotoSansDisplay-VF.ttf_**" after "**_INFO:fontmake.font_project:Saving TTF for NotoSansDisplay-BoldItalic_**"

**Comment by anthrotype** [comment]
Ouch. It should be an easy one, thanks for spotting.

**Comment by anthrotype** [comment]
Looks like a regression introduced with glyphsLib v1.7.2 from this commit:
https://github.com/googlei18n/glyphsLib/commit/6fcf3b1e4763b2f76b74c5028af9476b1f9fe0e4#diff-e9fd83f9aff129b278b8852b38f72414R89

The designspace file determines the filename of the fontmake-generated VF.ttf. Previously, glyphsLib was saving it with the `base_family` and `base_style`, after that only with `base_family`.

**Comment by anthrotype** [comment]
I'm thinking that glyphsLib could default to use the same base name as the glyphs source file for the name of the generated `*.designspace` file, and hence for the name of the variable font.

E.g. `NotoSans-ItalicMM.glyphs` will produce `master_ufo/NotoSans-ItalicMM.designspace`, and `variable_ttf/NotoSans-ItalicMM-VF.ttf`.

I have a patch locally, I'll clean up and push sometime tomorrow or next week.
