### ISSUE TITLE
Fontmake uses instance coordinates, not master coordinates for defining design space

### ISSUE THREAD

**Issue by robmck-ms** [googlei18n/fontmake#324]
It appears that when fontmake generates the .designspace file, it uses the min/max coordinates of instances, not of masters, to define the axis bounds. This means that if I don't happen to place an instance at the extreme of a range, fontmake will truncate the range.

For example, I have a 2 axis font, with weight min/def/max of 300/400/700, and a width of 75/100/100, with instances at the axes extrema and corners (e.g. wght=700, wdth=75). If I disable all the condensed instances, then the resulting .desginspace file has width 100/100/100 instead of 75/100/100.

```
    <axes>
        <axis default="400" maximum="700" minimum="300" name="weight" tag="wght">
            <map input="300" output="300" />
            <map input="350" output="350" />
            <map input="400" output="400" />
            <map input="600" output="600" />
            <map input="700" output="700" />
            <labelname xml:lang="en">Weight</labelname>
        </axis>
        <axis default="100" maximum="100" minimum="100" name="width" tag="wdth">
            <map input="100" output="100" />
            <labelname xml:lang="en">Width</labelname>
        </axis>
    </axes>

```

If I re-enable the condensed instances, but disable the bold instances, I get a width axis truncated at 600:

```
    <axes>
        <axis default="400" maximum="600" minimum="300" name="weight" tag="wght">
            <map input="300" output="300" />
            <map input="350" output="350" />
            <map input="400" output="400" />
            <map input="600" output="600" />
            <labelname xml:lang="en">Weight</labelname>
        </axis>
        <axis default="100" maximum="100" minimum="75" name="width" tag="wdth">
            <map input="75" output="75" />
            <map input="87.5" output="87.5" />
            <map input="100" output="100" />
            <labelname xml:lang="en">Width</labelname>
        </axis>
    </axes>
```

All of these things mean that varLib hits an assertion error building the variable font. It also means that, for another project I have which has no named instances along one axis, there's no way to build it without inserting dummy instances.

**Comment by robmck-ms** [comment]
Forgot to mention: this is all from Glyphs source files.

**Comment by anthrotype** [comment]
glyphsLib 2.3 supports the `Axes` font custom parameter, and the `Axis Location` master custom parameter. If you add those to your glyphs file, they should be used when generating the designspace axes, instead of the instances' locations.
Feel free to reopen this if it's not the case, thanks.
