### ISSUE TITLE
fontmake/Lib/fontmake/font_project.py : after we started checking for correct names we cannot process directories

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#33]
The font sources can have one of the two formats:
- a glyphs file; for example:
NotoSansGeorgian-MM.glyphs, testNotoSansOlChiki-Regular.glyphs, mzjNotoSansCham-Bold.glyphs,NotoSansHebrew-MM.glyphs  ...
- a directory which contains a glyphs file and all other input files; for example

marekj@yol-worjdp:~/src/noto-source$ ls src/NotoSansDevanagari

Noto Sans Devanagari Black Condensed GPOS.txt  Noto Sans Devanagari Regular GPOS.txt             Noto Sans Devanagari UI Bold GSUB w122-171.txt
Noto Sans Devanagari Black GPOS.txt            Noto Sans Devanagari Regular GSUB w59-121.txt     NotoSansDevanagariUI.cmap.txt
Noto Sans Devanagari Black GSUB w172-190.txt   Noto Sans Devanagari Thin Condensed GPOS.txt      Noto Sans Devanagari UI Condensed GPOS.txt
Noto Sans Devanagari Bold Condensed GPOS.txt   Noto Sans Devanagari Thin GPOS.txt                Noto Sans Devanagari UI GDEF.txt
Noto Sans Devanagari Bold GPOS.txt             Noto Sans Devanagari Thin GSUB w26-58.txt         NotoSansDevanagariUI.plist
Noto Sans Devanagari Bold GSUB w122-171.txt    Noto Sans Devanagari UI Black Condensed GPOS.txt  Noto Sans Devanagari UI Regular GPOS.txt
Noto Sans Devanagari Condensed GPOS.txt        Noto Sans Devanagari UI Black GPOS.txt            Noto Sans Devanagari UI regular GSUB w59-121.txt
Noto Sans Devanagari GDEF.txt                  Noto Sans Devanagari UI Black GSUB w172-190.txt   Noto Sans Devanagari UI Thin Condensed GPOS.txt
NotoSansDevanagari.glyphs                      Noto Sans Devanagari UI Bold Condensed GPOS.txt   Noto Sans Devanagari UI Thin GPOS.txt
NotoSansDevanagari.plist                       Noto Sans Devanagari UI Bold GPOS.txt             Noto Sans Devanagari UI Thin GSUB w26-58.txt

Ever since we introduced checking for the proper names we "lost" the ability to process glyphs that required additional (GSUB, GPOS, GDEF) data.

I finally managed to figure out how to force make to print more information, hence the traceback below:

Making `src/NotoSansDevanagari' due to always-make flag.
Must remake target `src/NotoSansDevanagari'.
bash build.sh build_one src/NotoSansDevanagari
Putting child 0x02020b30 (src/NotoSansDevanagari) PID 28657 on the chain.
Live child 0x02020b30 (src/NotoSansDevanagari) PID 28657 
>> Checking Glyphs source for illegal glyph names
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/fontmake/__main__.py", line 51, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/fontmake/__main__.py", line 39, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/usr/local/lib/python2.7/dist-packages/fontmake/font_project.py", line 129, in run_from_glyphs
    glyphs_source = self.preprocess(glyphs_path)
  File "/usr/local/lib/python2.7/dist-packages/fontmake/font_project.py", line 46, in preprocess
    with open(glyphs_path) as fp:
IOError: [Errno 21] Is a directory: 'src/NotoSansDevanagari'
Reaping losing child 0x02020b30 PID 28657 
make: *** [src/NotoSansDevanagari] Error 1
Removing child 0x02020b30 PID 28657 from chain.

**Comment by brawer** [comment]
Looks like something that @jamesgk can fix. Just to clarify, “all other input files” means Monotype feature files?

**Comment by marekjez86** [comment]
all other input files={*GPOS.txt,*GDEF.txt,*GSUB*}

**Comment by marekjez86** [comment]
A user error (aka mine) because a directory which contains a glyphs file and {\*GPOS.txt,\*GDEF.txt,\*GSUB\*.txt} may contain more than one glyphs file. Each glyphs file might be associated with a subset of {\*GPOS.txt,\*GDEF.txt,\*GSUB\*.txt} files.

A mapping between an instance of a font is contained in the <fontname>.plist file which contains all of the files required to build this font.

The two directories that didn't build were Myanmar related. The didn't build because we had no  <fontname>.plist files there.

Closing the bug.
