### ISSUE TITLE
Missing option to change the output directory

### ISSUE THREAD

**Issue by madig** [googlei18n/fontmake#333]
Would help with e.g. the meson build system that expects things to be generated in the same directory as the source file.

It should probably only change the output directory of the user-requested output. So if you have a multiple master .glyphs file and the user specifies `-o otf`, intermediary steps can litter whatever directory they want, but the final font binaries should be put into the directory the user declared. If the user says `-i -o ufo`, the final UFO instances should be put into said directory.

**Comment by madig** [comment]
I've been digging into fontmake to find a good spot to make the changes. `font.save(path)` is called from `save_otfs()` and `build_variable_font()`, both of which consult `_output_path()` and `_output_dir()` on various occasions, where the former is what's used to write the actual binaries. Why are there two methods for this?

My idea would be to change `_output_path()` to look for a `self.output_dir` variable (instead of modifying all callers) and generating one with `_output_dir()` if it's not available. The argument would have to be passed to FontProject.__init__ and deleted from the args dict so `save_otfs` doesn't trip. Are there more elegant ideas?

**Comment by anthrotype** [comment]
> e.g. the meson build system that expects things to be generated in the same directory as the source file.

not sure about that. According to the meson docs, "one of the main design goals of Meson has been to build all projects _out-of-source_". 

> look for a self.output_dir variable (instead of modifying all callers)

I would prefer if you don't add a self.output_dir attribute.
Currently FontProject objects don't hold any state. It's instance methods have `self` but they could well be turned into class methods, or even disassembled into a set of module-level functions. See https://github.com/googlei18n/fontmake/issues/215

honestly I don't see the urgency of such an output directory option. It's not a big deal if, say, in a build script or Makefile you first create a build directory, cd into it and call fontmake from there, then mv the output files where you like.

**Comment by madig** [comment]
> not sure about that. According to the meson docs, "one of the main design goals of Meson has been to build all projects out-of-source".

Correction: it expects files to be generated in the corresponding out-of-source build directory (read: on the same level).

> honestly I don't see the urgency of such an output directory option. It's not a big deal if, say, in a build script or Makefile you first create a build directory, cd into it and call fontmake from there, then mv the output files where you like.

It's annoying if you deal with build systems because you have to always, up-front write a wrapper to move stuff around. Doing the custom build script for Ubuntu made things _so much_ nicer.

**Comment by anthrotype** [comment]
> it expects files to be generated in the corresponding out-of-source build directory

just change directory to your out-of-source build directory before calling fontmake.

> Doing the custom build script for Ubuntu made things so much nicer.

but for ubuntu there's a simple one-to-one correspondence between a UFO and a generated TTF. With *.glyphs or *.designspace based projects there are multiple master UFOs and instance UFOs to be produced from a single source file.

Let me see if I understand what you want. You'd like an -d/--output-dir option that:
1) creates the new output folder if not there, or just assume it's already there and fails if not?
2) places all temporary _and_ final built artifacts into it, in turn, into subdirs like master_* instance_*? Or only the final products?

Why is it not OK to do this?

```sh
$ mkdir -p build
$ cd build
$ fontmake -g ../src/MyFont.glyphs -i -o ttf
# do what you want with *.ttf files in build/instance_ttf directory
```

**Comment by madig** [comment]
> just change directory to your out-of-source build directory before calling fontmake.

That's what meson does. It just expects the result of mangling `src/file.ufo` to be `build/result1`, `build/result2`, ...

> there are multiple master UFOs and instance UFOs to be produced from a single source file.

That's why I want a --output-DIR parameter, which is applicable to single and multiple masters.

1. It should create the output folders unless they already exist.
2. It should only put the final binaries into it. The rest can be ignored by git and the build system. Bonus points for an option to not write any intermediary files to disk.

The problem is currently that the build system has to implement some logic to _find the actual directory with the final build artifacts_ in a input-file-agnostic way and that logic probably has be be revisited if fontmake decides to change output directories. In the same annoying way you had to reliably guess the filename of a generated binary (or replicate the logic by copy-pasting from the fontmake source) before fontmake decided to just use the input filename(?). If you have multiple processes building stuff, as you should, and writing to the same directory, tricks like ls'ing and looking at timestamps are a joke at best.

You must know source and target files beforehand and be able to easily and reliably guess what the output is and where, regardless of input. Everything else makes fontmake painful and error-prone to use in a build system context.

**Comment by anthrotype** [comment]
I'd be happy to review a PR, thanks :)
