### ISSUE TITLE
Messed up weight declarations when compiling .glyphs file

### ISSUE THREAD

**Issue by madig** [googlei18n/fontmake#338]
The weight name and weight declaration in the OS/2 header differ when compiled by Glyphs (really the AFDKO?) and fontmake. This completely confuses fontconfig.

1. Load [Cantarell.zip](https://github.com/googlei18n/fontmake/files/1185527/Cantarell.zip)
2. Compile in Glyphs and then with `fontmake -g Canturell.glyphs -i -o otf`

Glyphs (file, weight name, weight declaration in OS/2 header):
thin: Thin, 250 (should be 100?)
light: Light, 300
regular: Regular, 400
bold: Bold, 700
black: Black, 900

fontmake:
thin: Light, 300
light: Normal, 351
regular: Medium, 467
bold: Semi-Bold, 600
black: Bold, 700

**Comment by anthrotype** [comment]
@madig thanks for the report.
Yes, this is a know incosistency between fontmake (actually glyphsLib) and Glyphs.app

https://github.com/googlei18n/glyphsLib/issues/139#issuecomment-297962171
https://github.com/googlei18n/fontmake/issues/307#issuecomment-297439423

For the time being, to make them agree with each other, you need to explicitly set a `weightClass` custom parameter for each instance, even when the implied value (i.e. from selecting one of the predefined weights in the drop down menu) which Glyphs.app uses, is the one you actually want to use.

**Comment by anthrotype** [comment]
@madig this is fixed in glyphsLib master, will be in next release.
