### ISSUE TITLE
KeyError: ('uni201D', 'ClassDef') when compiling https://github.com/googlei18n/noto-source/tree/master/src/NotoSerifSinhala

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#342]
KeyError: ('uni201D', 'ClassDef') when compiling https://github.com/googlei18n/noto-source/tree/master/src/NotoSerifSinhala

Source error? User error?

```i
===================
fragment of the log
===================
```
INFO:fontmake.font_project:Converting curves for NotoSansDisplay-ExtraCondensedExtraBold
INFO:cu2qu.ufo:New spline lengths:
1: 2210
2: 6601
3: 903
4: 215
5: 36
6: 2

INFO:fontmake.font_project:Converting curves for NotoSansDisplay-ExtraCondensedBlack
INFO:cu2qu.ufo:New spline lengths:
1: 2116
2: 6533
3: 1026
4: 240
5: 36
6: 2

INFO:fontmake.font_project:Saving TTF for NotoSansDisplay-Thin
INFO:fontmake.font_project:Saving TTF for NotoSansDisplay-ExtraLight
INFO:fontmake.font_project:Saving TTF for NotoSansDisplay-Light
INFO:fontmake.font_project:Saving TTF for NotoSansDisplay-Regular
INFO:fontmake.font_project:Saving TTF for NotoSansDisplay-Medium
INFO:fontmake.font_project:Saving TTF for NotoSansDisplay-SemiBold
INFO:fontmake.font_project:Saving TTF for NotoSansDisplay-Bold
INFO:fontmake.font_project:Saving TTF for NotoSansDisplay-ExtraBold
INFO:fontmake.font_project:Saving TTF for NotoSansDisplay-Black
INFO:fontmake.font_project:Saving TTF for NotoSansDisplay-SemiCondensedThin
INFO:fontmake.font_project:Saving TTF for NotoSansDisplay-SemiCondensedExtraLight
INFO:fontmake.font_project:Saving TTF for NotoSansDisplay-SemiCondensedLight
INFO:fontmake.font_project:Saving TTF for NotoSansDisplay-SemiCondensed
INFO:fontmake.font_project:Saving TTF for NotoSansDisplay-SemiCondensedMedium
INFO:fontmake.font_project:Saving TTF for NotoSansDisplay-SemiCondensedSemiBold
INFO:fontmake.font_project:Saving TTF for NotoSansDisplay-SemiCondensedBold
INFO:fontmake.font_project:Saving TTF for NotoSansDisplay-SemiCondensedExtraBold
INFO:fontmake.font_project:Saving TTF for NotoSansDisplay-SemiCondensedBlack
INFO:fontmake.font_project:Saving TTF for NotoSansDisplay-CondensedThin
INFO:fontmake.font_project:Saving TTF for NotoSansDisplay-CondensedExtraLight
INFO:fontmake.font_project:Saving TTF for NotoSansDisplay-CondensedLight
INFO:fontmake.font_project:Saving TTF for NotoSansDisplay-Condensed
INFO:fontmake.font_project:Saving TTF for NotoSansDisplay-CondensedMedium
INFO:fontmake.font_project:Saving TTF for NotoSansDisplay-CondensedSemiBold
INFO:fontmake.font_project:Saving TTF for NotoSansDisplay-CondensedBold
INFO:fontmake.font_project:Saving TTF for NotoSansDisplay-CondensedExtraBold
INFO:fontmake.font_project:Saving TTF for NotoSansDisplay-CondensedBlack
INFO:fontmake.font_project:Saving TTF for NotoSansDisplay-ExtraCondensedThin
INFO:fontmake.font_project:Saving TTF for NotoSansDisplay-ExtraCondensedExtraLight
INFO:fontmake.font_project:Saving TTF for NotoSansDisplay-ExtraCondensedLight
INFO:fontmake.font_project:Saving TTF for NotoSansDisplay-ExtraCondensed
INFO:fontmake.font_project:Saving TTF for NotoSansDisplay-ExtraCondensedMedium
INFO:fontmake.font_project:Saving TTF for NotoSansDisplay-ExtraCondensedSemiBold
INFO:fontmake.font_project:Saving TTF for NotoSansDisplay-ExtraCondensedBold
INFO:fontmake.font_project:Saving TTF for NotoSansDisplay-ExtraCondensedExtraBold
INFO:fontmake.font_project:Saving TTF for NotoSansDisplay-ExtraCondensedBlack
============= src/NotoSerifSinhala/NotoSerifSinhala-MM.plist ==============
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib:Parsing .glyphs file
INFO:glyphsLib:Casting parsed values
INFO:glyphsLib:Loading to UFOs
INFO:glyphsLib.util:Writing master_ufo/NotoSerifSinhala-Light.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSerifSinhala-Regular.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSerifSinhala-Bold.ufo
INFO:fontmake.font_project:Building OTFs
INFO:fontmake.font_project:Decomposing glyphs for NotoSerifSinhala-Regular
INFO:fontmake.font_project:Decomposing glyphs for NotoSerifSinhala-Light
INFO:fontmake.font_project:Decomposing glyphs for NotoSerifSinhala-Bold
INFO:fontmake.font_project:Removing overlaps for NotoSerifSinhala-Regular
INFO:fontmake.font_project:Removing overlaps for NotoSerifSinhala-Light
INFO:fontmake.font_project:Removing overlaps for NotoSerifSinhala-Bold
INFO:fontmake.font_project:Saving OTF for NotoSerifSinhala-Regular
INFO:fontmake.font_project:Saving OTF for NotoSerifSinhala-Light
INFO:fontmake.font_project:Saving OTF for NotoSerifSinhala-Bold
INFO:fontmake.font_project:Building TTFs
INFO:fontmake.font_project:Decomposing glyphs for NotoSerifSinhala-Regular
INFO:fontmake.font_project:Decomposing glyphs for NotoSerifSinhala-Light
INFO:fontmake.font_project:Decomposing glyphs for NotoSerifSinhala-Bold
INFO:fontmake.font_project:Removing overlaps for NotoSerifSinhala-Regular
INFO:fontmake.font_project:Removing overlaps for NotoSerifSinhala-Light
INFO:fontmake.font_project:Removing overlaps for NotoSerifSinhala-Bold
INFO:fontmake.font_project:Converting curves for NotoSerifSinhala-Regular
INFO:cu2qu.ufo:New spline lengths:
1: 2669
2: 11250
3: 2596
4: 735
5: 20

INFO:fontmake.font_project:Converting curves for NotoSerifSinhala-Light
INFO:cu2qu.ufo:New spline lengths:
1: 2460
2: 11177
3: 3208
4: 714
5: 7

INFO:fontmake.font_project:Converting curves for NotoSerifSinhala-Bold
INFO:cu2qu.ufo:New spline lengths:
1: 2973
2: 11066
3: 2204
4: 633
5: 40

INFO:fontmake.font_project:Saving TTF for NotoSerifSinhala-Regular
INFO:fontmake.font_project:Saving TTF for NotoSerifSinhala-Light
INFO:fontmake.font_project:Saving TTF for NotoSerifSinhala-Bold
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib:Parsing .glyphs file
INFO:glyphsLib:Casting parsed values
INFO:glyphsLib:Loading to UFOs
INFO:glyphsLib.util:Writing master_ufo/NotoSerifSinhala-Light.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSerifSinhala-Regular.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSerifSinhala-Bold.ufo
INFO:fontmake.font_project:Interpolating master UFOs from designspace
INFO:mutatorMath:Reading master_ufo/NotoSerifSinhala.designspace
INFO:mutatorMath:	Generating instance NotoSerifSinhala-Thin.ufo
INFO:mutatorMath:	Generating instance NotoSerifSinhala-ExtraLight.ufo
INFO:mutatorMath:	Generating instance NotoSerifSinhala-Light.ufo
INFO:mutatorMath:	Generating instance NotoSerifSinhala-Regular.ufo
INFO:mutatorMath:	Generating instance NotoSerifSinhala-Medium.ufo
INFO:mutatorMath:	Generating instance NotoSerifSinhala-SemiBold.ufo
INFO:mutatorMath:	Generating instance NotoSerifSinhala-Bold.ufo
INFO:mutatorMath:	Generating instance NotoSerifSinhala-ExtraBold.ufo
INFO:mutatorMath:	Generating instance NotoSerifSinhala-Black.ufo
INFO:fontmake.font_project:Building OTFs
INFO:fontmake.font_project:Decomposing glyphs for NotoSerifSinhala-Thin
INFO:fontmake.font_project:Decomposing glyphs for NotoSerifSinhala-ExtraLight
INFO:fontmake.font_project:Decomposing glyphs for NotoSerifSinhala-Light
INFO:fontmake.font_project:Decomposing glyphs for NotoSerifSinhala-Regular
INFO:fontmake.font_project:Decomposing glyphs for NotoSerifSinhala-Medium
INFO:fontmake.font_project:Decomposing glyphs for NotoSerifSinhala-SemiBold
INFO:fontmake.font_project:Decomposing glyphs for NotoSerifSinhala-Bold
INFO:fontmake.font_project:Decomposing glyphs for NotoSerifSinhala-ExtraBold
INFO:fontmake.font_project:Decomposing glyphs for NotoSerifSinhala-Black
INFO:fontmake.font_project:Removing overlaps for NotoSerifSinhala-Thin
INFO:fontmake.font_project:Removing overlaps for NotoSerifSinhala-ExtraLight
INFO:fontmake.font_project:Removing overlaps for NotoSerifSinhala-Light
INFO:fontmake.font_project:Removing overlaps for NotoSerifSinhala-Regular
INFO:fontmake.font_project:Removing overlaps for NotoSerifSinhala-Medium
INFO:fontmake.font_project:Removing overlaps for NotoSerifSinhala-SemiBold
INFO:fontmake.font_project:Removing overlaps for NotoSerifSinhala-Bold
INFO:fontmake.font_project:Removing overlaps for NotoSerifSinhala-ExtraBold
INFO:fontmake.font_project:Removing overlaps for NotoSerifSinhala-Black
INFO:fontmake.font_project:Saving OTF for NotoSerifSinhala-Thin
INFO:fontTools.varLib:Axes:
OrderedDict([('weight', {'map': {800.0: 175.0, 100.0: 28.0, 200.0: 42.0, 300.0: 64.0, 400.0: 94.0, 500.0: 110.0, 600.0: 130.0, 900.0: 194.0, 700.0: 152.0}, 'name': 'weight', 'default': 400.0, 'tag': 'wght', 'maximum': 900.0, 'minimum': 100.0, 'labelname': {'en': 'Weight'}})])
INFO:fontTools.varLib:Internal master locations:
[{'weight': 28.0}, {'weight': 94.0}, {'weight': 194.0}]
INFO:fontTools.varLib:Internal axis supports:
{'weight': [28.0, 94.0, 194.0]}
INFO:fontTools.varLib:Normalized master locations:
[{'weight': -1.0}, {'weight': 0.0}, {'weight': 1.0}]
INFO:fontTools.varLib:Index of base master: 1
INFO:fontTools.varLib.interpolate_layout:Building interpolated font
INFO:fontTools.varLib.interpolate_layout:Loading master fonts
INFO:fontTools.varLib.interpolate_layout:Location: {'weight': 28.0}
INFO:fontTools.varLib.interpolate_layout:Internal location: {'weight': 28.0}
INFO:fontTools.varLib.interpolate_layout:Normalized location: {'weight': -1.0}
INFO:fontTools.varLib.interpolate_layout:Building interpolated tables
Traceback (most recent call last):
  File "/usr/local/bin/fontmake", line 11, in <module>
    load_entry_point('fontmake', 'console_scripts', 'fontmake')()
  File "/Users/marekj/newrel/fontmake/Lib/fontmake/__main__.py", line 183, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/Users/marekj/newrel/fontmake/Lib/fontmake/font_project.py", line 378, in run_from_glyphs
    designspace_path, instance_data=instance_data, **kwargs)
  File "/Users/marekj/newrel/fontmake/Lib/fontmake/font_project.py", line 434, in run_from_designspace
    interpolate_layout_from=interpolate_layout_from, **kwargs)
  File "/Users/marekj/newrel/fontmake/Lib/fontmake/font_project.py", line 473, in run_from_ufos
    ufos, remove_overlaps, **kwargs)
  File "/Users/marekj/newrel/fontmake/Lib/fontmake/font_project.py", line 175, in build_otfs
    self.save_otfs(ufos, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/Users/marekj/newrel/fontmake/Lib/fontmake/font_project.py", line 307, in save_otfs
    font.save(otf_path)
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttLib/__init__.py", line 219, in save
    self._writeTable(tag, writer, done)
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttLib/__init__.py", line 658, in _writeTable
    tabledata = self.getTableData(tag)
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttLib/__init__.py", line 669, in getTableData
    return self.tables[tag].compile(self)
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 70, in compile
    self.table.compile(writer, font)
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 690, in compile
    conv.write(writer, font, table, value)
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otConverters.py", line 449, in write
    value.compile(subWriter, font)
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 632, in compile
    table = self.preWrite(font)
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otTables.py", line 449, in preWrite
    ranges = self._getClassRanges(font)
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otTables.py", line 431, in _getClassRanges
    items.append((getGlyphID(glyphName), glyphName, cls))
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttLib/__init__.py", line 628, in getGlyphID
    glyphID = d[glyphName]
KeyError: ('uni201D', 'ClassDef')

**Comment by anthrotype** [comment]
I cannot reproduce. If I git pull the latest `noto-source ` and run this

```
./build src/NotoSerifSinhala/NotoSerifSinhala-MM.plist
```

to build the Noto Serif Sinhala fonts, the build completes without the error.

**Comment by anthrotype** [comment]
cannot repo, pls retry with fontmake 1.3.0 and reopen if needed.
