### ISSUE TITLE
Missing typographic names

### ISSUE THREAD

**Issue by brawer** [googlei18n/fontmake#35]
Is it intentional that only one of the emitted instances has “typographic” names?

To reproduce:
```
$ git clone https://github.com/Microsoft/Selawik.git
$ fontmake -g Selawik/Source\ files/Glyphs/selawik.glyphs 
$ for STYLE in Light Regular Bold ; do ttx -t name -o - master_ttf/Selawik-$STYLE.ttf ; done
```

As expected, Selawik-Light has typographic family and style names:
```xml
    <namerecord nameID="16" platformID="3" platEncID="1" langID="0x409">
      Selawik
    </namerecord>
    <namerecord nameID="17" platformID="3" platEncID="1" langID="0x409">
      Light
    </namerecord>
```

However, the Regular and Bold fonts currently do not have any typographic names.

**Comment by davelab6** [comment]
>  the Regular and Bold fonts currently do not have any typographic names.

That is correct, because they would be identical to the IDs 1 and 2

**Comment by brawer** [comment]
Ah, got it — thanks.
