### ISSUE TITLE
Naming of the master fonts

### ISSUE THREAD

**Issue by yarmola** [googlei18n/fontmake#353]
I hit one small issue while trying to **fontmake -o variable** over **.designspace** document.

It looks that **fontmake** will generate file names for master fonts while converting from .ufo to .ttf (calling **_font_name** method in **save_otfs**) while **varLib** expects .ttf files to have the same name as source .ufo.

No problem to change naming convention for UFOs (in designspace package), but I have a feeling that it should be improved, so varLib will get the file names from **save_otfs**.

**Comment by moyogo** [comment]
Fontmake should do the right thing and use the names defined in the designspace instead of making them up everytime.

**Comment by anthrotype** [comment]
Thanks Denis for the patch, and also thanks Yuri for trying out fontmake!
