### ISSUE TITLE
build error or source error or my setup problem or as expected?

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#371]
I took delivery of https://github.com/googlei18n/noto-source/tree/master/src/NotoSansBalinese
and built a font from source using 
 _./build src/NotoSansBalinese/NotoSansBalinese-MM.plist_
command and obtained the following ttf

[NotoSansBalinese-Regular.ttf.zip](https://github.com/googlei18n/fontmake/files/1449110/NotoSansBalinese-Regular.ttf.zip)

I ran it through noto_lint.py and the following errors appeared (fragment of the list):
_E <bounds/glyph/ymax> Real yMax for glyph 267 (g178) is 2162, which is higher than the font's sTypoAscent (1069), resulting in clipping.
E <bounds/glyph/ymin> Real yMin for glyph 267 (g178) is -1118, which is lower than the font's sTypoDescent (-726), resulting in clipping.
E <bounds/glyph/ymax> Real yMax for glyph 268 (g179) is 1118, which is higher than the font's sTypoAscent (1069), resulting in clipping.
E <bounds/glyph/ymin> Real yMin for glyph 268 (g179) is -1118, which is lower than the font's sTypoDescent (-726), resulting in clipping.
E <bounds/glyph/ymax> Real yMax for glyph 269 (g180) is 2162, which is higher than the font's sTypoAscent (1069), resulting in clipping.
E <bounds/glyph/ymin> Real yMin for glyph 269 (g180) is -1118, which is lower than the font's sTypoDescent (-726), resulting in clipping.
E <bounds/glyph/ymax> Real yMax for glyph 270 (g181) is 1570, which is higher than the font's sTypoAscent (1069), resulting in clipping.
E <bounds/glyph/ymax> Real yMax for glyph 272 (zerowidthjoiner) is 1667, which is higher than the font's sTypoAscent (1069), resulting in clipping.
E <bounds/glyph/ymax> Real yMax for glyph 273 (zerowidthnonjoiner) is 1667, which is higher than the font's sTypoAscent (1069), resulting in clipping.
E <bounds/font/ymax> Real yMax 2162, but it should be less than or equal to the value of Ascent in 'hhea' table, which is 1069.
E <bounds/font/ymin> Real yMin is -1486, but it should be greater than or equal to the value of Descent in 'hhea' table, which is -726._

I looked at the ttf using glyphs and glyphs starting with g129 look outsized when compared to the uni* glyphs.
![notosansbalinese-mm_20171106](https://user-images.githubusercontent.com/13322623/32482981-abe497a8-c35f-11e7-8e8b-82aad787be9c.jpeg)

Is it build error or source error or my setup problem or as expected?

**Comment by marekjez86** [comment]
it was my build setup problem

**Comment by anthrotype** [comment]
Phew! :sweat_smile:
