### ISSUE TITLE
Make font build deterministic

### ISSUE THREAD

**Issue by madig** [googlei18n/fontmake#379]
Running fontmake multiple times on the same input always results in different SHA256 sums for the resulting binaries. It probably encodes the date or something in there. I'd like to get deterministic results instead.

**Comment by anthrotype** [comment]
Try setting SOURCE_DATE_EPOCH, fontTools should pick it up
https://github.com/fonttools/fonttools/blob/2e4b1d05df2d720bc1f4ba03b6dacb9171116ee1/Tests/misc/timeTools_test.py#L15

**Comment by madig** [comment]
That still results in this diff:
```
--- ur.ttx	2018-01-06 11:03:08.178497404 +0100
+++ ur2.ttx	2018-01-06 11:03:14.352472468 +0100
@@ -1271,15 +1271,15 @@
 
   <head>
     <!-- Most of this table will be recalculated by the compiler -->
     <tableVersion value="1.0"/>
     <fontRevision value="0.83"/>
-    <checkSumAdjustment value="0x4a909d5"/>
+    <checkSumAdjustment value="0x4a9099d"/>
     <magicNumber value="0x5f0f3cf5"/>
     <flags value="00000000 00011011"/>
     <unitsPerEm value="1000"/>
-    <created value="Sat Jan  6 10:00:32 2018"/>
+    <created value="Sat Jan  6 10:01:00 2018"/>
     <modified value="Thu Dec 28 18:19:42 2017"/>
     <xMin value="-167"/>
     <yMin value="-189"/>
     <xMax value="3480"/>
     <yMax value="962"/>
```
(Both files are the result of running `python tools/build.py source/Ubuntu-R.ufo/ /tmp/ur[2].ttf` in the Ubuntu font repo. with SOURCE_DATE_EPOCH set to 1514485182)

**Comment by sladen** [comment]
Presumably `<modified>` *is* being set from `$SOURCE_DATE_EPOCH`, but not `<created>` ?

**Comment by khaledhosny** [comment]
The UFOs do not have `openTypeHeadCreated` set, so ufo2ft fallbacks to the current time. Currently setting `SOURCE_DATE_EPOCH` has no effect in this.

**Comment by madig** [comment]
how about setting both with SOURCE_DATE_EPOCH?

**Comment by sladen** [comment]
@khaledhosny: groovy.  What types of patch would likely to be acceptable.  Ideally the "fall back" would be to `$SOURCE_DATE_EPOCH` if not present?

**Comment by anthrotype** [comment]
What Paul suggested sounds good to me. ufo2ft should set it to SOURCE_DATE_EPOCH if the openTypeHeadCreated isn’t set, or to the current time if neither is set.

**Comment by madig** [comment]
Closed by https://github.com/googlei18n/ufo2ft/pull/199.

**Comment by anthrotype** [comment]
let's close this after new ufo2ft with patch is released and fontmake requirements updated

**Comment by anthrotype** [comment]
font builds are now deterministic if you set the `SOURCE_DATE_EPOCH` environment variable. ufo2ft takes care of it.
https://reproducible-builds.org/specs/source-date-epoch/

**Comment by chrissimpkins** [comment]
@madig This is how we approached this issue as of the fontmake v1.5 release through shell scripting and our fontTools-based post-compile Python scripts.  This fontmake/ufo2ft release got us to fully reproducible builds at every git commit using git commit Unix timestamps.

https://github.com/source-foundry/Hack/issues/401#issuecomment-397102332
