### ISSUE TITLE
handling of "keep glyphs" parameter

### ISSUE THREAD

**Issue by schriftgestalt** [googlei18n/fontmake#381]
https://github.com/googlei18n/fontmake/blob/6cdf44ea38d17f9bb14fa65c1c9bc6ea82e3b89b/Lib/fontmake/font_project.py#L326-L329

This is indeed wrong. `keep_glyphs` is always true. 
I would so something like:
```
keep_glyphs_list = ufo.lib.get(GLYPHS_PREFIX + 'Keep Glyphs', None)
if keep_glyphs_list is not None:
    keep_glyphs = set(keep_glyphs_list)
else:
    keep_glyphs = None
```
and in the loop:
```
if keep_glyphs:
    if old_name not in keep_glyphs:
        continue
elif not glyph.lib.get(GLYPHS_PREFIX + 'Glyphs.Export', True):
   continue
```
(written in Safari)

**Comment by anthrotype** [comment]
thanks Georg, will do

**Comment by anthrotype** [comment]
for reference https://github.com/googlei18n/glyphsLib/issues/295
