### ISSUE TITLE
[QUESTION] Writing abvm and blwm features

### ISSUE THREAD

**Issue by pathumego** [googlei18n/fontmake#391]
Dose Fontmake write `abvm` and `blwm` features using the anchor data? What should I include in a UFO or features.fea for it to do this? Or do I need to use my own `--mark-writer-module` for this?

**Comment by anthrotype** [comment]
Hi Pathum. Not yet, but I plan to add support for it soon.
We are tracking the issue here https://github.com/googlei18n/ufo2ft/issues/179

**Comment by pathumego** [comment]
Awesome thanks @anthrotype. 
cc @paarandika
