### ISSUE TITLE
No output file when appending slash to UFO source input file

### ISSUE THREAD

**Issue by madig** [googlei18n/fontmake#393]
1. Unpack [Test_Lt.zip](https://github.com/googlei18n/fontmake/files/1670529/Test_Lt.zip)
2. `fontmake -u Test_Lt.ufo/`
3. `ls master_*`
4. `fontmake -u Test_Lt.ufo`
5. `ls master_*`

**Comment by anthrotype** [comment]
Fixed, thanks!
