### ISSUE TITLE
Can't install FontMake

### ISSUE THREAD

**Issue by etunni** [googlei18n/fontmake#395]
**This is the output message at terminal**
Last login: Tue Jan 30 18:41:18 on ttys000
Eduardos-iMac:~ etunni$ pip install fontmake
Collecting fontmake
  Using cached fontmake-1.4.0-py2.py3-none-any.whl
Collecting fonttools>=3.21.2 (from fontmake)
  Using cached fonttools-3.21.2-py2.py3-none-any.whl
Collecting MutatorMath>=2.1.0 (from fontmake)
  Using cached MutatorMath-2.1.0-py2.py3-none-any.whl
Collecting cu2qu>=1.3.0 (from fontmake)
  Using cached cu2qu-1.4.0-py2.py3-none-any.whl
Collecting glyphsLib>=2.2.1 (from fontmake)
  Using cached glyphsLib-2.2.1-py2.py3-none-any.whl
Collecting defcon>=0.3.5 (from fontmake)
  Using cached defcon-0.3.5-py2.py3-none-any.whl
Collecting ufo2ft>=1.1.0 (from fontmake)
  Using cached ufo2ft-1.1.0-py2.py3-none-any.whl
Collecting booleanOperations>=0.8.0 (from fontmake)
  Using cached booleanOperations-0.8.0-py2.py3-none-any.whl
Collecting ufoLib>=2.0.0 (from MutatorMath>=2.1.0->fontmake)
  Using cached ufoLib-2.1.1-py2.py3-none-any.whl
Collecting fontMath>=0.4.4 (from MutatorMath>=2.1.0->fontmake)
  Using cached fontMath-0.4.4-py2.py3-none-any.whl
Collecting compreffor>=0.4.5 (from ufo2ft>=1.1.0->fontmake)
  Using cached compreffor-0.4.6-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting pyclipper>=1.0.5 (from booleanOperations>=0.8.0->fontmake)
  Using cached pyclipper-1.1.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Installing collected packages: fonttools, ufoLib, fontMath, defcon, MutatorMath, cu2qu, glyphsLib, pyclipper, booleanOperations, compreffor, ufo2ft, fontmake
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/wheel.py", line 323, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/fontTools/__init__.py'
Eduardos-iMac:~ etunni$

**Comment by davelab6** [comment]
Try this:

    python -m virtualenv env;
    source env/bin/activate;
    pip install fontmake;

**Comment by anthrotype** [comment]
@etunni the pip command you're using is probably linked with the Apple system python, and you're attempting to install fontmake globally to the system python's site folders. You either need to use `sudo pip install ...` (but I do not recommend it as it could mess up with the system python's setup), or you `pip install --user ...` so you don't need admin rights and the packages will be available globally but for your user only, or as @davelab6 suggested use a virtual environment.   

Please refer to https://packaging.python.org/tutorials/installing-packages/ for more info on pip, virtualenv, etc.

**Comment by davelab6** [comment]
This is probably the best thing, @etunni 

    pip install --user fontmake

**Comment by anthrotype** [comment]
No problem. Note that `pip install --user ...` will install the console scripts to a directory which is not usually in the `PATH` environment variable so calling `fontmake` from the Terminal might not work, until you configure your shell to include that directory in the PATH variable where executables are searched.
I don't remember where exactly that folder is located on a Mac, maybe Dave can check on his. It should be some "bin" directory next to the corresponding "lib" folder. On linux it's usually "~/.local/bin". 

Try to run `python -m site` and get the value of `USER_BASE` that's printed, then add a `bin` to it. That's the directory where the scripts are installed when you `pip install --user`.

Btw, this should all be explained in the python docs I linked above.

**Comment by anthrotype** [comment]
even without modifying the bash profile, I think doing `python -m fontmake` should work after pip installing as `--user`, though it's more verbose

**Comment by chrissimpkins** [comment]
@etunni Here's what I get for USER_BASE in Py2 + Py3 on macOS 10.12.6

```
# Python 2.7

/Users/[user]/Library/Python/2.7

# Python 3.6

/Users/[user]/Library/Python/3.6
```

where [user] = my user name

**Comment by anthrotype** [comment]
Right. So you could add a line such as this to your `~/.bash_profile`

```
export PATH="/Users/$USER/Library/Python/2.7/bin:/Users/$USER/Library/3.6/bin:$PATH" 
```

**Comment by chrissimpkins** [comment]
And for any Windows users out there who might need it, here is USER_BASE on Win 10 with Py3:

```
C:\\Users\\[user]\\AppData\\Roaming\\Python
```

Ubuntu on Win10 (bash shell) uses the same Linux path that Cosimo posted above:

```
/home/[user]/.local'
```

**Comment by anthrotype** [comment]
Note that for Windows there is no 'bin' folder, under the user base, it's actually called "Scripts" with the uppercase S
