### ISSUE TITLE
Error from axis-praxis.org:  version 1.0 of STAT table is deprecated

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#417]
When you drop a variable font on https://www.axis-praxis.org/ and click on (i) button next to the font name, it performs some amount of validation.

I checked it on NotoSansMono-VF.ttf and it generated one error that version 1.0 of STAT table is deprecated. Could we fix it?

![statv1-deprecated](https://user-images.githubusercontent.com/13322623/38767734-5a386826-3fe7-11e8-9fac-186d2aa61611.jpeg)

**Comment by anthrotype** [comment]
@marekjez86 the warning will disappear once a new fonttools is released (sometime this week)

**Comment by marekjez86** [comment]
@anthrotype : thanks
