### ISSUE TITLE
PDF embedding not working for fonts made via macOS 10.13 Print dialog

### ISSUE THREAD

**Issue by MrBrezina** [googlei18n/fontmake#424]
We have custom and retail fonts produced using fontmake which exhibit this issue. When on macOS 10.13.3+ if you create a PDF using the Print dialog > Save as PDF (e.g. from TextEdit) and then open this PDF with Adobe Acrobat, the fonts are cannot be found.

We started getting reports about this issue this year, so it might have appeared with some of the recent versions of fontmake.

After some experiments, I think the issue is in CFF top dictionary records. When I remove the FontName record using fontTools (not the CFF attribute), it is all fine. This issue happens for various fonts with standard as well as non-standard weight names, with 4-style (or 2-style) family grouping as well as for a single-style family.

CFF top dictionary in fonts generated with other tools than fontmake (just a quick ttx/look at fonts generated from the same source):

*AFDKO:*

- no FontName
- no FullName
- no Weight

*Glyphs:*

- no FontName
- no FamilyName

Here is the code I am using to fix this:

```
from fontTools.ttLib import TTFont

font = TTFont(path)
if "CFF " in font.keys():
	cff = font["CFF "].cff
	topDictrawDict = cff[cff.keys()[0]].rawDict
	del topDictrawDict["FontName"]
font.save(outpath)
font.close()
```

**Comment by miguelsousa** [comment]
Something isn't right. `FontName` is a required entry in the CFF's TopDict, because that's essentially the font's PostScript name. I can see Acrobat having problems with a PDF whose embedded fonts lack `FontName`, but not the other way around.

Could it be that the problematic fonts have the CFF's `FontName` different from the 'name' table's ID 6?

**Comment by miguelsousa** [comment]
In any case, I strngly advise against making OT-CFF fonts with a blank `FontName` string.

**Comment by MrBrezina** [comment]
I better specify what I mean by `FontName` record. This is ttx output of SourceCodePro-Regular.otf

```
  <CFF>
    <major value="1"/>
    <minor value="0"/>
    <CFFFont name="SourceCodePro-Regular">
      <version value="1.000"/>
      <Notice value="Source is a trademark of Adobe Systems Incorporated in the United States and/or other countries."/>
      <Copyright value="Copyright 2010, 2012 Adobe Systems Incorporated. All Rights Reserved."/>
      <FullName value="Source Code Pro"/>
      <FamilyName value="Source Code Pro"/>
…
```

You can see there is an attribute `name` on the `CFFFont` element, but there is no `FontName` element like: `<FontName value="SourceCodePro-Regular"/>` in there. If I produced the same font with fontmake there would be the attribute as well as the element.

**Comment by anthrotype** [comment]
https://github.com/googlei18n/ufo2ft/pull/234

**Comment by miguelsousa** [comment]
Are we talking about the same thing? All our name-keyed OT-CFF fonts have the `FontName` string set. Here's the same SourceCodePro-Regular.otf. The TTX dump is lying.
<img width="1127" alt="fontname" src="https://user-images.githubusercontent.com/2119742/39340377-b7f04728-4982-11e8-89d8-f73c70373d5f.png">

**Comment by MrBrezina** [comment]
@miguelsousa to be clear, I see the same in OTM and I think the ttx output is correct too. Only for the fontmake-produced fonts it would also contain the `<FontName .../>` element which probably should not be there.

**Comment by miguelsousa** [comment]
OK, I guess I don't know what and where **Name INDEX** is, then. Anyone care to explain?

**Comment by anthrotype** [comment]
The latest master branch of ufo2ft no longer sets that TopDict.FontName operator. We just need to cut a new release. I can do it when I’m back next week.

**Comment by anthrotype** [comment]
fixed by https://github.com/googlei18n/ufo2ft/pull/234, which is required by fontmake 1.5
