### ISSUE TITLE
Designspace, interpolation: directories in instance filenames are ignored

### ISSUE THREAD

**Issue by madig** [googlei18n/fontmake#428]
E.g.  `<instance ... filename="instance/Some_font.ufo" ...` is treated as `<instance ... filename="Some_font.ufo" ...`.

**Comment by anthrotype** [comment]
The filename attribute of the instances in the designspace document is read by mutatorMath and then unsed to save the generated ufo. fontmake doesn't do anything with it, when `run_from_designspace`.

**Comment by madig** [comment]
Hrm. It happens in one project but not in my other for demonstration purposes. Closing until I find the culprit.
