### ISSUE TITLE
possibly incorrect 'Duplicate kerning rules found for glyph pair "hhaa_ethiopic, ggwa_ethiopic" (-63 vs -63)'

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#43]
pipeline as of 2016-03-11 processing [NotoSansEthiopic-MM.glyphs.zip](https://github.com/googlei18n/fontmake/files/170119/NotoSansEthiopic-MM.glyphs.zip)
produces many warnings 

produces the following warnings. My guess that -63 vs -63 represent real numbers rounded/truncated to -63 so maybe these are real

WARNING: Duplicate kerning rules found for glyph pair "hhaa_ethiopic, ggwaa_ethiopic" (-63 vs -63), removing from rule "hhaa_ethiopic, public.kern2.ge_ethiopic"
WARNING: Duplicate kerning rules found for glyph pair "hhaa_ethiopic, ggwa_ethiopic" (-63 vs -63), removing from rule "hhaa_ethiopic, public.kern2.ge_ethiopic"
WARNING: Duplicate kerning rules found for glyph pair "hhaa_ethiopic, ggwi_ethiopic" (-63 vs -63), removing from rule "hhaa_ethiopic, public.kern2.ge_ethiopic"
WARNING: Duplicate kerning rules found for glyph pair "hhaa_ethiopic, ggwe_ethiopic" (-63 vs -63), removing from rule "hhaa_ethiopic, public.kern2.ge_ethiopic"

**Comment by behdad** [comment]
That's the first case I point out here:
https://github.com/unified-font-object/ufoLib/pull/15#issuecomment-193552682

The warnings are bogus.  @jamesgk, can you send a patch to ufoLib to fix this case?

**Comment by jamesgk** [comment]
These warnings are generated by glyphs2ufo; we have to remove the duplicates for ufoLib to accept the kerning. The PR you linked to is a patch changing ufoLib to accept valid duplicate rules.

**Comment by jamesgk** [comment]
I don't think we're getting warnings for actual duplicate rules anymore (just conflicts).
