### ISSUE TITLE
Fontmake version in uniqueid

### ISSUE THREAD

**Issue by m4rc1e** [googlei18n/fontmake#434]
ttfautohint and makeotf both have the ability to record which versions were used to gen the fonts. This info is stored in the uniqueid nametable record. I think it would be useful to have such an option for fonmake.

**Comment by anthrotype** [comment]
I think you mean the nameID 5, i.e. the version record. NameID 3 is the TrueType Unique ID, which is something else (though it may be a concatenation of other name strings, including the version string).
Yes, we discussed about this here: https://github.com/googlei18n/fontmake/issues/251
I think we should continue the discussion over there
