### ISSUE TITLE
noto_lint.py error: E <head/os2/windescent>

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#44]
I don't know if this is a big issue or not (cc @dougfelt ) but noto_lint.py produces the following error on our pipeline generated OTF font for the following fonts. It doesn't happen when otf is produced by the glyphs app.

NotoSansArmenian-Black.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSansArmenian-Bold.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSansArmenianCondensed-Black.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSansArmenianCondensed-Bold.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSansArmenianCondensed-Light.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSansArmenianCondensed-Medium.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSansArmenianCondensed-Regular.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSansArmenianCondensed-SemiBold.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSansArmenianCondensed-Thin.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSansArmenian-Light.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSansArmenian-Medium.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSansArmenian-Regular.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSansArmenian-SemiBold.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSansArmenian-Thin.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSansDisplay-BlackItalic.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSansDisplay-Black.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSansDisplay-BoldItalic.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSansDisplay-Bold.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSansDisplayCondensed-BlackItalic.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSansDisplayCondensed-Black.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSansDisplayCondensed-BoldItalic.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSansDisplayCondensed-Bold.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSansDisplayCondensed-ExtraBoldItalic.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSansDisplayCondensed-ExtraBold.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSansDisplayCondensed-Italic.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSansDisplayCondensed-LightItalic.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSansDisplayCondensed-Light.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSansDisplayCondensed-MediumItalic.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSansDisplayCondensed-Medium.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSansDisplayCondensed-Regular.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSansDisplayCondensed-ThinItalic.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSansDisplayCondensed-Thin.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSansDisplay-ExtraBoldItalic.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSansDisplay-ExtraBold.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSansDisplay-LightItalic.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSansDisplay-Light.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSansDisplay-MediumItalic.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSansDisplay-Medium.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSansDisplay-Regular.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSansDisplay-ThinItalic.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSansDisplay-Thin.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSansGeorgian-Black.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSansGeorgian-Bold.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSansGeorgianCondensed-Black.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSansGeorgianCondensed-Bold.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSansGeorgianCondensed-Light.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSansGeorgianCondensed-Medium.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSansGeorgianCondensed-Regular.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSansGeorgianCondensed-SemiBold.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSansGeorgianCondensed-Thin.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSansGeorgian-Light.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSansGeorgian-Medium.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSansGeorgian-Regular.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSansGeorgian-SemiBold.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSansGeorgian-Thin.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSansHebrewCondensed-Light.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (242) is different from the opposite of value of Descent in 'hhea' table (-240), but they should be opposites.
NotoSansHebrewCondensed-Medium.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (241) is different from the opposite of value of Descent in 'hhea' table (-240), but they should be opposites.
NotoSansHebrew-ExtraBold.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (252) is different from the opposite of value of Descent in 'hhea' table (-240), but they should be opposites.
NotoSansHebrew-Light.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (246) is different from the opposite of value of Descent in 'hhea' table (-240), but they should be opposites.
NotoSansHebrew-Medium.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (252) is different from the opposite of value of Descent in 'hhea' table (-240), but they should be opposites.
NotoSansUI-BlackItalic.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (389) is different from the opposite of value of Descent in 'hhea' table (-240), but they should be opposites.
NotoSansUI-Black.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (389) is different from the opposite of value of Descent in 'hhea' table (-240), but they should be opposites.
NotoSansUI-BoldItalic.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (389) is different from the opposite of value of Descent in 'hhea' table (-240), but they should be opposites.
NotoSansUI-Bold.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (389) is different from the opposite of value of Descent in 'hhea' table (-240), but they should be opposites.
NotoSansUICondensed-BlackItalic.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (389) is different from the opposite of value of Descent in 'hhea' table (-240), but they should be opposites.
NotoSansUICondensed-Black.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (389) is different from the opposite of value of Descent in 'hhea' table (-240), but they should be opposites.
NotoSansUICondensed-BoldItalic.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (389) is different from the opposite of value of Descent in 'hhea' table (-240), but they should be opposites.
NotoSansUICondensed-Bold.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (389) is different from the opposite of value of Descent in 'hhea' table (-240), but they should be opposites.
NotoSansUICondensed-ExtraBoldItalic.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (389) is different from the opposite of value of Descent in 'hhea' table (-240), but they should be opposites.
NotoSansUICondensed-ExtraBold.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (389) is different from the opposite of value of Descent in 'hhea' table (-240), but they should be opposites.
NotoSansUICondensed-Italic.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (389) is different from the opposite of value of Descent in 'hhea' table (-240), but they should be opposites.
NotoSansUICondensed-LightItalic.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (389) is different from the opposite of value of Descent in 'hhea' table (-240), but they should be opposites.
NotoSansUICondensed-Light.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (389) is different from the opposite of value of Descent in 'hhea' table (-236), but they should be opposites.
NotoSansUICondensed-MediumItalic.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (389) is different from the opposite of value of Descent in 'hhea' table (-240), but they should be opposites.
NotoSansUICondensed-Medium.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (389) is different from the opposite of value of Descent in 'hhea' table (-240), but they should be opposites.
NotoSansUICondensed-Regular.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (389) is different from the opposite of value of Descent in 'hhea' table (-240), but they should be opposites.
NotoSansUICondensed-ThinItalic.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (389) is different from the opposite of value of Descent in 'hhea' table (-240), but they should be opposites.
NotoSansUICondensed-Thin.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (389) is different from the opposite of value of Descent in 'hhea' table (-232), but they should be opposites.
NotoSansUI-ExtraBoldItalic.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (389) is different from the opposite of value of Descent in 'hhea' table (-240), but they should be opposites.
NotoSansUI-ExtraBold.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (389) is different from the opposite of value of Descent in 'hhea' table (-240), but they should be opposites.
NotoSansUI-LightItalic.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (389) is different from the opposite of value of Descent in 'hhea' table (-240), but they should be opposites.
NotoSansUI-Light.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (389) is different from the opposite of value of Descent in 'hhea' table (-240), but they should be opposites.
NotoSansUI-MediumItalic.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (389) is different from the opposite of value of Descent in 'hhea' table (-240), but they should be opposites.
NotoSansUI-Medium.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (389) is different from the opposite of value of Descent in 'hhea' table (-240), but they should be opposites.
NotoSansUI-Regular.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (389) is different from the opposite of value of Descent in 'hhea' table (-240), but they should be opposites.
NotoSansUI-ThinItalic.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (389) is different from the opposite of value of Descent in 'hhea' table (-240), but they should be opposites.
NotoSansUI-Thin.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (389) is different from the opposite of value of Descent in 'hhea' table (-240), but they should be opposites.
NotoSerifArmenian-Black.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSerifArmenian-Bold.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSerifArmenianCondensed-Black.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSerifArmenianCondensed-Bold.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSerifArmenianCondensed-Light.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSerifArmenianCondensed-Medium.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSerifArmenianCondensed-Regular.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSerifArmenianCondensed-SemiBold.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSerifArmenianCondensed-Thin.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSerifArmenian-Light.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSerifArmenian-Medium.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSerifArmenian-Regular.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (553) is different from the opposite of value of Descent in 'hhea' table (-600), but they should be opposites.
NotoSerifArmenian-SemiBold.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSerifArmenian-Thin.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSerifGeorgian-Black.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSerifGeorgian-Bold.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSerifGeorgianCondensed-Black.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSerifGeorgianCondensed-Bold.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSerifGeorgianCondensed-Light.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSerifGeorgianCondensed-Medium.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSerifGeorgianCondensed-Regular.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSerifGeorgianCondensed-SemiBold.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSerifGeorgianCondensed-Thin.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSerifGeorgian-Light.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSerifGeorgian-Medium.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSerifGeorgian-Regular.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (502) is different from the opposite of value of Descent in 'hhea' table (-600), but they should be opposites.
NotoSerifGeorgian-SemiBold.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSerifGeorgian-Thin.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (292) is different from the opposite of value of Descent in 'hhea' table (292), but they should be opposites.
NotoSerifThai-Regular.otf:E <head/os2/windescent> Value of usWinDescent in 'OS/2' table (534) is different from the opposite of value of Descent in 'hhea' table (-524), but they should be opposites.

**Comment by marekjez86** [comment]
similarly noto_lint.py produces the following error on our pipeline generated OTF font for the following fonts. It doesn't happen when otf is produced by the glyphs app.


NotoSansArmenian-Black.otf:E <head/os2/descender> Value of sTypoDescender in 'OS/2' table (-292) is different from the value of Descent in 'hhea' table (292), but they should be equal.
NotoSansArmenian-Bold.otf:E <head/os2/descender> Value of sTypoDescender in 'OS/2' table (-292) is different from the value of Descent in 'hhea' table (292), but they should be equal.
NotoSansArmenianCondensed-Black.otf:E <head/os2/descender> Value of sTypoDescender in 'OS/2' table (-292) is different from the value of Descent in 'hhea' table (292), but they should be equal.
NotoSansArmenianCondensed-Bold.otf:E <head/os2/descender> Value of sTypoDescender in 'OS/2' table (-292) is different from the value of Descent in 'hhea' table (292), but they should be equal.
NotoSansArmenianCondensed-Light.otf:E <head/os2/descender> Value of sTypoDescender in 'OS/2' table (-292) is different from the value of Descent in 'hhea' table (292), but they should be equal.
NotoSansArmenianCondensed-Medium.otf:E <head/os2/descender> Value of sTypoDescender in 'OS/2' table (-292) is different from the value of Descent in 'hhea' table (292), but they should be equal.
NotoSansArmenianCondensed-Regular.otf:E <head/os2/descender> Value of sTypoDescender in 'OS/2' table (-292) is different from the value of Descent in 'hhea' table (292), but they should be equal.
NotoSansArmenianCondensed-SemiBold.otf:E <head/os2/descender> Value of sTypoDescender in 'OS/2' table (-292) is different from the value of Descent in 'hhea' table (292), but they should be equal.
NotoSansArmenianCondensed-Thin.otf:E <head/os2/descender> Value of sTypoDescender in 'OS/2' table (-292) is different from the value of Descent in 'hhea' table (292), but they should be equal.
NotoSansArmenian-Light.otf:E <head/os2/descender> Value of sTypoDescender in 'OS/2' table (-292) is different from the value of Descent in 'hhea' table (292), but they should be equal.
NotoSansArmenian-Medium.otf:E <head/os2/descender> Value of sTypoDescender in 'OS/2' table (-292) is different from the value of Descent in 'hhea' table (292), but they should be equal.
NotoSansArmenian-Regular.otf:E <head/os2/descender> Value of sTypoDescender in 'OS/2' table (-292) is different from the value of Descent in 'hhea' table (292), but they should be equal.
NotoSansArmenian-SemiBold.otf:E <head/os2/descender> Value of sTypoDescender in 'OS/2' table (-292) is different from the value of Descent in 'hhea' table (292), but they should be equal.
NotoSansArmenian-Thin.otf:E <head/os2/descender> Value of sTypoDescender in 'OS/2' table (-292) is different from the value of Descent in 'hhea' table (292), but they should be equal.
NotoSansGeorgian-Black.otf:E <head/os2/descender> Value of sTypoDescender in 'OS/2' table (-292) is different from the value of Descent in 'hhea' table (292), but they should be equal.
NotoSansGeorgian-Bold.otf:E <head/os2/descender> Value of sTypoDescender in 'OS/2' table (-292) is different from the value of Descent in 'hhea' table (292), but they should be equal.
NotoSansGeorgianCondensed-Black.otf:E <head/os2/descender> Value of sTypoDescender in 'OS/2' table (-292) is different from the value of Descent in 'hhea' table (292), but they should be equal.
NotoSansGeorgianCondensed-Bold.otf:E <head/os2/descender> Value of sTypoDescender in 'OS/2' table (-292) is different from the value of Descent in 'hhea' table (292), but they should be equal.
NotoSansGeorgianCondensed-Light.otf:E <head/os2/descender> Value of sTypoDescender in 'OS/2' table (-292) is different from the value of Descent in 'hhea' table (292), but they should be equal.
NotoSansGeorgianCondensed-Medium.otf:E <head/os2/descender> Value of sTypoDescender in 'OS/2' table (-292) is different from the value of Descent in 'hhea' table (292), but they should be equal.
NotoSansGeorgianCondensed-Regular.otf:E <head/os2/descender> Value of sTypoDescender in 'OS/2' table (-292) is different from the value of Descent in 'hhea' table (292), but they should be equal.
NotoSansGeorgianCondensed-SemiBold.otf:E <head/os2/descender> Value of sTypoDescender in 'OS/2' table (-292) is different from the value of Descent in 'hhea' table (292), but they should be equal.
NotoSansGeorgianCondensed-Thin.otf:E <head/os2/descender> Value of sTypoDescender in 'OS/2' table (-292) is different from the value of Descent in 'hhea' table (292), but they should be equal.
NotoSansGeorgian-Light.otf:E <head/os2/descender> Value of sTypoDescender in 'OS/2' table (-292) is different from the value of Descent in 'hhea' table (292), but they should be equal.
NotoSansGeorgian-Medium.otf:E <head/os2/descender> Value of sTypoDescender in 'OS/2' table (-292) is different from the value of Descent in 'hhea' table (292), but they should be equal.
NotoSansGeorgian-Regular.otf:E <head/os2/descender> Value of sTypoDescender in 'OS/2' table (-292) is different from the value of Descent in 'hhea' table (292), but they should be equal.
NotoSansGeorgian-SemiBold.otf:E <head/os2/descender> Value of sTypoDescender in 'OS/2' table (-292) is different from the value of Descent in 'hhea' table (292), but they should be equal.
NotoSansGeorgian-Thin.otf:E <head/os2/descender> Value of sTypoDescender in 'OS/2' table (-292) is different from the value of Descent in 'hhea' table (292), but they should be equal.
NotoSerifArmenian-Black.otf:E <head/os2/descender> Value of sTypoDescender in 'OS/2' table (-292) is different from the value of Descent in 'hhea' table (292), but they should be equal.
NotoSerifArmenian-Bold.otf:E <head/os2/descender> Value of sTypoDescender in 'OS/2' table (-292) is different from the value of Descent in 'hhea' table (292), but they should be equal.
NotoSerifArmenianCondensed-Black.otf:E <head/os2/descender> Value of sTypoDescender in 'OS/2' table (-292) is different from the value of Descent in 'hhea' table (292), but they should be equal.
NotoSerifArmenianCondensed-Bold.otf:E <head/os2/descender> Value of sTypoDescender in 'OS/2' table (-292) is different from the value of Descent in 'hhea' table (292), but they should be equal.
NotoSerifArmenianCondensed-Light.otf:E <head/os2/descender> Value of sTypoDescender in 'OS/2' table (-292) is different from the value of Descent in 'hhea' table (292), but they should be equal.
NotoSerifArmenianCondensed-Medium.otf:E <head/os2/descender> Value of sTypoDescender in 'OS/2' table (-292) is different from the value of Descent in 'hhea' table (292), but they should be equal.
NotoSerifArmenianCondensed-Regular.otf:E <head/os2/descender> Value of sTypoDescender in 'OS/2' table (-292) is different from the value of Descent in 'hhea' table (292), but they should be equal.
NotoSerifArmenianCondensed-SemiBold.otf:E <head/os2/descender> Value of sTypoDescender in 'OS/2' table (-292) is different from the value of Descent in 'hhea' table (292), but they should be equal.
NotoSerifArmenianCondensed-Thin.otf:E <head/os2/descender> Value of sTypoDescender in 'OS/2' table (-292) is different from the value of Descent in 'hhea' table (292), but they should be equal.
NotoSerifArmenian-Light.otf:E <head/os2/descender> Value of sTypoDescender in 'OS/2' table (-292) is different from the value of Descent in 'hhea' table (292), but they should be equal.
NotoSerifArmenian-Medium.otf:E <head/os2/descender> Value of sTypoDescender in 'OS/2' table (-292) is different from the value of Descent in 'hhea' table (292), but they should be equal.
NotoSerifArmenian-SemiBold.otf:E <head/os2/descender> Value of sTypoDescender in 'OS/2' table (-292) is different from the value of Descent in 'hhea' table (292), but they should be equal.
NotoSerifArmenian-Thin.otf:E <head/os2/descender> Value of sTypoDescender in 'OS/2' table (-292) is different from the value of Descent in 'hhea' table (292), but they should be equal.
NotoSerifGeorgian-Black.otf:E <head/os2/descender> Value of sTypoDescender in 'OS/2' table (-292) is different from the value of Descent in 'hhea' table (292), but they should be equal.
NotoSerifGeorgian-Bold.otf:E <head/os2/descender> Value of sTypoDescender in 'OS/2' table (-292) is different from the value of Descent in 'hhea' table (292), but they should be equal.
NotoSerifGeorgianCondensed-Black.otf:E <head/os2/descender> Value of sTypoDescender in 'OS/2' table (-292) is different from the value of Descent in 'hhea' table (292), but they should be equal.
NotoSerifGeorgianCondensed-Bold.otf:E <head/os2/descender> Value of sTypoDescender in 'OS/2' table (-292) is different from the value of Descent in 'hhea' table (292), but they should be equal.
NotoSerifGeorgianCondensed-Light.otf:E <head/os2/descender> Value of sTypoDescender in 'OS/2' table (-292) is different from the value of Descent in 'hhea' table (292), but they should be equal.
NotoSerifGeorgianCondensed-Medium.otf:E <head/os2/descender> Value of sTypoDescender in 'OS/2' table (-292) is different from the value of Descent in 'hhea' table (292), but they should be equal.
NotoSerifGeorgianCondensed-Regular.otf:E <head/os2/descender> Value of sTypoDescender in 'OS/2' table (-292) is different from the value of Descent in 'hhea' table (292), but they should be equal.
NotoSerifGeorgianCondensed-SemiBold.otf:E <head/os2/descender> Value of sTypoDescender in 'OS/2' table (-292) is different from the value of Descent in 'hhea' table (292), but they should be equal.
NotoSerifGeorgianCondensed-Thin.otf:E <head/os2/descender> Value of sTypoDescender in 'OS/2' table (-292) is different from the value of Descent in 'hhea' table (292), but they should be equal.
NotoSerifGeorgian-Light.otf:E <head/os2/descender> Value of sTypoDescender in 'OS/2' table (-292) is different from the value of Descent in 'hhea' table (292), but they should be equal.
NotoSerifGeorgian-Medium.otf:E <head/os2/descender> Value of sTypoDescender in 'OS/2' table (-292) is different from the value of Descent in 'hhea' table (292), but they should be equal.
NotoSerifGeorgian-SemiBold.otf:E <head/os2/descender> Value of sTypoDescender in 'OS/2' table (-292) is different from the value of Descent in 'hhea' table (292), but they should be equal.
NotoSerifGeorgian-Thin.otf:E <head/os2/descender> Value of sTypoDescender in 'OS/2' table (-292) is different from the value of Descent in 'hhea' table (292), but they should be equal.

**Comment by jamesgk** [comment]
These should no longer be issues.
