### ISSUE TITLE
Export flag: subsetter does not account for .notdef in OT binary

### ISSUE THREAD

**Issue by madig** [googlei18n/fontmake#443]
https://github.com/googlei18n/fontmake/blob/master/Lib/fontmake/font_project.py#L441

This leads to glyphs not lining up:
```
old_name new_name
A .notdef
B A
C B
D C
E D
F E
G F
H G
I H
[...]
```

**Comment by madig** [comment]
Hm. So `.notdef` might be in the UFO, but not as the first glyph, so this needs special handling.

**Comment by anthrotype** [comment]
ufo2ft forces .notdef to always be the first, so the output TTFont always has it as the first glyph. And if the font doesn't contain one, it inserts as stub glyph at that position.
There is no other sensible place for a glyph that is named ".notdef" (and of course has no codepoint assigned to it).
I believe Glyphs.app also does the same, if .notdef is present in the font.
