### ISSUE TITLE
fontmake fails to remove hyphens in names from glyphs source

### ISSUE THREAD

**Issue by mjlagattuta** [googlei18n/fontmake#455]
Glyphs App employs hyphens in glyph names do detail the script a glyph belongs to. This is normally not an issue for fontmake as those glyph names are converted to production names on export. The issue is that if a name is used which has no production equivalent then the hyphens are not removed.

In my case I was using "descender-cy" to make Cyrillic composites. I believe the practice in Glyphs is to drop the hyphen on export and I was wondering if fontmake could do the same

**Comment by davelab6** [comment]
Context: https://forum.glyphsapp.com/t/do-all-glyphs-drop-their-hyphens-on-export/9519/3 & https://github.com/googlefonts/robotoslab/issues/10

Seems high priority and perhaps relatively simple to fix :)

**Comment by anthrotype** [comment]
For reference, i'm quoting below the latest version of Adobe Feature File spec as available on the github afdko repository (the one published [on Adobe's website](https://www.adobe.com/devnet/opentype/afdko/topic_feature_file_syntax.html#2.f.i) is not up to date apparently)
 
Source: https://github.com/adobe-type-tools/afdko/blob/develop/docs/OpenTypeFeatureFileSpecification.html

======

<p><a name="2.f.i"></a><b>2.f.i. Glyph name</b></p>
<p>There are two different contexts for glyph naming: final production names and development names.</p>
<p>For production glyph names, names that are used in shipping font files, the specification is set by the Postscript and Type 1 specifications, which define what is expected by existing PostScript interpreters. These limitations are as follows.</p>
<p>A glyph name may be up to 63 characters in length, must be entirely comprised of characters from the following set:</p>
<p>A-Z a-z 0-9 . (period) _ (underscore)</p>
<p>and must not start with a digit or period. The only exception is the special character &quot;.notdef&quot;.</p>
<p>&quot;twocents&quot;, &quot;a1&quot;, and &quot;_&quot; are valid glyph names. &quot;2cents&quot; and &quot;.twocents&quot; are not.</p>
<p> Development glyph names, names used in source data during the development of a font, have a larger supported character set. In addition to the characters allowed for production glyph names, the following characters must also be supported for development glyph names:</p>
<ul>
<li>U+002A	*	Asterisk	</li>
<li>U+002B	+	Plus sign</li>
<li>U+002D	-	Hyphen-minus</li>
<li>U+003A	:	Colon</li>
<li>U+005E	^	Circumflex accent</li>
<li>U+007C	|	Vertical bar</li>
<li>U+007E	~	Tilde</li>
</ul>

**Comment by anthrotype** [comment]
I think it should be the responsibility of ufo2ft PostProcessor to perform this, since it is already doing the renaming from development to production glyph names.
I think we just need to replace any characters that are not in the valid set with an underscore.
The valid characters according to the quote above are: A-Z a-z 0-9 . (period) _ (underscore)

**Comment by anthrotype** [comment]
and if they start with a digit or period, we prefix them with another underscore

**Comment by moyogo** [comment]
The [OT spec for the post table](https://docs.microsoft.com/en-us/typography/opentype/spec/post) points to the [AGL specification](https://github.com/adobe-type-tools/agl-specification) which says the same: A-Z a-z 0-9 . (period) _ (underscore).

**Comment by madig** [comment]
makeotf/Glyphs really just drops the hyphen it seems:
```
-    <GlyphID id="1065" name="brevecombcy"/>
-    <GlyphID id="1066" name="descendercy"/>
-    <GlyphID id="1067" name="brevecombcy.case"/>
-    <GlyphID id="1068" name="descendercy.case"/>
-    <GlyphID id="1069" name="descendercy.strait"/>
+    <GlyphID id="1065" name="brevecomb-cy"/>
+    <GlyphID id="1066" name="descender-cy"/>
+    <GlyphID id="1067" name="brevecomb-cy.case"/>
+    <GlyphID id="1068" name="descender-cy.case"/>
+    <GlyphID id="1069" name="descender-cy.strait"/>
```

**Comment by madig** [comment]
If they are junk, why are we writing them to the post table anyway?

**Comment by anthrotype** [comment]
fixed in https://github.com/googlei18n/ufo2ft/pull/274
