### ISSUE TITLE
NotoSansArabic-Black: for NotoSansArabic-Black we produce <Weight value="Bold"/>

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#46]
I do not know how important this info is in the file but for NotoSansArabic-Black we produce <Weight value="Bold"/> and Glyphs app creates <Weight value="Black"/> which appears to be more correct (but maybe both are OK, I do not know).

```
4541c4298,4300
<       <Weight value="Black"/>
---
>       <FontName value="NotoSansArabic-Black"/>
>       <FamilyName value="Noto Sans Arabic"/>
>       <Weight value="Bold"/>
```

Glyphs produced OTF 
[NotoSansArabic-Black.otf.zip](https://github.com/googlei18n/fontmake/files/174640/NotoSansArabic-Black.otf.zip)

Pipeline produced OTF 
[NotoSansArabic-Black.otf.zip](https://github.com/googlei18n/fontmake/files/174639/NotoSansArabic-Black.otf.zip)

**Comment by marekjez86** [comment]
[weight.txt](https://github.com/googlei18n/fontmake/files/174814/weight.txt)

the file above contains the text I originally quoted in the bug (unfortunately it was treated as Markdown text).

**Comment by jamesgk** [comment]
I think our output is better; only Regular or Bold weights should be in the subfamily name.
