### ISSUE TITLE
how creating alternatives? and beginning

### ISSUE THREAD

**Issue by letarg0** [googlei18n/fontmake#460]
I have two variant of 'a'
how add this to font?

ho add a begining of word? for example in arabic char 'a' is in 3 variant
first letter in word, middle,last char in word. this same char = 3 glyph. of course in conscript too.

**Comment by anthrotype** [comment]
I'd recommend you direct questions like these to a type design forum like http://typedrawers.com.

**Comment by anthrotype** [comment]
this is also a good place to start http://opentypecookbook.com/index.html

**Comment by and09** [comment]
question is, yours library can do this or not.

**Comment by anthrotype** [comment]
Yes, but you have to write the feature file first.

**Comment by letarg0** [comment]
@anthrotype  Can You write example?
I have 2 glyph of 'a' how add this? I use Latex to using font. Is possible completly example?

**Comment by anthrotype** [comment]
fontmake is just a font compiler. You give it compatible source files (either Glyphs or UFO format) and it produces an OTF or TTF font file. If the sources can contain [OpenType features](https://www.adobe.com/devnet/opentype/afdko/topic_feature_file_syntax.html), fontmake will build OpenType layout tables (GSUB, GPOS, etc.) from these.
I can't teach you how to write proper OT features code here, sorry.
I pointed at some free online resources and forums where you can ask questions like these.

**Comment by letarg0** [comment]
@anthrotype in my opinion ufo dont decribe alternatives of glyph.

Can You tell me what font have alternatives? I produce ufo files from this font and read what i can create source
