### ISSUE TITLE
Bad kerning in SourceSansVariable-Italic.ttf

### ISSUE THREAD

**Issue by miguelsousa** [googlei18n/fontmake#464]
I'm getting bad kern pairs when building the variable TTF version of Source Sans Pro italic with `fontmake` version 1.7.4. The CFF2 version built from the same source files does not have this problem.

<img width="1001" alt="vata" src="https://user-images.githubusercontent.com/2119742/46139272-f4f1a380-c202-11e8-9297-ccaed1a2ba2f.png">

[SourceSansVariable-Italic.ttf.zip](https://github.com/googlei18n/fontmake/files/2423616/SourceSansVariable-Italic.ttf.zip)
[SourceSansVariable-Italic.otf.zip](https://github.com/googlei18n/fontmake/files/2423623/SourceSansVariable-Italic.otf.zip)

The source files are at https://github.com/adobe-fonts/source-sans-pro/tree/fontmake
The build command used was
`fontmake -m Italic/Masters/SourceSansVariable-Italic.designspace -o variable --output-path SourceSansVariable-Italic.ttf`

**Comment by miguelsousa** [comment]
I traced this back to changes introduced in **ufo2ft** `v2.0.0` https://github.com/googlei18n/ufo2ft/issues/280

**Comment by anthrotype** [comment]
please refer to my explanation in googlei18n/ufo2ft#280
