### ISSUE TITLE
uniXXXX names for all glyphs???

### ISSUE THREAD

**Issue by schriftgestalt** [googlei18n/fontmake#465]
Is there a reason that all glyphs get a uniXXXX name? I would expect that at last the AGLNF is used. Or is my setup broken (I just updated to the latest version, but maybe I missed something)?

**Comment by anthrotype** [comment]
ufo2ft.postProcessor is responsible for renaming glyphs to production names. If the UFO contains a `public.postscriptNames` list in the lib.plist, that will be used to do the renaming. GlyphsLib generates such a list when making the UFOs from .glyphs sources, using the production names from GlyphData.xml.
When `public.postscriptNames` is not present, ufo2ft will rename all the glyphs (with a unicode) to uniXXXX. 
If the UFO has `com.github.googlei18n.ufo2ft.useProductionNames` set to False (or if has the equivalent `com.schriftgestaltung.Don't use Production Names`, set to True), then no renaming happens.

https://github.com/googlei18n/ufo2ft/blob/c9925b38a103d2396528a5ec0b23d26016969e25/Lib/ufo2ft/postProcessor.py#L36-L45

fontmake also has `--production-names/--no-production-names` command line options to always (or never) perform the renaming operation, overriding the value set in the UFO lib.

At some point, @madig worked on a PR to use AGLFN names in the ufo2ft postProcessor (for when no explicit public.postsciptNames list is present), though he didn't finish it
https://github.com/googlei18n/ufo2ft/pull/211

I don't have strong opinions in either direction. I think uniXXXX for all glyphs is still techinically valid, as these postscript glyph names are more meant to be parsed by pdf renderers than by humans.
If anybody feels like working on a pull request, I will review it.

**Comment by schriftgestalt** [comment]
Glyphs only uses whatever is stored in the productionName field in GlyphData. It there is nothing set, it just keeps the name.

**Comment by anthrotype** [comment]
the public.postscriptNames in UFO lib is meant to do the same. Any glyphs that are present in that mapping will be renamed, otherwise they are not.
If the whole public.postcriptNames mapping is not available, then ufo2ft falls back to renaming all the glyphs to uniXXXX.
But you can disable this as I explained above.

**Comment by schriftgestalt** [comment]
>At some point, @madig worked on a PR to use AGLFN names in the ufo2ft postProcessor (for when no explicit public.postsciptNames list is present), though he didn't finish it

maybe on this point just stick with the name as is? And expect the `public.postsciptNames` to be set by whoever writes the ufo? And glyphsLib has the GlyphData now, so it nows when to assign a production name. 

> But you can disable this as I explained above.

You didn't. At least I don’t understand it that way. You mean `--production-names/--no-production-names` or `com.github.googlei18n.ufo2ft.useProductionNames`? That sounds like I would get no production names at all. 

I would just remove the uniXXXX name assignment in ufo2ft?

**Comment by anthrotype** [comment]
> That sounds like I would get no production names at all.

yes. Currently, if you want the AGLFN names you need to provide an explicit public.poscriptNames mapping in the UFO lib. Otherwise all glyphs (even a, b, c) will be renamed to uniXXXX.

> I would just remove the uniXXXX name assignment in ufo2ft... And expect the public.postsciptNames to be set by whoever writes the ufo

that's something we could consider. Is anybody else relying on this feature?

**Comment by schriftgestalt** [comment]
If ufo2ft can’t change, then glyphsLib should write the postscript name for all glyphs.

**Comment by anthrotype** [comment]
> glyphsLib should write the postscript name for all glyphs

no. glyphsLib already always writes a public.postcriptNames. That is enough to have only the glyphs that are explicitly mentioned in there to be renamed to whatever is their production name, whereas the rest which are not listed will keep their name. So the AGLFN glyphs may be omitted.

**Comment by anthrotype** [comment]
see https://github.com/googlei18n/ufo2ft/blob/c9925b38a103d2396528a5ec0b23d26016969e25/Lib/ufo2ft/postProcessor.py#L130-L133

if glyph.name is not in `public.postscriptNames`, then the original name is used.

**Comment by madig** [comment]
For what it's worth, I abandoned the AGLFN namer because I figured that there isn't much of a point to it (uniXXXX names are AGLFN-compatible, too).



>> I would just remove the uniXXXX name assignment in ufo2ft... And expect the public.postsciptNames to be set by whoever writes the ufo

> that's something we could consider. Is anybody else relying on this feature?

We currently manually invoke the post-processor in a later building step, so we only rely on `--no-production-names`.

If automatic production names are up for debate, one possibility would be to automatically write a `post` table version 3 without any PS names if no `public.postscriptNames` is present?

**Comment by anthrotype** [comment]
> If automatic production names are up for debate, one possibility would be to automatically write a post table version 3 without any PS names if no public.postscriptNames is present?

hm, I think that should be a different option

**Comment by schriftgestalt** [comment]
If you skip the AGLFN names, you should, at least, use the ones from the Mac encoding to not waist space in the post table. 

It is funny that I argue against doing automatic things on export. I would just rely on the data in the ufo. If it has production names, use it, otherwise just stick to the glyph names.

**Comment by anthrotype** [comment]
in general I agree with you; we just kept it that way when we added support for the new `public.postscriptNames` because it was already doing that.

**Comment by miguelsousa** [comment]
My opinion is that no glyph renaming should happen, unless `public.postscriptNames` is present.

**Comment by anthrotype** [comment]
So we all agree, let’s change it

**Comment by madig** [comment]
I.e. without a public.postscriptNames entry, a post table version 2 is written with the unmodified glyph names?

**Comment by miguelsousa** [comment]
The decision to rename glyphs (or not) is independent from the decision of which `post` table format to use.

**Comment by anthrotype** [comment]
I have a better idea instead of throwing this code away.
We already have a "com.github.googlei18n.ufo2ft.useProductionNames` boolean key defined. Currently when missing it defaults to `True`, and the user can set it to False to prevent the glyph renaming.
  
We can change it so that, when it is missing, the glyph renaming should only happen iff the public.postscriptNames mapping is also present.

But.. when the key is explicitly set to True, then the glyph renaming will happen, even in absence of an explicit public.postscriptNames mapping, but using uniXXXX names from glyph unicodes.

When the key is False, of course nothing should happen, whether or not public.postscriptnames is there.

**Comment by anthrotype** [comment]
the idea is, by default use the public.postcriptNames if it's there, else don't touch the names.
If the `useProductionNames` key is set to True (or if fontmake option --production-names is passed explicitly), then do the renaming with what you have available: prefer the public.postcriptNames, fall back to unicodes.

**Comment by anthrotype** [comment]
fixed in 2f800cb

**Comment by chrissimpkins** [comment]
Note that the change here breaks ttfautohint control instructions file workflows that are dependent on the previous default naming behavior.  Update those control instructions files or turn on the `--production-names` fontmake switch.

**Comment by madig** [comment]
Argh 😁 it's irritating how this legacy stuff continues to be a problem.
