### ISSUE TITLE
Non-ASCII glyph notes

### ISSUE THREAD

**Issue by arialcrime** [googlei18n/fontmake#467]
Hello there,

I recently ran into a problem with a GlyphsApp file that contained glyph notes created with [this plugin](https://github.com/mekkablue/NotePalettes). One of the entries contained the letter „ä“, resulting in the following error when trying to generate fonts with fontmake:

`ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters`

This struck me as a bit odd, since fontmake is able to handle non-ASCII characters just fine elsewhere and using Unicode characters should not really be a problem.

Am I missing something here? Is this a bug?
Thanks in advance!

**Comment by anthrotype** [comment]
It's not about ASCII, but about XML. Some Unicode characters (control characters, the surrogate blocks, FFFE, and FFFF) are not valid in XML strings.

This is the regex that ufoLib uses to match those:
https://github.com/unified-font-object/ufoLib/blob/b1ec81ab56461c17ae2cfd64ee5c0fcb693dc55d/Lib/ufoLib/etree.py#L225-L261

I doubt it is that letter `„ä“` you mentioned, it think it might be some of the other non printable control characters.
Check again with that regular expression, or print the string with python repr().

Ideally ufoLib should tell you the line and column..

**Comment by arialcrime** [comment]
So as a quick test I was just removing individual characters from the note. 

There, it also looks like the error message is caused by “ä”. Removing it within GlyphsApp “solves” the problem. The same behavior can also be observed when using an almost blank test font with only an “ä” in the note of the “A” (see attachment).

[Test Font-Regular.zip](https://github.com/googlei18n/fontmake/files/2437694/Test.Font-Regular.zip)

**Comment by anthrotype** [comment]
oh I see...
It's a bug in ufoLib. The _writeNote function in ufoLib.glifLib must send either a unicode string or a ascii encoded bytes string to lxml, whereas it is setting the element's text attribute to a bytes string encoded in UTF-8.
Thanks for this, I'll fix it in ufoLib.

**Comment by anthrotype** [comment]
amazing that nobody caught this for so long

**Comment by anthrotype** [comment]
@arialcrime you should be able to pip install --upgrade ufoLib in a few minutes 
https://pypi.org/project/ufoLib/2.3.2/
