### ISSUE TITLE
Fontmake fails to generate proper min max with HOI

### ISSUE THREAD

**Issue by mjlagattuta** [googlei18n/fontmake#473]
When using higher order interpolations in a stepped fashion (i.e. a cubic interpolation from 0-500 and then another cubic interpolation from 500-1000), fontmake correctly generates the `delta` values, but fails to generate the proper `min` and `max` values

In some cases (in ttx) no `min` or `max` is added at all and in others the issue seems to be that all occurrences of `min` reference the same value.

**Comment by behdad** [comment]
What min and max are you talking about?  Need details.

**Comment by mjlagattuta** [comment]
The min and max range of an axis that a given set of deltas apply to. This is a ttx snippet of one of the tuples that fontmake generates (in ttx) for a quadratic interpolation:
```xml
      <tuple>
        <coord axis="TIME" value="0.25"/>
        <coord axis="TIM2" max="0.5" min="0.25" value="0.5"/>
        <delta pt="6" x="200" y="-200"/>
        <delta pt="26" x="0" y="-25"/>
        <delta pt="27" x="0" y="25"/>
      </tuple>
```

and here is the corrected version:
```xml
      <tuple>
        <coord axis="TIME" max="0.5" min="0.0" value="0.25"/>
        <coord axis="TIM2" max="0.75" min="0.25" value="0.5"/>
        <delta pt="6" x="200" y="-200"/>
        <delta pt="26" x="0" y="-25"/>
        <delta pt="27" x="0" y="25"/>
      </tuple>
```

**Comment by behdad** [comment]
This is how the varLib model works.  Can you share the full master configuration?

**Comment by mjlagattuta** [comment]
Sure thing. There are two axes with masters at:
- 0, 0
- 0, 250
- 250, 0
- 250, 250
- 500, 250
- 250, 500
- 500, 500
- 750, 500
- 500, 750
- 750, 750
- 1000, 750
- 750, 1000
- 1000, 1000

The masters with the same values flipped (i.e. 250, 500 and 500, 250) are identical but sit at 2 places in the designspace

Also here's the glyphs file: [deltasTEST2.glyphs.zip](https://github.com/googlei18n/fontmake/files/2517145/deltasTEST2.glyphs.zip)

**Comment by behdad** [comment]
varLib doesn't work if you don't have on-axis extreme masters, ie. 0,1000 and 1000,0.  How does it for you?

**Comment by behdad** [comment]
Or do you have a full 5x5 mesh?

**Comment by behdad** [comment]
I suppose you have the 5x5 mesh, and the ones you didn't list simply are the same as origin?

**Comment by mjlagattuta** [comment]
I don't believe I have a 5x5 mesh, what is that?

And no other masters, only the ones I listed, and fontmake manages to build it even though it lacks those extremes.

Just tried building after adding masters identical to origin at 1000, 0 and 0, 1000 as you said and it works as expected, thanks!

**Comment by behdad** [comment]
That's really weird.  It's not supposed to work without those!  I'll investigate.  Thanks.

**Comment by behdad** [comment]
Okay apparently the new varLib model does NOT enforce extremes on axes, though the results don't make sense without those.  Here's a simpler test case, from Akiem:
```
$ ./fonttools varLib.models 0,0 .5,0 0,.5 .5,5 1,1
Sorted locations:
[{}, {'A': 0.5}, {'B': 0.5}, {'A': 0.5, 'B': 5.0}, {'A': 1.0, 'B': 1.0}]
Supports:
[{},
 {'A': (0, 0.5, 0.5)},
 {'B': (0, 0.5, 0.5)},
 {'A': (0, 0.5, 0.5), 'B': (0, 5.0, 5.0)},
 {'A': (0, 1.0, 1.0), 'B': (0, 1.0, 1.0)}]
```
@letterror Erik, what does MutatorMath do with this?  What *is* the expected value at 1,0 and 0,1?

**Comment by behdad** [comment]
I probably add code to verbosely fail if axis extremes don't have masters.

**Comment by anthrotype** [comment]
@behdad thanks for looking into this!
@mjlagattuta can you try with fonttools latest master branch? A new fonttools release should be out very soon.

**Comment by mjlagattuta** [comment]
@anthrotype, I just tested with the latest master branch of fonttools, it builds the font with the expected visual output without having masters at 0, 1000 or 1000, 0

Some delta values and corresponding min and max values are different but as I said the output is good.

**Comment by anthrotype** [comment]
btw, I'd be curious to know more about this HOI thing you're working on... :wink:
you know where to reach me
