### ISSUE TITLE
nameID 6 generates with spaces

### ISSUE THREAD

**Issue by weiweihuanghuang** [googlei18n/fontmake#478]
I noticed when generating with fontmake my font name in nameID 6 still has spaces in it? shouldn't it be default that the space is removed?

**Comment by anthrotype** [comment]
that's strange, ufo2ft takes care of normalizing the UFO font.info.postscriptFontName:

https://github.com/googlei18n/ufo2ft/blob/44f3199c9b27108eb9dc9052c15d153b73224328/Lib/ufo2ft/outlineCompiler.py#L326
https://github.com/googlei18n/ufo2ft/blob/44f3199c9b27108eb9dc9052c15d153b73224328/Lib/ufo2ft/fontInfoData.py#L192-L223

how can we reproduce?

**Comment by m4rc1e** [comment]
I'm assuming this is happening in Work Sans, https://github.com/weiweihuanghuang/Work-Sans.

I'm not able to replicate this when generating the fonts using fontmake v1.8.0.

I get the following for nameID 6:

**WorkSans.glyphs:** WorkSans-Regular
**WorkSans-Italic.glyphs:** WorkSans-ItalicItalic


@weiweihuanghuang  Are you sure you're not introducing this in your post processing steps?

**Comment by weiweihuanghuang** [comment]
Weirdly now I don't get this issue, I do think it was probably one of my post processing steps though
