### ISSUE TITLE
difference between the hb-view outputs for font generated by pipeline and by the Glyphs app

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#48]
I used  [NotoSerifThai-MM.glyphs.zip](https://github.com/googlei18n/fontmake/files/176455/NotoSerifThai-MM.glyphs.zip) as input to both pipeline and to the Glyphs.app on Mac.

The pipeline produced the following OTF font
[NotoSerifThai-Regular.otf.zip](https://github.com/googlei18n/fontmake/files/176478/NotoSerifThai-Regular.otf.zip)

The Glyphs.app on Mac produced the following OTF font
[NotoSerifThai-Regular.otf.zip](https://github.com/googlei18n/fontmake/files/176457/NotoSerifThai-Regular.otf.zip)

Then I ran
hb-view NotoSerifThai-Regular.otf --output-format=png --text-file=../thai-sample2.txt > ts.png
for each of the fonts.

Pipeline font produced the following image
![ts2](https://cloud.githubusercontent.com/assets/13322623/13820962/efe6c976-eb5c-11e5-8a07-8ba0da6f8f46.png)

The Glyphs.app on Mac font produced the following image
![ts](https://cloud.githubusercontent.com/assets/13322623/13821008/1373400e-eb5d-11e5-9b1d-0d7c815dee7d.png)

**Comment by marekjez86** [comment]
samples for all versions produced by pipeline are below

NotoSerifThai-Black.otf 
![notoserifthai-black otf](https://cloud.githubusercontent.com/assets/13322623/13823576/79c42df0-eb67-11e5-91fd-058b5441c228.png)

NotoSerifThai-Bold.otf 
![notoserifthai-bold otf](https://cloud.githubusercontent.com/assets/13322623/13823573/73a8d74a-eb67-11e5-97ce-0ca86d59babf.png)

NotoSerifThai-Regular.otf 
![notoserifthai-regular otf](https://cloud.githubusercontent.com/assets/13322623/13823566/67710e20-eb67-11e5-912c-607667a0cd76.png)

NotoSerifThai-Thin.otf 
![notoserifthai-thin otf](https://cloud.githubusercontent.com/assets/13322623/13823562/5d2983a2-eb67-11e5-8a7e-2cb1725f7ab9.png)

NotoSerifThaiCondensed-Black.otf 
![notoserifthaicondensed-black otf](https://cloud.githubusercontent.com/assets/13322623/13823558/5285359a-eb67-11e5-85e8-d512254975e1.png)

NotoSerifThaiCondensed-Bold.otf 
![notoserifthaicondensed-bold otf](https://cloud.githubusercontent.com/assets/13322623/13823554/4ca4ca82-eb67-11e5-8e58-add7479d669b.png)

NotoSerifThaiCondensed-Regular.otf 
![notoserifthaicondensed-regular otf](https://cloud.githubusercontent.com/assets/13322623/13823546/40468028-eb67-11e5-8ede-3d8fff0d1ca9.png)

NotoSerifThaiCondensed-Thin.otf
![notoserifthaicondensed-thin otf](https://cloud.githubusercontent.com/assets/13322623/13823525/20d3430c-eb67-11e5-804a-082f9ddf3b66.png)

**Comment by jamesgk** [comment]
This is quite an impressive bug! However, I'm not getting similar results with the latest toolchain output using the first characters from https://github.com/googlei18n/nototools/blob/master/sample_texts/th-Thai_udhr.txt:

![notoserifthai-regular otf](https://cloud.githubusercontent.com/assets/988758/14195532/21736260-f76f-11e5-95cd-b90975b2e65f.png)

**Comment by marekjez86** [comment]
instance_otf_20160328 marekj$ hb-view --version
hb-view (HarfBuzz) 1.2.4
Available shapers: graphite2,ot,fallback

Interesting: I get the same problem on my Mac. I'll check hb-view (but I need to install) on my Linux.

Inside the otf directory I ran the following:

for i in `ls NotoSerifThai*.otf` ; do echo ========= $i ============= ; hb-view $i --output-format=png --text-file=../thai-sample3.txt > $i.3.png ; done

where ../thai-sample3.txt contained the text I found in https://github.com/googlei18n/nototools/blob/master/sample_texts/th-Thai_udhr.txt

Possibly I have installation problems on my Mac

**Comment by jamesgk** [comment]
Hmm. Let's also wait for https://github.com/googlei18n/glyphs2ufo/pull/29 and https://github.com/googlei18n/fontmake/pull/55 to be merged.

**Comment by marekjez86** [comment]
I ran on my Linux with today's OTFs. Looks good. Therefore most likely a problem with my hb-view on Mac:

![notosansthai-black otf 2](https://cloud.githubusercontent.com/assets/13322623/14197485/a68738c8-f783-11e5-891c-16dfd36bea90.png)
![notosansthai-bold otf 2](https://cloud.githubusercontent.com/assets/13322623/14197487/a68a781c-f783-11e5-9f7d-9b0721c5d4ef.png)
![notosansthai-regular otf 2](https://cloud.githubusercontent.com/assets/13322623/14197488/a68a6a3e-f783-11e5-81d2-e80219e7ab83.png)
![notosansthai-thin otf 2](https://cloud.githubusercontent.com/assets/13322623/14197489/a68aa9d6-f783-11e5-9e9b-a7d3cec61f49.png)
![notosansthaicondensed-bold otf 2](https://cloud.githubusercontent.com/assets/13322623/14197486/a68a6674-f783-11e5-9483-25e54c2e893f.png)
![notosansthaicondensed-regular otf 2](https://cloud.githubusercontent.com/assets/13322623/14197490/a68ae3e2-f783-11e5-9dc6-4576f68978bb.png)
![notosansthaicondensed-thin otf 2](https://cloud.githubusercontent.com/assets/13322623/14197491/a69846fe-f783-11e5-8d8e-1794f6ab12a6.png)
![notoserifthai-black otf 2](https://cloud.githubusercontent.com/assets/13322623/14197493/a69f27da-f783-11e5-9f81-4dbdb10328dc.png)
![notoserifthai-bold otf 2](https://cloud.githubusercontent.com/assets/13322623/14197494/a69f41ca-f783-11e5-9ae1-ec66ec3ac71e.png)
![notoserifthai-regular otf 2](https://cloud.githubusercontent.com/assets/13322623/14197496/a69fb858-f783-11e5-9296-ccfb0c80ca44.png)
![notoserifthai-thin otf 2](https://cloud.githubusercontent.com/assets/13322623/14197495/a69fbfb0-f783-11e5-9fd7-6d91e6309c78.png)
![notoserifthaicondensed-black otf 2](https://cloud.githubusercontent.com/assets/13322623/14197492/a69f0746-f783-11e5-800e-3674a846917c.png)
![notoserifthaicondensed-bold otf 2](https://cloud.githubusercontent.com/assets/13322623/14197497/a6aa26bc-f783-11e5-9f54-55aa477269a5.png)
![notoserifthaicondensed-regular otf 2](https://cloud.githubusercontent.com/assets/13322623/14197498/a6b19b7c-f783-11e5-860b-787da731feaa.png)
![notoserifthaicondensed-thin otf 2](https://cloud.githubusercontent.com/assets/13322623/14197499/a6b27c90-f783-11e5-9131-7bf60935260c.png)

**Comment by marekjez86** [comment]
Now also my Mac's hb-view produces correct view. I'm unable to reproduce the problem. I'm closing this bug. 

![notoserifthai-black otf 3](https://cloud.githubusercontent.com/assets/13322623/14220424/ee2d2cdc-f814-11e5-8f3b-3938605aa72b.png)
![notoserifthai-bold otf 3](https://cloud.githubusercontent.com/assets/13322623/14220426/ee2ea486-f814-11e5-9e3a-c40931760871.png)
![notoserifthai-regular otf 3](https://cloud.githubusercontent.com/assets/13322623/14220425/ee2dca0c-f814-11e5-9492-5d8a24dc84db.png)
![notoserifthai-thin otf 3](https://cloud.githubusercontent.com/assets/13322623/14220423/ee2b3e5e-f814-11e5-8167-7fb83b7dd480.png)
![notoserifthaicondensed-black otf 3](https://cloud.githubusercontent.com/assets/13322623/14220427/ee301438-f814-11e5-963b-58335923ff04.png)
![notoserifthaicondensed-bold otf 3](https://cloud.githubusercontent.com/assets/13322623/14220428/ee3f2b44-f814-11e5-833d-07ceb9932568.png)
![notoserifthaicondensed-regular otf 3](https://cloud.githubusercontent.com/assets/13322623/14220429/ee3f7040-f814-11e5-9f76-b3ef7b7f72f0.png)
![notoserifthaicondensed-thin otf 3](https://cloud.githubusercontent.com/assets/13322623/14220430/ee435962-f814-11e5-93bd-f381f46ef5ce.png)

**Comment by marekjez86** [comment]
added the input file with the sample text
[thai-sample2.txt.zip](https://github.com/googlei18n/fontmake/files/203410/thai-sample2.txt.zip)

**Comment by marekjez86** [comment]
[NotoSerifThai-Regular.otf.zip](https://github.com/googlei18n/fontmake/files/203468/NotoSerifThai-Regular.otf.zip)

I do not have actually the font from 20160401. This is from 20160404 (I broke my hb-view by trying to install ttfdiff, so I cannot confirm it's "good" - my guess it is still good).

**Comment by marekjez86** [comment]
I installed harbuzz hb-view (HarfBuzz) 1.2.4
the font above produces the following correctly looking output

![notoserifthai-regular otf 2](https://cloud.githubusercontent.com/assets/13322623/14266765/6be23fa2-fa7f-11e5-8ae9-d9219e4ea4b1.png)

**Comment by behdad** [comment]
Ok, it's a mystery how the original rendering happened, but indeed seems fixed now.
