### ISSUE TITLE
please advise: bad or good :-)

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#49]
I took an intermediate (early, for review) delivery of NotoSansArabic-MM.glyphs 
[NotoSansArabic-MM.glyphs.zip](https://github.com/googlei18n/fontmake/files/177017/NotoSansArabic-MM.glyphs.zip)
and ran through the pipeline creating 4 OTF fonts.

I took a sample Arabic text and created png files using hb-view.
I have no idea if what we generated is bad or good :-)
Please advise.

NotoSansArabic-Black.otf
[NotoSansArabic-Black.otf 2.zip](https://github.com/googlei18n/fontmake/files/176933/NotoSansArabic-Black.otf.2.zip)
![notosansarabic-black otf](https://cloud.githubusercontent.com/assets/13322623/13829694/a2d1547a-eb85-11e5-818b-b43dfa752cc9.png)

NotoSansArabic-Bold.otf
[NotoSansArabic-Bold.otf.zip](https://github.com/googlei18n/fontmake/files/176935/NotoSansArabic-Bold.otf.zip)
![notosansarabic-bold otf](https://cloud.githubusercontent.com/assets/13322623/13829729/bde9f46a-eb85-11e5-93d5-5b83bba83a67.png)

NotoSansArabic-Regular.otf
[NotoSansArabic-Regular.otf.zip](https://github.com/googlei18n/fontmake/files/176936/NotoSansArabic-Regular.otf.zip)
![notosansarabic-regular otf](https://cloud.githubusercontent.com/assets/13322623/13829754/d49e82d4-eb85-11e5-9314-3a36c278dafb.png)

NotoSansArabic-Thin.otf
[NotoSansArabic-Thin.otf.zip](https://github.com/googlei18n/fontmake/files/176938/NotoSansArabic-Thin.otf.zip)
![notosansarabic-thin otf](https://cloud.githubusercontent.com/assets/13322623/13829788/0b1f9dc0-eb86-11e5-9882-1bb61abdb7e6.png)

**Comment by marekjez86** [comment]
Here are the same samples from fonts generated by the Glyphs.app on Mac

![notosansarabic-black otf](https://cloud.githubusercontent.com/assets/13322623/13829900/baf6bfe4-eb86-11e5-9039-3fb5cab8d521.png)
![notosansarabic-bold otf](https://cloud.githubusercontent.com/assets/13322623/13829907/c5fc6fb0-eb86-11e5-8a3e-728e23e339f7.png)
![notosansarabic-regular otf](https://cloud.githubusercontent.com/assets/13322623/13829913/cdbde422-eb86-11e5-9897-d3705e3a2ca4.png)
![notosansarabic-thin otf](https://cloud.githubusercontent.com/assets/13322623/13829917/d3a0616c-eb86-11e5-9794-1a823c324ed0.png)

Whatever our pipeline does causes that we look different. (Note I also need feedback on the Glyphs.app fonts -- if they look bad it means that delivery of NotoSansArabic-MM.glyphs has problems). Please look and advise.

**Comment by marekjez86** [comment]
@behdad @roozbehp FYI

**Comment by roozbehp** [comment]
The version done by our pipeline seems to have messed up GPOS data.

**Comment by behdad** [comment]
There was a severe bug in the pipeline which I just fixed.  I'm confused.  Not sure how it was working at all, at least since February....  Please retest.

**Comment by behdad** [comment]
Works for me BTW.

**Comment by jamesgk** [comment]
Have you re-tested this Marek? I think it should be fixed.

**Comment by marekjez86** [comment]
Yes, tested it via fontdiff. It is fixed.
