### ISSUE TITLE
fontmake builds FiraCode-Bold with weight 80

### ISSUE THREAD

**Issue by fabiangreffrath** [googlei18n/fontmake#494]

**Comment by fabiangreffrath** [comment]
Now that it is possible to build FiraCode [1] from its Glyphs sources (thanks again for that!) another issue has popped up: The bold variant of that font ends up with the same weight value (80) as the regular variant. This confuses fontconfig so much, that it is pretty much impossible to explicitly select one variant over the other, see the attached screenshot of the GTK+3 font chooser.

```
$ cd fonts-firacode_1.206
$ fontmake -o otf -g FiraCode.glyphs
[...]
$ fc-scan master_otf/FiraCode-Regular.otf | grep weight
	weight: 80(f)(s)
$  fc-scan master_otf/FiraCode-Bold.otf | grep weight
	weight: 80(f)(s)
```

![bildschirmfoto vom 2018-12-23 13-51-48](https://user-images.githubusercontent.com/6449237/50383753-1f47e580-06ba-11e9-914a-0d05b2d057b6.png)

[1] https://github.com/tonsky/FiraCode

**Comment by fabiangreffrath** [comment]
The first two entries in the font chooser are the same font, i.e. the Bold variant, albeit one is called Regular. The second Bold variant in that list has been extra emboldened by fontconfig.

**Comment by fabiangreffrath** [comment]
This is on Debian with 
fontmake       1.8.0-1
python3-glyphslib 3.1.4-1
python3-ufo2ft 2.5.0-2

**Comment by moyogo** [comment]
What command are you running?

Here is what I do:
```bash
$ fontmake -i -o otf --optimize-cff 0 -g FiraCode.glyphs
[...]
$ fc-scan instance_otf/FiraCode-{Regular,Bold}.otf | grep weight
        weight: 80(f)(s)
        weight: 200(f)(s)
```
Running it without `-i` (which generates the interpolated instances) or with `-M` (which tries to generate the masters as instanced) instead will reproduce your issue because the masters only have information about their location on the weight interpolation axis, but have no information on the weightClass that fontconfig uses to calculate a font’s weight.
The right thing to do here is to generate the instances.

**Comment by fabiangreffrath** [comment]
@moyogo This was very helpful, thank you! I wonder why `-i` isn't the default, though. Is there any reason why you chose `--optimize-cff 0`?

**Comment by moyogo** [comment]
`--optimize-cff 0` builds the OTF faster without optmizitation.

**Comment by moyogo** [comment]
Yes, the default is `--optimize-cff 2` which creates smaller OTF files files but takes longer. Since that only affect the glyph’s outlines, it’s not needed when checking the weightClass of the fonts. Do use the default if you’re packaging the fonts.

**Comment by fabiangreffrath** [comment]
Works as expected, thank you very much!
