### ISSUE TITLE
OTOffsetOverflowError

### ISSUE THREAD

**Issue by laerm0** [googlei18n/fontmake#499]
Hi –

I am trying to build Vollkorn and am getting this error:

```INFO:fontTools.ttLib.tables.otBase:Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 2, 'SubTableIndex:', None, 'ItemName:', None, 'ItemIndex:', None)```

The command I am using is `fontmake -g sources/Vollkorn.glyphs -o variable`. The file I am using is in [my fork of Vollkorn, hinting branch](https://github.com/laerm0/Vollkorn-Typeface/tree/hinting).

Thanks!

**Comment by behdad** [comment]
@anthrotype Let's look into this next week.

**Comment by anthrotype** [comment]
Indeed, it was just that logging.INFO message, but the fontmake command completes without errors.
I cloned the repo and run fontmake sucessfully on Vollkorn.glyphs file from `hinting` branch. 

@laerm0 False alarm. You can ignore the message, that's just fonttools doing its thing (attempting to fix an offset overflow).

I think I will just demote it to DEBUG so users won't see it under normal circumstances.

**Comment by laerm0** [comment]
Ah, okay, great. Thanks everyone. I didn't know if it was yielding a properly built font or not.
