### ISSUE TITLE
make it possible to scale glyphs (and other metrics) when generating fonts from the source

### ISSUE THREAD

**Issue by jungshik** [googlei18n/fontmake#50]
It'd be handy to scale up or down glyphs and other metrics when the source scale (e.g. 1000/em) is different from the desired target scale (e.g. 2048/em).  

I came across this issue when I tried to transplant a few glyphs (U+2032 .. U+2034) from the source generated TTF to v2 Noto fonts in googlei18n/noto-fonts#510.   The former (source) is 1000/em while the latter is 2048/em. 

@roozbehp @dougfelt @xiangyexiao

**Comment by jungshik** [comment]
BTW, for googlei18n/noto-fonts#510, I just need to scale glyf and hmtx.

**Comment by davelab6** [comment]
BTW, since scaling by 2.048x and rounding points to integers can distort
the results, if the sources are quantized, it may be better scale by 2x and
adjust the spacing.

**Comment by behdad** [comment]
I suggest WONTFIXing this.  fontmake is a production pipeline, not a solution to every font design problem.  In your case, you should do the scaling and save the result into the source.

**Comment by davelab6** [comment]
Being able to produce fonts with different UPM to source files is something
a production pipeline needs to do from time to time; either with arbitrary
scaling (eg scaling by 2.048x to make a 1000/em source into a 2048/em
binary) that introduces distortions due to integer quantization, or seeks
to minimise that distortion.

If WONTFIX then it will need to be done in a font editor.

**Comment by behdad** [comment]
Changing UPEM we will do eventually.  But Jungshik wants to be able to rescale some glyphs, not all.

**Comment by davelab6** [comment]
Sure, but Jungshik wants to rescale in order to back port them to another
file; thus if the pipeline allowed rescaling all the glyphs, he could then
pick the ones to copy and they would drop in

**Comment by jungshik** [comment]
On the way home, I also thought about the implication of this (including rounding issues when going from 1000 to 2048). 

For my immediate need, (putting aside the issue of whether adding this feature to the pipeline is good or not ), I think I can scale 'manually' (or semi-automatically) as Behdad suggested. I'll do that for google-i18n/noto-fonts#510.

**Comment by adrientetar** [comment]
> I suggest WONTFIXing this.

Agreed.
