### ISSUE TITLE
When building a static font group-to-letter kerns are flattened

### ISSUE THREAD

**Issue by mjlagattuta** [googlei18n/fontmake#502]
When building a static font with ~4000 kerns, the final ttf results in ~9000 kerns. After looking into this more it appears that all group-group kerns are maintained and that any case where there is a group-letter or letter-group kern, then those pairs are flattened (i.e. @MMK_L_A + V would result in A + V, Aacute + V, Adieresis + V, etc.)

I have tested this out with the source as both a ufo and a glyphs file and cannot figure out if there is an issue with the source file or with fontmake.

Here is a zip of the ufo and glyphs source to replicate:
[Advent-Kerns.zip](https://github.com/googlei18n/fontmake/files/2775946/Advent-Kerns.zip)

I was building with the commands:
`fontmake -o ttf -g path/to/file` and `fontmake -o ttf -u path/to/file`

**Comment by anthrotype** [comment]
Like Behdad said, that’s how OpenType pair positioning lookups are structured.
I’m inclined to close this as wontfix. But feel free to propose alternatives, thanks.

**Comment by mjlagattuta** [comment]
Ah, I was unaware that ttfs only had glyph-glyph and class-class, thanks for clarifying that for me!
