### ISSUE TITLE
VF is building with incorrect style name in nameID 1 (is "Light," should be "Thin")

### ISSUE THREAD

**Issue by thundernixon** [googlei18n/fontmake#524]
In the project [Encode Sans](https://github.com/thundernixon/Encode-Sans), FontMake is building single-axis weight variable fonts with an unexpected style name in `nameID` 1.

Encode has weight instances from Thin to Black, coming from two masters which are labeled as "Light" and "Bold" in the GlyphsApp source. 

## Expectation

In order to display a naming matching the default instance – the "Thin" instance – in legacy apps, `nameID` 1 must be `Encode Sans Condensed Thin`.

```
    <namerecord nameID="1" platformID="3" platEncID="1" langID="0x409">
      Encode Sans Condensed Thin
    </namerecord>
    <namerecord nameID="2" platformID="3" platEncID="1" langID="0x409">
      Regular
    </namerecord>
```

## Actual result

The font gets the "Light" style name in `nameID` 1.

When I ttx the font as ouput by FontMake, `nameID`s 1 & 2 are:

```
    <namerecord nameID="1" platformID="3" platEncID="1" langID="0x409">
      Encode Sans Condensed Light
    </namerecord>
    <namerecord nameID="2" platformID="3" platEncID="1" langID="0x409">
      Regular
    </namerecord>
```

Here's [the current name-table ttx file](https://github.com/thundernixon/Encode-Sans/blob/fbd7792f575cc093a9de307833a467fa59e363cd/fonts/encodesanscondensed/split_vf/EncodeSansCondensed-Thin.ttx).

## To Reproduce

1. `git clone` https://github.com/thundernixon/Encode-Sans
2. Follow the [Build Process](https://github.com/thundernixon/Encode-Sans#build-process), using a command to build just a single "split" VF, such as

```
sources/scripts/build-split-vf.sh --condensed
```

3. Use `ttx` to analyze the `name` table of the output font, using a command like:

```
ttx -t name fonts/encodesanscondensed/split_vf/EncodeSansCondensed-Thin.ttf
```

4. If you want to edit the font sources, the GlyphsApp sources are available in `Encode-Sans/sources`. You can either edit the full source, then output the split build sources as described in the readme at [Build steps after edits to primary source](https://github.com/thundernixon/Encode-Sans#build-steps-after-edits-to-primary-source), _or_ you can directly edit the split Glyphs source if you want to quickly test something (making sure you edit the "condensed" source if you are building the Condensed split VF).

**Comment by madig** [comment]
This seems to happen because when you convert `Encode-Sans-condensed.glyphs` to UFOs plus Designspace, you get this excerpt from the Designspace file:

```XML
    <source filename="EncodeSansCondensed-Light.ufo" name="Encode Sans Condensed Light" familyname="Encode Sans Condensed" stylename="Light">
      <lib copy="1"/>
      <groups copy="1"/>
      <features copy="1"/>
      <info copy="1"/>
      <location>
        <dimension name="Weight" xvalue="34"/>
      </location>
    </source>
```

The `<info copy="1"/>` designates the UFO source that should be taken as the base font/default outline that other source deltas are bolted on on, so that's what ends up in name ID 1 and 2.

**Comment by madig** [comment]
I suppose the easiest fix here is to call the Thin master "Thin" instead of "Light". I think Glyphs 2.6 is less fussy about master names. Or you write a script to change stuff.

 Not sure if there's anything else to do here?

**Comment by thundernixon** [comment]
Ahh that makes sense, thank you, @madig!

Sure enough, when I renamed the "Light" master to "Thin," it works as needed.

I wonder if this is something worth changing in FontMake ... I would suggest that the sources/masters are just _inputs_ and should be able to have arbitrary names (e.g. A, B, and C or whatever else), and it is the instances that should define the _output_ variable font (e.g. canonical style names like Thin, Regular, Bold, etc). I could be off-base on that, but since so much about the output file comes from the Instances, why shouldn't the "base style" name?

**Comment by madig** [comment]
Hm, I have to defer to @anthrotype here, maybe there are reasons to do it like it's being done now. The source element has `name` and `stylename` attributes, so fontmake could use those. Not sure.

**Comment by moyogo** [comment]
This is a bug in the source AFAIC. Glyphs.app allows you to name the master, fontmake uses that because the designspace tells it to.

**Comment by thundernixon** [comment]
Thanks so much for the clarification! I'm getting a better sense for how things are connected.

I've read some code in a few repos, but I'm still not 100% sure what part of the toolchain is generating the font name table. However, a more accurate way to state this feature request is:

When nameID 1 is constructed, it should find `<info copy="1"/>` in the default `source`, then check which `instance` matches the axis values of that source, and use _that instance's_ name, rather than the source.

In the case of Encode Sans, the "Thin" `instance` matches the axis value of the default `source`.

```
<source filename="EncodeSansCondensed-Thin.ufo" name="Encode Sans Condensed Thin" familyname="Encode Sans Condensed" stylename="Thin">
    <lib copy="1"/>
    <groups copy="1"/>
    <features copy="1"/>
    <info copy="1"/>
    <location>
    <dimension name="Weight" xvalue="34"/>
    </location>
</source>
```
```
<instance name="Encode Sans Condensed Thin" familyname="Encode Sans Condensed" stylename="Thin" filename="../instance_ufo/EncodeSansCondensed-Thin.ufo" stylemapfamilyname="Encode Sans Condensed Thin" stylemapstylename="regular">
    <location>
    <dimension name="Weight" xvalue="34"/>
    </location>
    <kerning/>
    <info/>
</instance>
```

If this part is done by FontTools or glyphsLib, I'd be grateful to better understand which does it, and happy to post this request there.

However, I realize that I may not be seeing the full picture, and perhaps the design intent of FontMake is that source authors should expect to conform their sources to FontMake, rather than making FontMake overly flexible. If that is the case, it's understandable, and I appreciate the help here for the next person who might come along, searching for this issue. 

Please close this issue if it's not something that can /should be affected in FontMake.

**Comment by madig** [comment]
When you use fontmake, ufo2ft compiles the individual masters and fontTools.varLib.build() takes the main source (`info=1` and the default coordinate in the axes) and grafts the other masters onto that as deltas. The current way of doing things is simply, as Denis notes, the result of Designspace semantics. If something is declared `info=1`, then the tooling should take that as the source of, among others, name table defaults.

I think the primary issue here is that Glyphs files with Glyphs semantics get forcibly round-tripped through UFO+Designspace with different semantics because there is no man power to make a `glyphs2ft` to keep Glyphs semantics, leading to an impedance mismatch. You can however bring it up on the fontTools issue tracker.

**Comment by thundernixon** [comment]
Sounds good; if I run into the issue more, I'll take it over to fontTools.

Thanks for the discussion here!
