### ISSUE TITLE
Problem with on the fly mark positioning

### ISSUE THREAD

**Issue by sebastian-losch** [googlei18n/fontmake#525]
Hi,

In the fonts I generated with the current version of fontmake on the fly mark positioning doesn't work anymore. Combining marks are not using anchors. Is there anything that I'm doing wrong? I'm using this command, which used to work with previous versions of fontmake:

`fontmake -u font.ufo -o ttf`

Thanks in advance for your help.

**Comment by madig** [comment]
Do you mean mark-to-mark positioning? It works for me here, can you send me an example UFO?

**Comment by sebastian-losch** [comment]
Mark-to-mark as well as just mark. I can't share the UFO publicly, but I sent you an e-mail.

Thanks.

**Comment by madig** [comment]
Got it. You defined the `GDEF` table manually but only filled in the combining marks. This results in anchors from only three combining marks surviving into the final TTF. Deleting the entire `GDEF` statements makes things work (if it's missing, ufo2ft generates one for you). You need to define the `GDEF` with everything.

**Comment by sebastian-losch** [comment]
Thank you so much. I hope this didn't take too much of your time.

**Comment by madig** [comment]
No worries. It does however highlight how easy it is to get this wrong and have no idea what happened... Not sure what could be done to alert the user.
