### ISSUE TITLE
Input arguments don't include a Glyphs app generated VF

### ISSUE THREAD

**Issue by EbenSorkin** [googlei18n/fontmake#526]
The instructions as of now are 

Input arguments:
  The following arguments are mutually exclusive.

  -g GLYPHS, --glyphs-path GLYPHS
                        Path to .glyphs source file
  -u UFO [UFO ...], --ufo-paths UFO [UFO ...]
                        One or more paths to UFO files
  -m DESIGNSPACE, --mm-designspace DESIGNSPACE
                        Path to .designspace file

I would like to be able to process a Glyphs app variable font. May I use the  -g or is this in fact not supported?

Side question - it looks like Glyphs outputs a TTF flavored VF only. Is that correct?

**Comment by davelab6** [comment]
G should work!

Yes afaik TTF only, fdk for cff2, building from ufo

**Comment by EbenSorkin** [comment]
Thanks!

-e.

**Comment by madig** [comment]
`fontmake -g myfont.glyphs -o variable`

Currently, only TTF VFs are supported by fontTools. CFF2 support is pending.
