### ISSUE TITLE
Syntax problem?

### ISSUE THREAD

**Issue by EbenSorkin** [googlei18n/fontmake#527]
Here in a VirEnv : 

**(TestMerriweather) EbensiMacRetina:virtualenvs ebensorkin$**

I put in:

**fontmake -g myfont.glyphs -o variable /Users/ebensorkin/virtualenvs/TestMerriweather/MerriweatherGX.ttf**

But that failed. 

Because I get this error I think it looks like Fontmake thinks my path is part of the output argument

**fontmake: error: argument -o/--output: invalid choice: '/Users/ebensorkin/virtualenvs/TestMerriweather/MerriweatherGX.ttf' (choose from 'ufo', 'otf', 'ttf', 'ttf-interpolatable', 'otf-interpolatable', 'variable', 'variable-cff2')**

Should I form my command differently? If so how?

**Comment by madig** [comment]
`fontmake -g myfont.glyphs -o variable --output-path /Users/ebensorkin/virtualenvs/TestMerriweather/MerriweatherGX.ttf`

**Comment by moyogo** [comment]
madig beat me to it. You’re missing `--output-path` before the output file path, without it it is a value given to `-o`, a.k.a. `--output` for format(s).
