### ISSUE TITLE
Process one instance at a time

### ISSUE THREAD

**Issue by behdad** [googlei18n/fontmake#53]
Right now fontmake generates and saves UFO for all instances, then removeoverlaps them all, then save them.  Will be much more memory-efficient and as such probably even faster, if we process one instance completely, then the next, then the next...

**Comment by anthrotype** [comment]
I think this is addressed with the latest release.
We now call ufo2ft compileOTF/compileTTF on each UFOs in a generator expression that yields the built TTFont object one by one, then we save it to disk and continue to the next ufo. Ufo2ft filters are now responsible for running the expensive preprocessing operations like removing overlaps, converting outlines, etc.

Also, fontmake can now be told to only build a specific instance, by passing that instance's full name (the "name" attribute in the designspace document which uniquely identify the instance") to the `-i/--interpolate` option (no argument still means build all instances). 
So in theory now one could use GNU make or similar to call multiple fontmakes in parallel each building one instance, like I think @khaledhosny did for one of his projects (forgot which one).
