### ISSUE TITLE
What are *.glyphs files?

### ISSUE THREAD

**Issue by TonalidadeHidrica** [googlei18n/fontmake#537]
I am very afraid of asking this kind of basic question, but could somebody tell me what are *.glyphs files are?  I googled it, but as "glyphs" was regarded not as an extension but just a ordinary noun, I couldn't find resources about the file extension or format *.glyphs ...

**Comment by punchcutter** [comment]
These are files produced with the Glyphs application: https://glyphsapp.com/

**Comment by chrissimpkins** [comment]
@TonalidadeHidrica you can find some information about the files here too https://github.com/googlei18n/glyphslib

**Comment by TonalidadeHidrica** [comment]
Oh yes, that's exactly I wanted.  Thanks @punchcutter and @chrissimpkins !
I think it would be helpful for beginners like me if there are a link to glyphslib page in the README.md of this project, how do you think of it?
