### ISSUE TITLE
Overflow issue with Noto Sans Ethiopic

### ISSUE THREAD

**Issue by jamesgk** [googlei18n/fontmake#63]
Noto Sans Ethiopic has been crashing fontmake with something like

```
>> Saving OTF for NotoSansEthiopic-Medium
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
...
  File "/home/jamesgk/.local/lib/python2.7/site-packages/fontmake/font_project.py", line 157, in save_otfs
    otf.save(otf_path)
...
  File "/home/jamesgk/.local/lib/python2.7/site-packages/FontTools/fontTools/ttLib/tables/otBase.py", line 412, in getAllData
    tableData = table.getData()
  File "/home/jamesgk/.local/lib/python2.7/site-packages/FontTools/fontTools/ttLib/tables/otBase.py", line 282, in getData
    raise OTLOffsetOverflowError(overflowErrorRecord)
fontTools.ttLib.tables.otBase.OTLOffsetOverflowError: ('GPOS', 'LookupIndex:', 0, 'SubTableIndex:', 1, 'ItemName:', 'PairSet', 'ItemIndex:', 45)
```

Incredibly, this seems to be caused by https://github.com/unified-font-object/ufoLib/commit/44474ee8e5c1d6492cfdc01cc54a13fcc2c93094 (at least, reverting that commit fixes the issue). But I have no idea why. Where could those pairs possibly be used?

**Comment by behdad** [comment]
Ok, my guess is that the "conflict handling" logic is creating too many kerning pairs.  I can fix the overflow, and will, but also note that the Noto Sans Ethiopic has many thousands of bogus kerning records, many of them conflicting.

Now that defcon is fixed re not failing on conflicting kerning, we should go back and re-evaluate our strategy there, and tweak our kern tables to optimize for size.  Also, need to figure out what Glyphs is generating for conflicting kern pairs while doing so.

**Comment by jamesgk** [comment]
Well what's really strange to me is that a) `pairs` in that commit isn't actually used for UFO kerning, just error reporting and b) Defcon doesn't even call that validation code anymore! But I must be missing something somewhere.

**Comment by marekjez86** [comment]
Not reproducible
