### ISSUE TITLE
-o ttf-interpolatable does not work with designspace source

### ISSUE THREAD

**Issue by behdad** [googlei18n/fontmake#65]
Eg, when I do:
`
fontmake -m sample.designspace -o ttf-interpolatable
`
I expect to get masters in `master_ttf_interpolatable`, but what I get instead is the instances, put in `master_ttf_interpolatable`.

@jamesgk I have a test case for this if you need, I can email you.

**Comment by jamesgk** [comment]
No test case needed, this makes sense. The fact that instances are put into master output directories is a bug which should be easily fixed. But did you also want to produce master output from a designspace? Currently, any time you designate a designspace source, fontmake assumes you want to interpolate and produces instance UFOs which it compiles to binaries.

**Comment by jamesgk** [comment]
You can capture input master UFOs with something like `fontmake -u master_path/Family-*.ufo -o ttf-interpolatable`. Otherwise we can special-case designspace input with interpolatable output. Or add another argument to designate whether to interpolate with designspace input.

**Comment by behdad** [comment]
Thanks.  The way I see it, the .designspace mode is the entry point for "multiple UFO masters", so I expect it to respect the other arguments; ie. -o ttf-interpolatable to work.  Thanks for the tip re `fontmake -u 'master_path/Family-*.ufo' -o ttf-interpolatable`.

**Comment by behdad** [comment]
cc @letteror

**Comment by jamesgk** [comment]
Should be fixed by the commits linking to this issue.

**Comment by behdad** [comment]
Thanks.
