### ISSUE TITLE
Remove workaround for sorting glyph names

### ISSUE THREAD

**Issue by brawer** [googlei18n/fontmake#68]
Afaik fontmake currently sorts glyph names before passing them to fontmake/feaLib; this was done to work around https://github.com/behdad/fonttools/issues/504. Since @moyogo has kindly fixed this upstream bug, this workaround can now be removed.

**Comment by jamesgk** [comment]
I don't think anything was done to fontmake itself, just a one-time operation on the Roboto sources (I've opened an issue for that). Thanks for the heads up!
