### ISSUE TITLE
Invoke ttfautohint

### ISSUE THREAD

**Issue by brawer** [googlei18n/fontmake#7]
Invoke [ttfautohint](http://freetype.org/ttfautohint/) as part of the build pipeline, if installed and requested.

**Comment by behdad** [comment]
@anthrotype is working on Python bindings for ttfautohint library.

**Comment by jamesgk** [comment]
This was done in https://github.com/googlei18n/fontmake/pull/104

**Comment by anthrotype** [comment]
Thanks James. Sorry I couldn't find the time to work on this as I had promised.

**Comment by jamesgk** [comment]
No problem at all! Totally understand being tight on time.
