### ISSUE TITLE
Option to NOT save UFOs

### ISSUE THREAD

**Issue by behdad** [googlei18n/fontmake#71]
Since we don't need / use the UFOs, and saving them takes considerable time, have option to not write them? You can add ufo as another output format in -o

**Comment by behdad** [comment]
I suppose you need to save them, because you reload them right now, right?

**Comment by jamesgk** [comment]
The way MutatorMath works, I don't think there's any way to get around saving them.

**Comment by behdad** [comment]
I see...  Closing this now.
