### ISSUE TITLE
Disable compreffor until we figure out the build system

### ISSUE THREAD

**Issue by behdad** [googlei18n/fontmake#72]
The Python version of compreffor is a slow memory hog.  Disable until we make the C++ version buildable by setup.py...

**Comment by jamesgk** [comment]
I'm pretty sure the C++ version is now the default installation option for compreffor's setup.py (and the one installed by pip). Can anyone confirm?

**Comment by adrientetar** [comment]
Is there an easy way to tell which version ends up being run? That would be cool.

**Comment by anthrotype** [comment]
from the docstring:

> If a Compreffor is initialized with no method, Methods.NoPref is chosen. This
method automatically chooses the fastest available backend (order is exe, lib,
py). Availability is dependent on the presence of the compiled binary and library.

In the `compress` method, it tries the executable first, then the shared lib and finally the python method:

```python
        if self.method == Methods.NoPref:
            # choose fastest available method
            if os.path.exists(self.exe_path):
                self.run_executable()
            elif os.path.exists(self.lib_path):
                self.run_lib()
            else:
                self.run_py()
```

**Comment by anthrotype** [comment]
> I'm pretty sure the C++ version is now the default installation option for compreffor's setup.py

confirm. The `make` command is still used by setup.py to build the executable and shared library. Eventually, an extension module will be built with the usual distutils/setuptools.

**Comment by behdad** [comment]
sgtm
