### ISSUE TITLE
enhancement request: Could we treat errors/warnings as a set as opposed to a list?

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#79]
Currently when I run fontmake on NotoSerifDisplay-RomanMM.glyphs

I get the following

==== building src/NotoSerifDisplay-RomanMM.glyphs ====
WARNING: Duplicate kerning rules found for glyph pair "Tau, increment" (('public.kern1.T', 'increment', -50) and ('Tau', 'public.kern2.uni0394', -40)), 
removing pair from latter rule
WARNING: Duplicate kerning rules found for glyph pair "Tau, increment" (('public.kern1.T', 'increment', -50) and ('Tau', 'public.kern2.uni0394', -40)), 
removing pair from latter rule
WARNING: Duplicate kerning rules found for glyph pair "Tau, increment" (('public.kern1.T', 'increment', -50) and ('Tau', 'public.kern2.uni0394', -40)), 
removing pair from latter rule
WARNING: Duplicate kerning rules found for glyph pair "Tau, increment" (('public.kern1.T', 'increment', -50) and ('Tau', 'public.kern2.uni0394', -40)), 
removing pair from latter rule

They are just multiple occurrences of the same single issue:

WARNING: Duplicate kerning rules found for glyph pair "Tau, increment" (('public.kern1.T', 'increment', -50) and ('Tau', 'public.kern2.uni0394', -40)), 
removing pair from latter rule

I do not see the warnings or messages associated with the lines of text, therefore I'd prefer to see a single warning as opposed to warning repeated 4 time.

Could we treat errors/warnings as a set as opposed to a list?

**Comment by behdad** [comment]
That's weird indeed.

On Thu, May 19, 2016 at 11:08 AM, Marek Jeziorek <notifications@github.com>
wrote:

> Currently when I run fontmake on NotoSerifDisplay-RomanMM.glyphs
>
> I get the following
>
> ==== building src/NotoSerifDisplay-RomanMM.glyphs ====
> WARNING: Duplicate kerning rules found for glyph pair "Tau, increment"
> (('public.kern1.T', 'increment', -50) and ('Tau', 'public.kern2.uni0394',
> -40)),
> removing pair from latter rule
> WARNING: Duplicate kerning rules found for glyph pair "Tau, increment"
> (('public.kern1.T', 'increment', -50) and ('Tau', 'public.kern2.uni0394',
> -40)),
> removing pair from latter rule
> WARNING: Duplicate kerning rules found for glyph pair "Tau, increment"
> (('public.kern1.T', 'increment', -50) and ('Tau', 'public.kern2.uni0394',
> -40)),
> removing pair from latter rule
> WARNING: Duplicate kerning rules found for glyph pair "Tau, increment"
> (('public.kern1.T', 'increment', -50) and ('Tau', 'public.kern2.uni0394',
> -40)),
> removing pair from latter rule
>
> They are just multiple occurrences of the same single issue:
>
> WARNING: Duplicate kerning rules found for glyph pair "Tau, increment"
> (('public.kern1.T', 'increment', -50) and ('Tau', 'public.kern2.uni0394',
> -40)),
> removing pair from latter rule
>
> I do not see the warnings or messages associated with the lines of text,
> therefore I'd prefer to see a single warning as opposed to warning repeated
> 4 time.
>
> Could we treat errors/warnings as a set as opposed to a list?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/googlei18n/fontmake/issues/79>
>



-- 
behdad
http://behdad.org/

**Comment by jamesgk** [comment]
I think the actual issue here is that the warning is given for multiple masters in the source file, but the master is not included in the warning. So I'd suggest just including the master as a fix.
