### ISSUE TITLE
question: when duplicate kerning is present, could we utilize not a random strategy?

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#80]
Why wouldn't we use the following rule (I just made it up, so this might be just an uneducated/novice question :-)):
'When duplicate kerning rules found for a glyph pair then we use a rule that gets characters "closest" of the two rules if signs indicate this is "closer kerning", "furthest" otherwise'
when resolving the conflicts?

My "novice" thinking to justify this:
- kerning is mostly (all the time?) used to get characters "closer" 
- duplicate kerning is either a sign of incomplete (or not-fully debugged) design or maybe a conscious design decision (I have no idea about it)
- we could resolve the conflict in one of the following ways:
 a. randomly (that's what it looks to me right now)
if both signs of numbers are the same then [I assume signs are about getting closer or further]:
  b. pick a rule that gets characters "furtherest" of the two if signs indicate this is "further kerning"
  c. pick a rule that gets characters "closest" of the two if signs indicate this is "closer kerning"
if signs are different then to me it indicates that the designer is very confused and we should do a. (random) or 
 d. pick an average between the two numbers :-)

Just an idea/question from a novice in the "font business."

the list below is just a fragment from processing Ethiopic glyphs with the highest absolute number of the pair in bold
WARNING: Duplicate kerning rules found for glyph pair "zwa.ethiopic, zhwa.ethiopic" (('public.kern1.li.ethiopic', 'zhwa.ethiopic', **-106**) and ('zwa.ethiopic', 'public.kern2.ze.ethiopic', -83)), removing pair from latter rule
WARNING: Duplicate kerning rules found for glyph pair "zwa.ethiopic, zhwa.ethiopic" (('public.kern1.li.ethiopic', 'zhwa.ethiopic', **-115**) and ('zwa.ethiopic', 'public.kern2.ze.ethiopic', -110)), removing pair from latter rule
WARNING: Duplicate kerning rules found for glyph pair "zwa.ethiopic, zhwa.ethiopic" (('public.kern1.li.ethiopic', 'zhwa.ethiopic', **-125**) and ('zwa.ethiopic', 'public.kern2.ze.ethiopic', -83)), removing pair from latter rule
WARNING: Duplicate kerning rules found for glyph pair "zwa.ethiopic, zhwa.ethiopic" (('public.kern1.li.ethiopic', 'zhwa.ethiopic', **-167**) and ('zwa.ethiopic', 'public.kern2.ze.ethiopic', -110)), removing pair from latter rule
WARNING: Duplicate kerning rules found for glyph pair "zwa.ethiopic, zhwa.ethiopic" (('public.kern1.li.ethiopic', 'zhwa.ethiopic', -65) and ('zwa.ethiopic', 'public.kern2.ze.ethiopic', **-83**)), removing pair from latter rule
WARNING: Duplicate kerning rules found for glyph pair "zwa.ethiopic, zhwa.ethiopic" (('public.kern1.li.ethiopic', 'zhwa.ethiopic', -86) and ('zwa.ethiopic', 'public.kern2.ze.ethiopic', **-110**)), removing pair from latter rule

**Comment by behdad** [comment]
So, this is not just about conflicting rules; the file has duplicate kern entries, right?!

**Comment by jamesgk** [comment]
I believe so, though we no longer report duplicates, only conflicts (perhaps the warning message should be changed). In my mind this issue is only about conflicts; in the case of duplicate rules we already have one single value that the source author meant to use for the kerning pair.

**Comment by marekjez86** [comment]
I actually do not know how to check for duplicate/conflicting kern entries.
The source is at
https://github.com/googlei18n/noto-source/blob/master/src/NotoSansEthiopic-MM.glyphs



On Thu, May 19, 2016 at 4:42 PM, James Godfrey-Kittle <
notifications@github.com> wrote:

> I believe so, though we no longer report duplicates, only conflicts
> (perhaps the warning message should be changed). In my mind this issue is
> only about conflicts; in the case of duplicate rules we already have one
> single value that the source author meant to use for the kerning pair.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/googlei18n/fontmake/issues/80#issuecomment-220479134>
>



-- 

Marek Z Jeziorek [ 老马 ] | marekj@google.com | 312 725-6958

**Comment by jamesgk** [comment]
Well basically we are checking for conflicting kern entries just by running fontmake on the source.

**Comment by jamesgk** [comment]
Note that as of https://github.com/googlei18n/fontmake/pull/85 being merged the choice of rule should be deterministic and we should be doing the same thing as Glyphs: always using the last rule which appears in the Glyphs source. Not sure if we want to improve further than that.

**Comment by marekjez86** [comment]
I consider the issue resolved.
