### ISSUE TITLE
building src/NotoSansArabic-MM.glyphs causes ValueError: math domain error

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#87]
< Traceback (most recent call last):
<   File "/usr/local/bin/fontmake", line 9, in <module>
<     load_entry_point('fontmake==1.0', 'console_scripts', 'fontmake')()
<   File "build/bdist.linux-x86_64/egg/fontmake/__main__.py", line 43, in main
<   File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 237, in run_from_glyphs
<   File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 282, in run_from_ufos
<   File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 143, in build_otfs
<   File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/misc/loggingTools.py", line 372, in wrapper
<     return func(*args, **kwds)
<   File "build/bdist.linux-x86_64/egg/fontmake/font_project.py", line 97, in remove_overlaps
<   File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/booleanOperations/booleanOperationManager.py", line 58, in union
<     return _performOperation("union", contours, [], outPen)
<   File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/booleanOperations/booleanOperationManager.py", line 47, in _performOperation
<     outputContour.reCurveSubSegments(inputContours)
<   File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/booleanOperations/flatten.py", line 882, in reCurveSubSegments
<     tValues = inputSegment.tValueForPoint(searchPoint)
<   File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/booleanOperations/flatten.py", line 254, in tValueForPoint
<     return _tValueForPointOnCubicCurve(point, (on1, off1, off2, on2))
<   File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/booleanOperations/flatten.py", line 1050, in _tValueForPointOnCubicCurve
<     return _tValueForPointOnCubicCurve(point, (pt1, pt2, pt3, pt4), isHorizontal=1)
<   File "/usr/local/google/home/marekj/.local/lib/python2.7/site-packages/booleanOperations/flatten.py", line 1046, in _tValueForPointOnCubicCurve
<     d[isHorizontal] - point[isHorizontal])
<   File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/misc/bezierTools.py", line 328, in solveCubic
<     theta = acos(min(R/sqrt(Q*Q*Q), 1.0))
< ValueError: math domain error

to reproduce it run the pipeline with https://github.com/googlei18n/noto-source/blob/master/src/NotoSansArabic-MM.glyphs

**Comment by behdad** [comment]
Should be fixed.  Sorry about that.

**Comment by marekjez86** [comment]
verified as fixed. thank you
