### ISSUE TITLE
resolution needed: handling of *.cmap.txt files (and the information they contain)

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#90]
marekjez86 wrote to @JelleBosmaMT: This delivery also had src/NotoSansDevanagari/NotoSansDevanagariUI.cmap.txt . I have never seen it in the delivery. It is not referenced explicitly. Is this intentional?

The text below was copied from @JelleBosmaMT 's response e-mail:

[...]
The cmap file has been part of all previous Devanagari deliveries:
starting with the trial data with 2 and 4 masters.

I noted that it was missing from the GitHub repository when I was pointed
towards it in order to get the .plist package list, which I was expected
to update for the new file names. On the 2nd of June I posted the
following message about the format of the package list. I did not see a
response, which also mentions the missing cmap file:

On 02-jun.-16 15:10, @JelleBosmaMT wrote:

>Hi,
>
>
>I prepared a set deliverables of Noto Sans Devanagari and Sinhala. As a
>test our QE team is expected to generate fonts from the source files with
>the pipeline or fontmake as it seems to be called. Therefore I was asked
>to provide a new .plist file based
>on one that can be found on GitHub
>(https://github.com/googlei18n/fontmake/tree/master/test/NotoSansDevanagar
>i).
>
>
>In the package list the OTL source files are assigned to the masters in
>the .glyphs file. I did not think that would work, and it turns out it
>doesn’t. One cannot assign the OTL source files of the UI font to the UI
>masters as the sample file does, because
>there are no UI masters. And although makefont generates fonts with the
>OTL sources assigned to the masters that do exist, this produces  fonts
>that are simply 8 fonts with the outlines from the 8 masters with OTL
>tables of the document fonts. That is of course
>very different from what is intended.
>
>
>The OTL sources have only an indirect relation ship with the masters. The
>.glyphs files define one or more font families with a range of widths and
>weights: the instances. The masters and OTL source files are ingredients
>that go into these font families.
>The link between master, OTL source and these families with instances are
>the interpolation values.
>
>
>So I propose to modify the .plist to assign the OTL source files to
>Family name + interpolation values:
>
>
><key>NotoSansDevanagari-SemiBold</key>
>Should refer to the font family Noto Sans Devanagari with interpolation
>values weight = 151 and width = 100
>
>
>The <key>NotoSansDevanagariUI-SemiBold</key> which currently points to
>nothing, would have to point to the font family Noto Sans Devanagari UI.
>
>
>I assume XML experts have more advanced ways of expressing this, I am
>just trying something to make my point, that OTL sources are assigned to
>interpolation values of font families:
>
>
>
><key>Noto Sans Devanagari</key>
><dict>
>...
><key>151 100</key>
><dict>
><key>GDEF</key>
><string>Noto Sans Devanagari GDEF.txt</string>
><key>GPOS</key>
><string>Noto Sans Devanagari 151-100 GPOS.txt</string>
><key>GSUB</key>
><string>Noto Sans Devanagari 151-100 GSUB.txt</string>
></dict>
>
>…
></dict>
>
><key>Noto Sans Devanagari UI</key>
><dict>
>...
><key>151 100</key>
><dict>
><key>GDEF</key>
><string>Noto Sans Devanagari UI GDEF.txt</string>
><key>GPOS</key>
><string>Noto Sans Devanagari UI 151-100 GPOS.txt</string>
><key>GSUB</key>
><string>Noto Sans Devanagari UI 151-100 GSUB.txt</string>
><key>cmap</key>
><string>NotoSansDevanagariUI.cmap</string>
>
></dict>
>
>…
></dict>
>

>
>I could not help noticing that in the GitHub page with test data for Noto
>Sans Devanagari the provided source file for the cmap of the UI fonts is
>missing. Of course the cmap files would have to be added to the updated
>format of the package list.
>

**Comment by marekjez86** [comment]
@brawer : Sascha, could you look at it (Behdad is available to work on it at the end of June)?

**Comment by jamesgk** [comment]
Oh, I think I could also take this. The cmap file in question is https://github.com/googlei18n/noto-source/blob/master/src/NotoSansDevanagari/NotoSansDevanagariUI.cmap.txt and it seems straightforward enough to use that data to construct a new cmap table for certain fontmake outputs.

**Comment by jamesgk** [comment]
The other question here is how to correctly handle external GPOS/GSUB for Devanagari; that's a seperate issue that Behdad and I were going to discuss at the end of June.

**Comment by JelleBosmaMT** [comment]
On 17-jun.-16 00:31, "James Godfrey-Kittle" <notifications@github.com>
wrote:

>Oh, I think I could also take this. The cmap file in question is
>https://github.com/googlei18n/noto-source/blob/master/src/NotoSansDevanaga
>ri/NotoSansDevanagariUI.cmap.txt and it seems straightforward enough to
>use that data to construct a new cmap table for certain fontmake outputs.

FYI: the cmap file lists code, glyph name and glyph index. The glyph index
has been added to the format in order to have the option  to use it for
TTFs with format 3 post tables. Using the name is of course the safer
option to find the glyph index.



>
